/********************************************************************************************************
   	Module		:  rmcr_63_source_infomap_export

   	Function	:  This macro will be used to create export package for infomaps from 63 to 81.

	Called-by	:  NONE
	Calls		:  	NONE
					
   	Parameters	:  None
	Author		:   RM Team
	
	Sample call :
					%let m_staging_area_path=/tmp;
					%let m_source_code_path=/tmp/source_code;
					%include "&m_source_code_path/rmcr_63_source_infomap_export.sas";
					%CSBINIT;
					%rmcr_63_source_infomap_export();
				   
*********************************************************************************************************/

%macro rmcr_63_source_infomap_export();

	%if %symexist(job_rc)=0 %then %do;
	%global job_rc;
	%end;
	%if %symexist(sqlrc)=0 %then %do;
		%global sqlrc;
	%end;
	
	/****** Creating macro variable m_staging_area which holds the staging path ******/
	
	%let m_staging_area=&m_staging_area_path;
	
	/****** Creating a timestamp macro variable that will be used for logs and txt files ******/	
	data _null_;   
	   call symputx('timestamp', put(datetime(),datetime20.));    /* i18nOK:Line */
	run;
	%let timestamp=%sysfunc(ktranslate(&timestamp,'.',':'));    /* i18nOK:Line */
	 
	/****** path_to_migration is a macro variable that holds the path of folder cs63_export_pkg 
		under which all folders will be made ******/	
	%let path_to_migration=;
	%dabt_make_work_area(dir=&m_staging_area, create_dir=cs63_export_pkg, path=path_to_migration);
	%let path_to_migration=&path_to_migration;
	
	/****** path_to_log is a macro variable that holds the path of log folder under cs63_export_pkg log ******/	
	%let path_to_log=;
	%dabt_make_work_area(dir=&path_to_migration, create_dir=log, path=path_to_log);
	%let path_to_log=&path_to_log;

	/****** Divert log to log folder ******/
	proc printto log="&path_to_log/rmcr_63_source_infomap_export_&timestamp..log";    /* i18nOK:Line */
	run;
	
	/****** Create directory for source data xpt -starts ******/		
	%let path_to_source_data_xpt=;
	%dabt_make_work_area(dir=&path_to_migration, create_dir=source_data, path=path_to_source_data_xpt);
	%let path_to_source_data_xpt=&path_to_source_data_xpt;
	/****** Create directory for source data xpt -ends ******/
	
	/****** Create directory for source infomaps -starts ******/		
	%let path_to_source_im_xpt=;
	%dabt_make_work_area(dir=&path_to_source_data_xpt, create_dir=source_im, path=path_to_source_im_xpt);
	%let path_to_source_im_xpt=&path_to_source_im_xpt;
	/****** Create directory for source infomaps  -ends ******/
	/********************************************************************
	MACRO DEFINITON STARTS FOR INFOMAPS VIEWS
	*********************************************************************/
	%macro rmcr_63_infomaps_export();
	
	/*start to check if banking content applied*/
	%let bnk_cnt_appl=;
		
	proc sql;
	select count(*) into :bnk_cnt_appl from &lib_apdm..CS_CR_INFO     /* i18nOK:Line */
	where cr_unique_cd='BANKING_BASEL' and status_sk=1 ;				/* i18nOK:Line */
	quit;
	
	%let bnk_cnt_appl=&bnk_cnt_appl;

	%if &bnk_cnt_appl ge 1 %then %do;

		/* Create work table of all the IM's */
		PROC SQL noprint;
		Create table work.INQUIRY_FACT_BASE as
		SELECT 
		/* i18nOK:BEGIN */
			table0.ACCOUNT_RK AS ACCOUNT_RK LABEL='ACCOUNT_RK',  	
			table3.CREDIT_FACILITY_RK AS CREDIT_FACILITY_RK LABEL='CREDIT_FACILITY_RK',
			table0.PRIMARY_CUSTOMER_RK AS CUSTOMER_RK LABEL='CUSTOMER_RK',
			table5.DISPUTE_AMT AS DISPUTE_AMT LABEL='DISPUTE_AMT' FORMAT=NLNUM18.5,
			table5.INQUIRY_CNT AS INQUIRY_CNT LABEL='INQUIRY_CNT',
			 ( table8.PERIOD_LAST_DTTM )  AS PERIOD_LAST_DTTM LABEL='PERIOD_LAST_DTTM' FORMAT=NLDATM21.,
			table0.ACCOUNT_TYPE_CD AS ACCOUNT_TYPE_CD LABEL='ACCOUNT_TYPE_CD' FORMAT=$3.,
			table0.ACCOUNT_SUB_TYPE_CD AS ACCOUNT_SUB_TYPE_CD LABEL='ACCOUNT_SUB_TYPE_CD' FORMAT=$3.,
			table6.FINANCIAL_PRODUCT_TYPE_CD AS FINANCIAL_PRODUCT_TYPE_CD LABEL='FINANCIAL_PRODUCT_TYPE_CD' FORMAT=$3.,
			table6.PRODUCT_SUB_TYPE_CD AS PRODUCT_SUB_TYPE_CD LABEL='PRODUCT_SUB_TYPE_CD' FORMAT=$3.,
			table3.CREDIT_FACILITY_TYPE_CD AS CREDIT_FACILITY_TYPE_CD LABEL='CREDIT_FACILITY_TYPE_CD' FORMAT=$3.,
			table10.TRANSACTION_TYPE_CD AS TRANSACTION_TYPE_CD LABEL='TRANSACTION_TYPE_CD' FORMAT=$3.,
			table7.INQUIRY_STATUS_CD AS INQUIRY_STATUS_CD LABEL='INQUIRY_STATUS_CD' FORMAT=$3.,
			table9.RESOLUTION_CD AS RESOLUTION_CD LABEL='RESOLUTION_CD' FORMAT=$3.,   	
			/* i18nOK:END */
			 ( CASE  WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&CHK_ACCOUNT_SUB_TYPE) THEN  &ACC_HIER_CHK
			 WHEN table0.ACCOUNT_TYPE_CD IN (&CCD_ACCOUNT_TYPE) THEN &ACC_HIER_CCD
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&SAV_ACCOUNT_SUB_TYPE,&CHK_ACCOUNT_SUB_TYPE) AND table0.ALLOW_OVERDRAFT_FLG IN (&CHECK_FLAG_TRUE)  THEN &ACC_HIER_OD
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN (&RDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_RD
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN  (&SAV_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_SAV 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&MTG_ACCOUNT_TYPE, &LON_ACCOUNT_TYPE) AND table0.COLLATERAL_CD IS NOT NULL THEN &ACC_HIER_SLN  
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD  IN (&TDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_TD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&LON_ACCOUNT_TYPE) AND (table0.COLLATERAL_CD IS NULL) THEN &ACC_HIER_ULN  ELSE ' '  END  )  AS ACCOUNT_HIERARCHY_CD LABEL='ACCOUNT_HIERARCHY_CD'   	/* i18nOK:LINE */
		FROM
			dim.ACCOUNT_DIM as table0 Inner join fact.INQUIRY_FACT as table5 on table0.ACCOUNT_SK = table5.ACCOUNT_SK 
			 Inner join dim.CREDIT_FACILITY_DIM as table3 on table3.CREDIT_FACILITY_SK = table5.CREDIT_FACILITY_SK 
			 Inner join dim.FINANCIAL_PRODUCT_DIM as table6 on table6.PRODUCT_SK = table5.PRODUCT_SK 
			 Inner join dim.INQUIRY_STATUS_DIM as table7 on 
			table7.INQUIRY_STATUS_SK = table5.INQUIRY_STATUS_SK 
			Inner join dim.TIME_DIM as table8 on table8.TIME_SK = table5.TIME_SK 
			Inner join dim.RESOLUTION_DIM as table9 on table9.RESOLUTION_SK = table5.RESOLUTION_SK 
			Inner join dim.TRANSACTION_TYPE_DIM as table10 on table10.TRANSACTION_TYPE_SK = table5.TRANSACTION_TYPE_SK ;
		quit;
		
		%dabt_err_chk(type=SQL);
		

		PROC SQL ;
		Create table work.OUTBOUND_COMM_FACT_BASE as
		SELECT 
		/* i18nOK:BEGIN */
			table0.ACCOUNT_RK AS ACCOUNT_RK LABEL='ACCOUNT_RK',  	
			table4.CREDIT_FACILITY_RK AS CREDIT_FACILITY_RK LABEL='CREDIT_FACILITY_RK',
			table5.CUSTOMER_RK AS CUSTOMER_RK LABEL='CUSTOMER_RK',
			table7.OUTBOUND_COMM_CNT AS OUTBOUND_COMM_CNT LABEL='OUTBOUND_COMM_CNT',
			 ( table8.PERIOD_LAST_DTTM )  AS PERIOD_LAST_DTTM LABEL='PERIOD_LAST_DTTM' FORMAT=NLDATM21.,
			table0.ACCOUNT_TYPE_CD AS ACCOUNT_TYPE_CD LABEL='ACCOUNT_TYPE_CD' FORMAT=$3.,
			table0.ACCOUNT_SUB_TYPE_CD AS ACCOUNT_SUB_TYPE_CD LABEL='ACCOUNT_SUB_TYPE_CD' FORMAT=$3.,
			table6.FINANCIAL_PRODUCT_TYPE_CD AS FINANCIAL_PRODUCT_TYPE_CD LABEL='FINANCIAL_PRODUCT_TYPE_CD' FORMAT=$3.,
			table6.PRODUCT_SUB_TYPE_CD AS PRODUCT_SUB_TYPE_CD LABEL='PRODUCT_SUB_TYPE_CD' FORMAT=$3.,
			table4.CREDIT_FACILITY_TYPE_CD AS CREDIT_FACILITY_TYPE_CD LABEL='CREDIT_FACILITY_TYPE_CD' FORMAT=$3.,
			table9.TRANSACTION_TYPE_CD AS TRANSACTION_TYPE_CD LABEL='TRANSACTION_TYPE_CD' FORMAT=$3.,
			table2.CHANNEL_CD AS CHANNEL_CD LABEL='CHANNEL_CD' FORMAT=$3.,   	
			/* i18nOK:END */
			 ( CASE  WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&CHK_ACCOUNT_SUB_TYPE) THEN  &ACC_HIER_CHK
			 WHEN table0.ACCOUNT_TYPE_CD IN (&CCD_ACCOUNT_TYPE) THEN &ACC_HIER_CCD
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&SAV_ACCOUNT_SUB_TYPE,&CHK_ACCOUNT_SUB_TYPE) AND table0.ALLOW_OVERDRAFT_FLG IN (&CHECK_FLAG_TRUE)  THEN &ACC_HIER_OD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN (&RDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_RD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN  (&SAV_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_SAV 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&MTG_ACCOUNT_TYPE, &LON_ACCOUNT_TYPE) AND table0.COLLATERAL_CD IS NOT NULL THEN &ACC_HIER_SLN      
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD  IN (&TDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_TD  
			 WHEN table0.ACCOUNT_TYPE_CD IN (&LON_ACCOUNT_TYPE) AND (table0.COLLATERAL_CD IS NULL) THEN &ACC_HIER_ULN  ELSE ' '  END  )  AS ACCOUNT_HIERARCHY_CD LABEL='ACCOUNT_HIERARCHY_CD'    	/* i18nOK:LINE */
		FROM
			dim.ACCOUNT_DIM table0 Inner join fact.OUTBOUND_COMM_FACT table7 on table0.ACCOUNT_SK = table7.ACCOUNT_SK  Inner join dim.CHANNEL_DIM table2 on table2.CHANNEL_SK = table7.CHANNEL_SK 
		Inner join dim.customer_DIM table5 on table5.CUSTOMER_SK = table7.CUSTOMER_SK 
		 Inner join dim.CREDIT_FACILITY_DIM table4 on table4.CREDIT_FACILITY_SK = table7.CREDIT_FACILITY_SK 
		 Inner join dim.FINANCIAL_PRODUCT_DIM table6 on table6.PRODUCT_SK = table7.PRODUCT_SK 
		Inner join dim.TIME_DIM table8 on table8.TIME_SK = table7.TIME_SK 
		Inner join dim.TRANSACTION_TYPE_DIM table9 on table9.TRANSACTION_TYPE_SK = table7.TRANSACTION_TYPE_SK ;
		quit;


		%dabt_err_chk(type=SQL);

		

		PROC SQL ;
		Create table WORK.CORP_CRD_FACILITY_X_CUSTOMER as
		SELECT 
		/* i18nOK:BEGIN */
			table0.CUSTOMER_SK AS CUSTOMER_SK LABEL='CUSTOMER_SK' FORMAT=12.,    	
			table0.CUSTOMER_RK AS CUSTOMER_RK LABEL='CUSTOMER_RK' FORMAT=12.,
			table0.CUSTOMER_ID AS CUSTOMER_ID LABEL='CUSTOMER_ID',
			table0.ORGANIZATION_TYPE_CD AS ORGANIZATION_TYPE_CD LABEL='ORGANIZATION_TYPE_CD',
			table0.CUSTOMER_CITY_NM AS CUSTOMER_CITY_NM LABEL='CUSTOMER_CITY_NM',
			table0.CUSTOMER_POSTAL_CD AS CUSTOMER_POSTAL_CD LABEL='CUSTOMER_POSTAL_CD',
			table0.CUSTOMER_STATE_REGION_CD AS CUSTOMER_STATE_REGION_CD LABEL='CUSTOMER_STATE_REGION_CD',
			table0.CUSTOMER_COUNTRY_CD AS CUSTOMER_COUNTRY_CD LABEL='CUSTOMER_COUNTRY_CD',
			table0.CUSTOMER_TYPE_CD AS CUSTOMER_TYPE_CD LABEL='CUSTOMER_TYPE_CD',
			table0.CUSTOMER_ACTIVE_CD AS CUSTOMER_ACTIVE_CD LABEL='CUSTOMER_ACTIVE_CD',
			table0.CUSTOMER_LIFECYCLE_CD AS CUSTOMER_LIFECYCLE_CD LABEL='CUSTOMER_LIFECYCLE_CD',
			table0.BANKRUPTCY_STATUS_CD AS BANKRUPTCY_STATUS_CD LABEL='BANKRUPTCY_STATUS_CD',
			table0.PENDING_LAWSUIT_FLG AS PENDING_LAWSUIT_FLG LABEL='PENDING_LAWSUIT_FLG',
			table0.LEGAL_JUDGEMENT_FLG AS LEGAL_JUDGEMENT_FLG LABEL='LEGAL_JUDGEMENT_FLG',
			table0.TAX_BRACKET_CD AS TAX_BRACKET_CD LABEL='TAX_BRACKET_CD',
			table0.TAX_ID AS TAX_ID LABEL='TAX_ID',
			table0.TAX_ID_TYPE_CD AS TAX_ID_TYPE_CD LABEL='TAX_ID_TYPE_CD',
			table0.FIRST_ACCOUNT_TYPE_CD AS FIRST_ACCOUNT_TYPE_CD LABEL='FIRST_ACCOUNT_TYPE_CD',
			table0.EVER_IN_COLLECTION_FLG AS EVER_IN_COLLECTION_FLG LABEL='EVER_IN_COLLECTION_FLG',
			table0.PREFERRED_CHANNEL_CD AS PREFERRED_CHANNEL_CD LABEL='PREFERRED_CHANNEL_CD',
			table0.OTHER_BANK_CLIENT_FLG AS OTHER_BANK_CLIENT_FLG LABEL='OTHER_BANK_CLIENT_FLG',
			table0.OTHER_CREDIT_CARDS_CNT AS OTHER_CREDIT_CARDS_CNT LABEL='OTHER_CREDIT_CARDS_CNT',
			table0.ANNUAL_INCOME_AMT AS ANNUAL_INCOME_AMT LABEL='ANNUAL_INCOME_AMT',
			table0.INTERNAL_CREDIT_RATING_CD AS INTERNAL_CREDIT_RATING_CD LABEL='INTERNAL_CREDIT_RATING_CD',
			table0.PRIMARY_INTERNAL_ORG_RK AS PRIMARY_INTERNAL_ORG_RK LABEL='PRIMARY_INTERNAL_ORG_RK' FORMAT=12.,
			table0.INDUSTRY_CD AS INDUSTRY_CD LABEL='INDUSTRY_CD',
			table0.NUM_EMPLOYEES_CNT AS NUM_EMPLOYEES_CNT LABEL='NUM_EMPLOYEES_CNT',
			table0.EXTERNAL_CREDIT_RATING1_CD AS EXTERNAL_CREDIT_RATING1_CD LABEL='EXTERNAL_CREDIT_RATING1_CD',
			table0.NUM_OFFICES_CNT AS NUM_OFFICES_CNT LABEL='NUM_OFFICES_CNT',
			table0.EXTERNAL_CREDIT_RATING2_CD AS EXTERNAL_CREDIT_RATING2_CD LABEL='EXTERNAL_CREDIT_RATING2_CD',
			table0.OWNERSHIP_CNT AS OWNERSHIP_CNT LABEL='OWNERSHIP_CNT',
			table0.CUSTOMER_CLASS_CD AS CUSTOMER_CLASS_CD LABEL='CUSTOMER_CLASS_CD',
			table0.OWNERSHIP_CD AS OWNERSHIP_CD LABEL='OWNERSHIP_CD',
			table0.BUSINESS_NATURE_CD AS BUSINESS_NATURE_CD LABEL='BUSINESS_NATURE_CD',
			 ( table0.VALID_START_DTTM )  AS VALID_START_DTTM LABEL='VALID_START_DTTM' FORMAT=NLDATM21.,
			 ( table0.VALID_END_DTTM )  AS VALID_END_DTTM LABEL='VALID_END_DTTM' FORMAT=NLDATM21.,
			 ( table0.CURRENT_COUNTRY_START_DT )  AS CURRENT_COUNTRY_START_DT LABEL='CURRENT_COUNTRY_START_DT' FORMAT=NLDATM21.,
			 ( table0.BANKRUPTCY_FILED_DT )  AS BANKRUPTCY_FILED_DT LABEL='BANKRUPTCY_FILED_DT' FORMAT=NLDATM21.,
			 ( table0.INCORPORATION_DT )  AS INCORPORATION_DT LABEL='INCORPORATION_DT' FORMAT=NLDATM21.,
			 ( table0.BUSINESS_COMMENCED_DT )  AS BUSINESS_COMMENCED_DT LABEL='BUSINESS_COMMENCED_DT' FORMAT=NLDATM21.,
			 ( table0.BUSINESS_ESTABLISHED_DT )  AS BUSINESS_ESTABLISHED_DT LABEL='BUSINESS_ESTABLISHED_DT' FORMAT=NLDATM21.,
			 ( table0.CURRENT_ADDRESS_START_DT )  AS CURRENT_ADDRESS_START_DT LABEL='CURRENT_ADDRESS_START_DT' FORMAT=NLDATM21.,
			 ( table0.FIRST_ACCOUNT_OPEN_DT )  AS FIRST_ACCOUNT_OPEN_DT LABEL='FIRST_ACCOUNT_OPEN_DT' FORMAT=NLDATM21.,
			table1.CREDIT_FACILITY_SK AS CREDIT_FACILITY_SK LABEL='CREDIT_FACILITY_SK',
			table1.CREDIT_FACILITY_RK AS CREDIT_FACILITY_RK LABEL='CREDIT_FACILITY_RK' FORMAT=12.,
			table1.CREDIT_FACILITY_ID AS CREDIT_FACILITY_ID LABEL='CREDIT_FACILITY_ID',
			table1.CURRENCY_CD AS CURRENCY_CD LABEL='CURRENCY_CD',
			table1.LIMIT_AMT AS LIMIT_AMT LABEL='LIMIT_AMT',
			table1.IN_DEFAULT_FLG AS IN_DEFAULT_FLG LABEL='IN_DEFAULT_FLG',
			table1.SPECIALIZED_LENDING_CD AS SPECIALIZED_LENDING_CD LABEL='SPECIALIZED_LENDING_CD',
			table1.SENIORITY_CD AS SENIORITY_CD LABEL='SENIORITY_CD',
			table1.CREDIT_FACILITY_TYPE_CD AS CREDIT_FACILITY_TYPE_CD LABEL='CREDIT_FACILITY_TYPE_CD',
			table1.COMMITMENT_TYPE_CD AS COMMITMENT_TYPE_CD LABEL='COMMITMENT_TYPE_CD',
			table1.COUNTERPARTY_RK AS COUNTERPARTY_RK LABEL='COUNTERPARTY_RK' FORMAT=12.,
			table1.OWNED_BY_INTERNAL_ORG_RK AS OWNED_BY_INTERNAL_ORG_RK LABEL='OWNED_BY_INTERNAL_ORG_RK' FORMAT=12.,
			table1.EFFECTIVE_MATURITY_YEAR_NO AS EFFECTIVE_MATURITY_YEAR_NO LABEL='EFFECTIVE_MATURITY_YEAR_NO',
			table1.EXPOSURE_AT_DEFAULT_AMT AS EXPOSURE_AT_DEFAULT_AMT LABEL='EXPOSURE_AT_DEFAULT_AMT',
			table1.RESETS_TYPE_CD AS RESETS_TYPE_CD LABEL='RESETS_TYPE_CD',
			table1.INTERNAL_REPORTING_CATEGORY_CD AS INTERNAL_REPORTING_CATEGORY_CD LABEL='INTERNAL_REPORTING_CATEGORY_CD',
			table1.COUNTERPARTY_ID AS COUNTERPARTY_ID LABEL='COUNTERPARTY_ID',
			table1.COUNTERPARTY_TYPE_CD AS COUNTERPARTY_TYPE_CD LABEL='COUNTERPARTY_TYPE_CD',
			table1.ECONOMIC_SECTOR_CD AS ECONOMIC_SECTOR_CD LABEL='ECONOMIC_SECTOR_CD',
			table1.HIGH_RISK_CATEGORY_FLG AS HIGH_RISK_CATEGORY_FLG LABEL='HIGH_RISK_CATEGORY_FLG',
			table1.COUNTERPARTY_LEGAL_TYPE_CD AS COUNTERPARTY_LEGAL_TYPE_CD LABEL='COUNTERPARTY_LEGAL_TYPE_CD',
			table1.CORE_MKT_PARTICIPANT_FLG AS CORE_MKT_PARTICIPANT_FLG LABEL='CORE_MKT_PARTICIPANT_FLG',
			table1.COUNTERPARTY_RLN_TYPE_CD AS COUNTERPARTY_RLN_TYPE_CD LABEL='COUNTERPARTY_RLN_TYPE_CD',
			table1.CPTY_INTERNAL_RPT_CATEGORY_CD AS CPTY_INTERNAL_RPT_CATEGORY_CD LABEL='CPTY_INTERNAL_RPT_CATEGORY_CD',
			 ( table1.VALID_START_DTTM )  AS VALID_START_DTTM_2 LABEL='VALID_START_DTTM_2' FORMAT=NLDATM21.,
			 ( table1.VALID_END_DTTM )  AS VALID_END_DTTM_2 LABEL='VALID_END_DTTM_2' FORMAT=NLDATM21. 
		FROM
			dim.CUSTOMER_DIM table0 Inner join dim.CREDIT_FACILITY_DIM table1 on table0.CUSTOMER_RK = table1.CUSTOMER_RK ;
		quit;


		%dabt_err_chk(type=SQL);

		PROC SQL ;
		Create table WORK.CORP_ACCOUNT_X_CUSTOMER as
		SELECT 
			table1.CUSTOMER_SK AS CUSTOMER_SK LABEL='CUSTOMER_SK' FORMAT=12.,
			table1.CUSTOMER_RK AS CUSTOMER_RK LABEL='CUSTOMER_RK' FORMAT=12.,
			table1.CUSTOMER_ID AS CUSTOMER_ID LABEL='CUSTOMER_ID',
			table1.ORGANIZATION_TYPE_CD AS ORGANIZATION_TYPE_CD LABEL='ORGANIZATION_TYPE_CD',
			table1.CUSTOMER_CITY_NM AS CUSTOMER_CITY_NM LABEL='CUSTOMER_CITY_NM',
			table1.CUSTOMER_POSTAL_CD AS CUSTOMER_POSTAL_CD LABEL='CUSTOMER_POSTAL_CD',
			table1.CUSTOMER_STATE_REGION_CD AS CUSTOMER_STATE_REGION_CD LABEL='CUSTOMER_STATE_REGION_CD',
			table1.CUSTOMER_COUNTRY_CD AS CUSTOMER_COUNTRY_CD LABEL='CUSTOMER_COUNTRY_CD',
			table1.CUSTOMER_TYPE_CD AS CUSTOMER_TYPE_CD LABEL='CUSTOMER_TYPE_CD',
			table1.CUSTOMER_ACTIVE_CD AS CUSTOMER_ACTIVE_CD LABEL='CUSTOMER_ACTIVE_CD',
			table1.CUSTOMER_LIFECYCLE_CD AS CUSTOMER_LIFECYCLE_CD LABEL='CUSTOMER_LIFECYCLE_CD',
			table1.BANKRUPTCY_STATUS_CD AS BANKRUPTCY_STATUS_CD LABEL='BANKRUPTCY_STATUS_CD',
			table1.PENDING_LAWSUIT_FLG AS PENDING_LAWSUIT_FLG LABEL='PENDING_LAWSUIT_FLG',
			table1.LEGAL_JUDGEMENT_FLG AS LEGAL_JUDGEMENT_FLG LABEL='LEGAL_JUDGEMENT_FLG',
			table1.TAX_BRACKET_CD AS TAX_BRACKET_CD LABEL='TAX_BRACKET_CD',
			table1.TAX_ID AS TAX_ID LABEL='TAX_ID',
			table1.TAX_ID_TYPE_CD AS TAX_ID_TYPE_CD LABEL='TAX_ID_TYPE_CD',
			table1.FIRST_ACCOUNT_TYPE_CD AS FIRST_ACCOUNT_TYPE_CD LABEL='FIRST_ACCOUNT_TYPE_CD',
			table1.EVER_IN_COLLECTION_FLG AS EVER_IN_COLLECTION_FLG LABEL='EVER_IN_COLLECTION_FLG',
			table1.PREFERRED_CHANNEL_CD AS PREFERRED_CHANNEL_CD LABEL='PREFERRED_CHANNEL_CD',
			table1.OTHER_BANK_CLIENT_FLG AS OTHER_BANK_CLIENT_FLG LABEL='OTHER_BANK_CLIENT_FLG',
			table1.OTHER_CREDIT_CARDS_CNT AS OTHER_CREDIT_CARDS_CNT LABEL='OTHER_CREDIT_CARDS_CNT',
			table1.ANNUAL_INCOME_AMT AS ANNUAL_INCOME_AMT LABEL='ANNUAL_INCOME_AMT',
			table1.INTERNAL_CREDIT_RATING_CD AS INTERNAL_CREDIT_RATING_CD LABEL='INTERNAL_CREDIT_RATING_CD',
			table1.PRIMARY_INTERNAL_ORG_RK AS PRIMARY_INTERNAL_ORG_RK LABEL='PRIMARY_INTERNAL_ORG_RK' FORMAT=12.,
			table1.INDUSTRY_CD AS INDUSTRY_CD LABEL='INDUSTRY_CD',
			table1.NUM_EMPLOYEES_CNT AS NUM_EMPLOYEES_CNT LABEL='NUM_EMPLOYEES_CNT',
			table1.EXTERNAL_CREDIT_RATING1_CD AS EXTERNAL_CREDIT_RATING1_CD LABEL='EXTERNAL_CREDIT_RATING1_CD',
			table1.NUM_OFFICES_CNT AS NUM_OFFICES_CNT LABEL='NUM_OFFICES_CNT',
			table1.EXTERNAL_CREDIT_RATING2_CD AS EXTERNAL_CREDIT_RATING2_CD LABEL='EXTERNAL_CREDIT_RATING2_CD',
			table1.OWNERSHIP_CNT AS OWNERSHIP_CNT LABEL='OWNERSHIP_CNT',
			table1.CUSTOMER_CLASS_CD AS CUSTOMER_CLASS_CD LABEL='CUSTOMER_CLASS_CD',
			table1.OWNERSHIP_CD AS OWNERSHIP_CD LABEL='OWNERSHIP_CD',
			table1.BUSINESS_NATURE_CD AS BUSINESS_NATURE_CD LABEL='BUSINESS_NATURE_CD',
			 ( table1.VALID_START_DTTM )  AS VALID_START_DTTM LABEL='VALID_START_DTTM' FORMAT=NLDATM21.,
			 ( table1.VALID_END_DTTM )  AS VALID_END_DTTM LABEL='VALID_END_DTTM' FORMAT=NLDATM21.,
			 ( table1.CURRENT_COUNTRY_START_DT )  AS CURRENT_COUNTRY_START_DT LABEL='CURRENT_COUNTRY_START_DT' FORMAT=NLDATM21.,
			 ( table1.BANKRUPTCY_FILED_DT )  AS BANKRUPTCY_FILED_DT LABEL='BANKRUPTCY_FILED_DT' FORMAT=NLDATM21.,
			 ( table1.INCORPORATION_DT )  AS INCORPORATION_DT LABEL='INCORPORATION_DT' FORMAT=NLDATM21.,
			 ( table1.BUSINESS_ESTABLISHED_DT )  AS BUSINESS_ESTABLISHED_DT LABEL='BUSINESS_ESTABLISHED_DT' FORMAT=NLDATM21.,
			 ( table1.BUSINESS_COMMENCED_DT )  AS BUSINESS_COMMENCED_DT LABEL='BUSINESS_COMMENCED_DT' FORMAT=NLDATM21.,
			 ( table1.FIRST_ACCOUNT_OPEN_DT )  AS FIRST_ACCOUNT_OPEN_DT LABEL='FIRST_ACCOUNT_OPEN_DT' FORMAT=NLDATM21.,
			 ( table1.CURRENT_ADDRESS_START_DT )  AS CURRENT_ADDRESS_START_DT LABEL='CURRENT_ADDRESS_START_DT' FORMAT=NLDATM21.,
			table0.ACCOUNT_SK AS ACCOUNT_SK LABEL='ACCOUNT_SK',
			table0.ACCOUNT_RK AS ACCOUNT_RK LABEL='ACCOUNT_RK' FORMAT=12.,
			table0.OWNED_BY_INTERNAL_ORG_RK AS OWNED_BY_INTERNAL_ORG_RK LABEL='OWNED_BY_INTERNAL_ORG_RK' FORMAT=12.,
			table0.PRIMARY_PRODUCT_RK AS PRIMARY_PRODUCT_RK LABEL='PRIMARY_PRODUCT_RK' FORMAT=12.,
			table0.CREDIT_FACILITY_RK AS CREDIT_FACILITY_RK LABEL='CREDIT_FACILITY_RK' FORMAT=12.,
			table0.ACCOUNT_ID AS ACCOUNT_ID LABEL='ACCOUNT_ID',
			table0.ACCOUNT_TYPE_CD AS ACCOUNT_TYPE_CD LABEL='ACCOUNT_TYPE_CD',
			table0.ACCOUNT_TYPE_DESC AS ACCOUNT_TYPE_DESC LABEL='ACCOUNT_TYPE_DESC',
			table0.ACCOUNT_SUB_TYPE_CD AS ACCOUNT_SUB_TYPE_CD LABEL='ACCOUNT_SUB_TYPE_CD',
			table0.ACCOUNT_SUB_TYPE_DESC AS ACCOUNT_SUB_TYPE_DESC LABEL='ACCOUNT_SUB_TYPE_DESC',
			table0.PURPOSE_CD AS PURPOSE_CD LABEL='PURPOSE_CD',
			table0.ACCT_HOLDERS_CNT AS ACCT_HOLDERS_CNT LABEL='ACCT_HOLDERS_CNT',
			table0.SIGNATORIES_CNT AS SIGNATORIES_CNT LABEL='SIGNATORIES_CNT',
			table0.ADDITIONAL_CARD_CNT AS ADDITIONAL_CARD_CNT LABEL='ADDITIONAL_CARD_CNT',
			table0.SECURITY_CD AS SECURITY_CD LABEL='SECURITY_CD',
			table0.COLLATERAL_CD AS COLLATERAL_CD LABEL='COLLATERAL_CD',
			table0.MORTGAGE_INSURED_FLG AS MORTGAGE_INSURED_FLG LABEL='MORTGAGE_INSURED_FLG',
			table0.PAYMENT_INSURED_FLG AS PAYMENT_INSURED_FLG LABEL='PAYMENT_INSURED_FLG',
			table0.CURRENCY_CD AS CURRENCY_CD LABEL='CURRENCY_CD',
			table0.OPENING_CHANNEL_CD AS OPENING_CHANNEL_CD LABEL='OPENING_CHANNEL_CD',
			table0.BROKER_FLG AS BROKER_FLG LABEL='BROKER_FLG',
			table0.OPENING_CAMPAIGN_CD AS OPENING_CAMPAIGN_CD LABEL='OPENING_CAMPAIGN_CD',
			table0.DOCUMENTATION_TYPE_CD AS DOCUMENTATION_TYPE_CD LABEL='DOCUMENTATION_TYPE_CD',
			table0.CHECK_BOOK_FLG AS CHECK_BOOK_FLG LABEL='CHECK_BOOK_FLG',
			table0.MIN_ACCOUNT_OPENING_AMT AS MIN_ACCOUNT_OPENING_AMT LABEL='MIN_ACCOUNT_OPENING_AMT',
			table0.REQUIRED_MIN_BALANCE_AMT AS REQUIRED_MIN_BALANCE_AMT LABEL='REQUIRED_MIN_BALANCE_AMT',
			table0.ALLOW_OVERDRAFT_FLG AS ALLOW_OVERDRAFT_FLG LABEL='ALLOW_OVERDRAFT_FLG',
			table0.SAFE_DEPOSIT_FLG AS SAFE_DEPOSIT_FLG LABEL='SAFE_DEPOSIT_FLG',
			table0.MIN_REDRAW_AMT AS MIN_REDRAW_AMT LABEL='MIN_REDRAW_AMT',
			table0.MIN_PAYMENT_FLG AS MIN_PAYMENT_FLG LABEL='MIN_PAYMENT_FLG',
			table0.DISBURSEMENT_TYPE_CD AS DISBURSEMENT_TYPE_CD LABEL='DISBURSEMENT_TYPE_CD',
			table0.GRACE_PERIOD_DAYS_CNT AS GRACE_PERIOD_DAYS_CNT LABEL='GRACE_PERIOD_DAYS_CNT',
			table0.CASH_BACK_FLG AS CASH_BACK_FLG LABEL='CASH_BACK_FLG',
			table0.CASH_BACK_PCT AS CASH_BACK_PCT LABEL='CASH_BACK_PCT',
			table0.FINANCE_CHARGE_FLG AS FINANCE_CHARGE_FLG LABEL='FINANCE_CHARGE_FLG',
			table0.SPLIT_LOAN_FLG AS SPLIT_LOAN_FLG LABEL='SPLIT_LOAN_FLG',
			table0.ANNUAL_FEES_AMT AS ANNUAL_FEES_AMT LABEL='ANNUAL_FEES_AMT',
			table0.PORTABILITY_FLG AS PORTABILITY_FLG LABEL='PORTABILITY_FLG',
			table0.ACTUAL_ACCOUNT_OPENING_AMT AS ACTUAL_ACCOUNT_OPENING_AMT LABEL='ACTUAL_ACCOUNT_OPENING_AMT',
			table0.CURRENT_LIMIT_AMT AS CURRENT_LIMIT_AMT LABEL='CURRENT_LIMIT_AMT',
			table0.CASH_LIMIT_AMT AS CASH_LIMIT_AMT LABEL='CASH_LIMIT_AMT',
			table0.SECURITY_DEPOSIT_AMT AS SECURITY_DEPOSIT_AMT LABEL='SECURITY_DEPOSIT_AMT',
			table0.APPROVED_AMT AS APPROVED_AMT LABEL='APPROVED_AMT',
			table0.ACTUAL_ADVANCE_AMT AS ACTUAL_ADVANCE_AMT LABEL='ACTUAL_ADVANCE_AMT',
			table0.COLLECTIONS_STATUS_CD AS COLLECTIONS_STATUS_CD LABEL='COLLECTIONS_STATUS_CD',
			table0.DOWNPAYMENT_AMT AS DOWNPAYMENT_AMT LABEL='DOWNPAYMENT_AMT',
			table0.IMPROVEMENTS_ALLOCATION_AMT AS IMPROVEMENTS_ALLOCATION_AMT LABEL='IMPROVEMENTS_ALLOCATION_AMT',
			table0.INTEREST_PAYOUT_FLG AS INTEREST_PAYOUT_FLG LABEL='INTEREST_PAYOUT_FLG',
			table0.MULTI_RATE_FLG AS MULTI_RATE_FLG LABEL='MULTI_RATE_FLG',
			table0.CLOSE_REASON_CD AS CLOSE_REASON_CD LABEL='CLOSE_REASON_CD',
			table0.ACCOUNT_STATUS_CD AS ACCOUNT_STATUS_CD LABEL='ACCOUNT_STATUS_CD',
			table0.ACCOUNT_LIFECYCLE_STG_CD AS ACCOUNT_LIFECYCLE_STG_CD LABEL='ACCOUNT_LIFECYCLE_STG_CD',
			table0.OFFSET_ACCOUNT_FLG AS OFFSET_ACCOUNT_FLG LABEL='OFFSET_ACCOUNT_FLG',
			table0.DO_NOT_CONTACT_FLG AS DO_NOT_CONTACT_FLG LABEL='DO_NOT_CONTACT_FLG',
			table0.HONEYMOON_PERIOD_FLG AS HONEYMOON_PERIOD_FLG LABEL='HONEYMOON_PERIOD_FLG',
			table0.LINKED_ACCOUNT_FLG AS LINKED_ACCOUNT_FLG LABEL='LINKED_ACCOUNT_FLG',
			table0.LINKED_DEP_ACCT_FLG AS LINKED_DEP_ACCT_FLG LABEL='LINKED_DEP_ACCT_FLG',
			table0.STATEMENT_FREQUENCY_CD AS STATEMENT_FREQUENCY_CD LABEL='STATEMENT_FREQUENCY_CD',
			table0.REPAYMENT_HOLIDAY_FLG AS REPAYMENT_HOLIDAY_FLG LABEL='REPAYMENT_HOLIDAY_FLG',
			table0.PAYMENT_FREQUENCY_CD AS PAYMENT_FREQUENCY_CD LABEL='PAYMENT_FREQUENCY_CD',
			table0.REGULAR_PERIODIC_PAYMENT_AMT AS REGULAR_PERIODIC_PAYMENT_AMT LABEL='REGULAR_PERIODIC_PAYMENT_AMT',
			table0.PAYMENT_DAY_OF_MONTH AS PAYMENT_DAY_OF_MONTH LABEL='PAYMENT_DAY_OF_MONTH',
			table0.PAYMENT_MODE_CD AS PAYMENT_MODE_CD LABEL='PAYMENT_MODE_CD',
			table0.SPECIAL_RATE_TYPE_CD AS SPECIAL_RATE_TYPE_CD LABEL='SPECIAL_RATE_TYPE_CD',
			table0.SPECIAL_INTEREST_RT AS SPECIAL_INTEREST_RT LABEL='SPECIAL_INTEREST_RT',
			 ( table0.VALID_START_DTTM )  AS VALID_START_DTTM_2 LABEL='VALID_START_DTTM_2' FORMAT=NLDATM21.,
			 ( table0.VALID_END_DTTM )  AS VALID_END_DTTM_2 LABEL='VALID_END_DTTM_2' FORMAT=NLDATM21.,
			table0.HOME_STATUS_CD AS HOME_STATUS_CD LABEL='HOME_STATUS_CD',
			table0.STEP_UP_FACILITY_USED_FLG AS STEP_UP_FACILITY_USED_FLG LABEL='STEP_UP_FACILITY_USED_FLG',
			table0.CALLABLE_FACILITY_USED_FLG AS CALLABLE_FACILITY_USED_FLG LABEL='CALLABLE_FACILITY_USED_FLG',
			table0.ACCOUNT_RENEWAL_TYPE_CD AS ACCOUNT_RENEWAL_TYPE_CD LABEL='ACCOUNT_RENEWAL_TYPE_CD',
			table0.COLLATERAL_AMT AS COLLATERAL_AMT LABEL='COLLATERAL_AMT',
			table0.GUARANTORS_CNT AS GUARANTORS_CNT LABEL='GUARANTORS_CNT',
			table0.NOMINEES_CNT AS NOMINEES_CNT LABEL='NOMINEES_CNT',
			table0.REDRAW_FLG AS REDRAW_FLG LABEL='REDRAW_FLG',
			table0.CLOSING_COST_AMT AS CLOSING_COST_AMT LABEL='CLOSING_COST_AMT',
			table0.SENIORITY_CD AS SENIORITY_CD LABEL='SENIORITY_CD',
			table0.LIEN_INDICATOR_FLG AS LIEN_INDICATOR_FLG LABEL='LIEN_INDICATOR_FLG',
			table0.OVERDRAFT_LIMIT_AMT AS OVERDRAFT_LIMIT_AMT LABEL='OVERDRAFT_LIMIT_AMT',
			table0.SECURITY_DEPOSIT_REFUND_AMT AS SECURITY_DEPOSIT_REFUND_AMT LABEL='SECURITY_DEPOSIT_REFUND_AMT',
			table0.STANDING_ORDERS_CNT AS STANDING_ORDERS_CNT LABEL='STANDING_ORDERS_CNT',
			table0.CHECKING_MAIN_FLG AS CHECKING_MAIN_FLG LABEL='CHECKING_MAIN_FLG',
			table0.INITIAL_LIMIT_AMT AS INITIAL_LIMIT_AMT LABEL='INITIAL_LIMIT_AMT',
			table0.DIRECT_DEBITS_CNT AS DIRECT_DEBITS_CNT LABEL='DIRECT_DEBITS_CNT',
			table0.GUARANTEE_AMT AS GUARANTEE_AMT LABEL='GUARANTEE_AMT',
			table0.PROVISIONAL_CREDIT_LIMIT_AMT AS PROVISIONAL_CREDIT_LIMIT_AMT LABEL='PROVISIONAL_CREDIT_LIMIT_AMT',
			table0.MORTGAGE_OPEN_TO_BUY_AMT AS MORTGAGE_OPEN_TO_BUY_AMT LABEL='MORTGAGE_OPEN_TO_BUY_AMT',
			table0.CHARGE_OFF_AMT AS CHARGE_OFF_AMT LABEL='CHARGE_OFF_AMT',
			table0.CHARGE_OFF_FLG AS CHARGE_OFF_FLG LABEL='CHARGE_OFF_FLG',
			table0.ACCOUNT_RENEWAL_CNT AS ACCOUNT_RENEWAL_CNT LABEL='ACCOUNT_RENEWAL_CNT',
			table0.INDIVIDUAL_ORGANIZATION_CD AS INDIVIDUAL_ORGANIZATION_CD LABEL='INDIVIDUAL_ORGANIZATION_CD',
			 ( table0.REGISTER_ONLINE_DT )  AS REGISTER_ONLINE_DT LABEL='REGISTER_ONLINE_DT' FORMAT=NLDATM21.,
			 ( table0.OPEN_DT )  AS OPEN_DT LABEL='OPEN_DT' FORMAT=NLDATM21.,
			 ( table0.CURRENT_LIMIT_DT )  AS CURRENT_LIMIT_DT LABEL='CURRENT_LIMIT_DT' FORMAT=NLDATM21.,
			 ( table0.CARD_EXPIRATION_DT )  AS CARD_EXPIRATION_DT LABEL='CARD_EXPIRATION_DT' FORMAT=NLDATM21.,
			 ( table0.CARD_ISSUE_DT )  AS CARD_ISSUE_DT LABEL='CARD_ISSUE_DT' FORMAT=NLDATM21.,
			 ( table0.CARD_REISSUE_DT )  AS CARD_REISSUE_DT LABEL='CARD_REISSUE_DT' FORMAT=NLDATM21.,
			 ( table0.HONEYMOON_END_DT )  AS HONEYMOON_END_DT LABEL='HONEYMOON_END_DT' FORMAT=NLDATM21.,
			 ( table0.REPAYMENT_HOLIDAY_END_DT )  AS REPAYMENT_HOLIDAY_END_DT LABEL='REPAYMENT_HOLIDAY_END_DT' FORMAT=NLDATM21.,
			 ( table0.REPAYMENT_HOLIDAY_START_DT )  AS REPAYMENT_HOLIDAY_START_DT LABEL='REPAYMENT_HOLIDAY_START_DT' FORMAT=NLDATM21.,
			 ( table0.SPECIAL_RATE_END_DT )  AS SPECIAL_RATE_END_DT LABEL='SPECIAL_RATE_END_DT' FORMAT=NLDATM21.,
			 ( table0.SPECIAL_RATE_START_DT )  AS SPECIAL_RATE_START_DT LABEL='SPECIAL_RATE_START_DT' FORMAT=NLDATM21.,
			 ( table0.OVERDRAFT_LIMIT_DT )  AS OVERDRAFT_LIMIT_DT LABEL='OVERDRAFT_LIMIT_DT' FORMAT=NLDATM21.,
			 ( table0.PROV_CREDIT_LIMIT_CLOSE_DT )  AS PROV_CREDIT_LIMIT_CLOSE_DT LABEL='PROV_CREDIT_LIMIT_CLOSE_DT' FORMAT=NLDATM21.,
			 ( table0.PROV_CREDIT_LIMIT_OPEN_DT )  AS PROV_CREDIT_LIMIT_OPEN_DT LABEL='PROV_CREDIT_LIMIT_OPEN_DT' FORMAT=NLDATM21.,
			 ( table0.CHARGE_OFF_DT )  AS CHARGE_OFF_DT LABEL='CHARGE_OFF_DT' FORMAT=NLDATM21.,
			 ( table0.CLOSE_DT )  AS CLOSE_DT LABEL='CLOSE_DT' FORMAT=NLDATM21.,
			 ( CASE  WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&CHK_ACCOUNT_SUB_TYPE) THEN  &ACC_HIER_CHK 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&CCD_ACCOUNT_TYPE) THEN &ACC_HIER_CCD  
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&SAV_ACCOUNT_SUB_TYPE,&CHK_ACCOUNT_SUB_TYPE) AND table0.ALLOW_OVERDRAFT_FLG IN (&CHECK_FLAG_TRUE)  THEN &ACC_HIER_OD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN (&RDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_RD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN  (&SAV_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_SAV 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&MTG_ACCOUNT_TYPE, &LON_ACCOUNT_TYPE) AND table0.COLLATERAL_CD IS NOT NULL THEN &ACC_HIER_SLN     
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD  IN (&TDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_TD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&LON_ACCOUNT_TYPE) AND (table0.COLLATERAL_CD IS NULL) THEN &ACC_HIER_ULN  ELSE ' '  END  )  AS ACCOUNT_HIERARCHY_CD LABEL='ACCOUNT_HIERARCHY_CD' 
		FROM
			dim.CUSTOMER_DIM table1 Inner join dim.ACCOUNT_DIM table0 on table1.CUSTOMER_RK = table0.PRIMARY_CUSTOMER_RK ;
		quit;

		%dabt_err_chk(type=SQL);

		PROC SQL ;
		Create table work.ACCOUNT_SNAPSHOT_BASE as
		SELECT 
			table0.ACCOUNT_RK AS ACCOUNT_RK LABEL='ACCOUNT_RK',
			table5.CREDIT_FACILITY_RK AS CREDIT_FACILITY_RK LABEL='CREDIT_FACILITY_RK',
			table0.PRIMARY_CUSTOMER_RK AS CUSTOMER_RK LABEL='CUSTOMER_RK',
			table0.APPLICATION_RK AS APPLICATION_RK LABEL='APPLICATION_RK',
			table2.DAYS_PAYMENT_PAST_DUE_CNT AS DAYS_PAYMENT_PAST_DUE_CNT LABEL='DAYS_PAYMENT_PAST_DUE_CNT',
			table2.DELINQUENCY_CNT AS DELINQUENCY_CNT LABEL='DELINQUENCY_CNT',
			table2.ACTIVE_ACCOUNT_CNT AS ACTIVE_ACCOUNT_CNT LABEL='ACTIVE_ACCOUNT_CNT',
			table2.INACTIVE_ACCOUNT_CNT AS INACTIVE_ACCOUNT_CNT LABEL='INACTIVE_ACCOUNT_CNT',
			table2.CLOSED_ACCOUNT_CNT AS CLOSED_ACCOUNT_CNT LABEL='CLOSED_ACCOUNT_CNT',
			table2.OPEN_ACCOUNT_CNT AS OPEN_ACCOUNT_CNT LABEL='OPEN_ACCOUNT_CNT',
			table2.DEFAULT_CNT AS DEFAULT_CNT LABEL='DEFAULT_CNT',
			table2.NEW_ACCOUNT_CNT AS NEW_ACCOUNT_CNT LABEL='NEW_ACCOUNT_CNT',
			table2.CROSS_SELL_ACCOUNT_CNT AS CROSS_SELL_ACCOUNT_CNT LABEL='CROSS_SELL_ACCOUNT_CNT',
			table2.CROSS_SELL_CAMPAIGN_IND AS CROSS_SELL_CAMPAIGN_IND LABEL='CROSS_SELL_CAMPAIGN_IND',
			table2.DIFFER_PAYMENT_CNT AS DIFFER_PAYMENT_CNT LABEL='DIFFER_PAYMENT_CNT',
			table2.UP_SELL_ACCOUNT_CNT AS UP_SELL_ACCOUNT_CNT LABEL='UP_SELL_ACCOUNT_CNT',
			table2.TOTAL_SUSPENSIONS_CNT AS TOTAL_SUSPENSIONS_CNT LABEL='TOTAL_SUSPENSIONS_CNT',
			table2.CCD_TOT_POINTS_EARNED AS CCD_TOT_POINTS_EARNED LABEL='CCD_TOT_POINTS_EARNED',
			table2.CCD_TOT_POINTS_REDEEMED AS CCD_TOT_POINTS_REDEEMED LABEL='CCD_TOT_POINTS_REDEEMED',
			table2.CCD_POINTS_BALANCE AS CCD_POINTS_BALANCE LABEL='CCD_POINTS_BALANCE',
			table2.CLAIM_CNT AS CLAIM_CNT LABEL='CLAIM_CNT',
			table2.BALANCE_AMT AS BALANCE_AMT LABEL='BALANCE_AMT' FORMAT=NLNUM18.5,
			table2.INTEREST_EXPECTED_AMT AS INTEREST_EXPECTED_AMT LABEL='INTEREST_EXPECTED_AMT' FORMAT=NLNUM18.5,
			table2.PAST_DUE_AMT AS PAST_DUE_AMT LABEL='PAST_DUE_AMT' FORMAT=NLNUM18.5,
			table2.AVERAGE_DAILY_BALANCE_AMT AS AVERAGE_DAILY_BALANCE_AMT LABEL='AVERAGE_DAILY_BALANCE_AMT' FORMAT=NLNUM18.5,
			table2.MAX_ACCOUNT_VALUE_AMT AS MAX_ACCOUNT_VALUE_AMT LABEL='MAX_ACCOUNT_VALUE_AMT' FORMAT=NLNUM18.5,
			table2.MIN_ACCOUNT_VALUE_AMT AS MIN_ACCOUNT_VALUE_AMT LABEL='MIN_ACCOUNT_VALUE_AMT' FORMAT=NLNUM18.5,
			table2.BILLED_AMT AS BILLED_AMT LABEL='BILLED_AMT' FORMAT=NLNUM18.5,
			table2.CURRENT_LIMIT_AMT AS CURRENT_LIMIT_AMT LABEL='CURRENT_LIMIT_AMT' FORMAT=NLNUM18.5,
			table2.CURRENT_BILL_AMT AS CURRENT_BILL_AMT LABEL='CURRENT_BILL_AMT' FORMAT=NLNUM18.5,
			table2.MIN_BILLING_AMT AS MIN_BILLING_AMT LABEL='MIN_BILLING_AMT' FORMAT=NLNUM18.5,
			table2.FEES_AMT AS FEES_AMT LABEL='FEES_AMT' FORMAT=NLNUM18.5,
			table2.CURTAILMENT_AMT AS CURTAILMENT_AMT LABEL='CURTAILMENT_AMT' FORMAT=NLNUM18.5,
			table2.ESCROW_AMT AS ESCROW_AMT LABEL='ESCROW_AMT' FORMAT=NLNUM18.5,
			table2.CLEARED_BALANCE_AMT AS CLEARED_BALANCE_AMT LABEL='CLEARED_BALANCE_AMT' FORMAT=NLNUM18.5,
			table2.PRINCIPAL_BALANCE_AMT AS PRINCIPAL_BALANCE_AMT LABEL='PRINCIPAL_BALANCE_AMT' FORMAT=NLNUM18.5,
			table2.OVERDRAFT_CURRENT_AMT AS OVERDRAFT_CURRENT_AMT LABEL='OVERDRAFT_CURRENT_AMT' FORMAT=NLNUM18.5,
			table2.TOTAL_BALANCE_AMT AS TOTAL_BALANCE_AMT LABEL='TOTAL_BALANCE_AMT' FORMAT=NLNUM18.5,
			table2.CLAIM_AMT AS CLAIM_AMT LABEL='CLAIM_AMT' FORMAT=NLNUM18.5,
			table0.ACCOUNT_LIFECYCLE_STG_CD AS ACCOUNT_LIFECYCLE_STG_CD LABEL='ACCOUNT_LIFECYCLE_STG_CD' FORMAT=$3.,
			table0.ACCOUNT_STATUS_CD AS ACCOUNT_STATUS_CD LABEL='ACCOUNT_STATUS_CD' FORMAT=$3.,
			table0.ACCOUNT_SUB_TYPE_CD AS ACCOUNT_SUB_TYPE_CD LABEL='ACCOUNT_SUB_TYPE_CD' FORMAT=$3.,
			table0.ACCOUNT_TYPE_CD AS ACCOUNT_TYPE_CD LABEL='ACCOUNT_TYPE_CD' FORMAT=$3.,
			table0.COLLECTIONS_STATUS_CD AS COLLECTIONS_STATUS_CD LABEL='COLLECTIONS_STATUS_CD' FORMAT=$3.,
			table0.COLLATERAL_AMT AS COLLATERAL_AMT LABEL='COLLATERAL_AMT' FORMAT=NLNUM18.5,
			table0.DIRECT_DEBITS_CNT AS DIRECT_DEBITS_CNT LABEL='DIRECT_DEBITS_CNT',
			table0.REGULAR_PERIODIC_PAYMENT_AMT AS REGULAR_PERIODIC_PAYMENT_AMT LABEL='REGULAR_PERIODIC_PAYMENT_AMT' FORMAT=NLNUM18.5,
			table0.REQUIRED_MIN_BALANCE_AMT AS REQUIRED_MIN_BALANCE_AMT LABEL='REQUIRED_MIN_BALANCE_AMT' FORMAT=NLNUM18.5,
			table0.STANDING_ORDERS_CNT AS STANDING_ORDERS_CNT LABEL='STANDING_ORDERS_CNT',
			table0.ACTUAL_ADVANCE_AMT AS ACTUAL_ADVANCE_AMT LABEL='ACTUAL_ADVANCE_AMT' FORMAT=NLNUM18.5,
			table0.ANNUAL_FEES_AMT AS ANNUAL_FEES_AMT LABEL='ANNUAL_FEES_AMT' FORMAT=NLNUM18.5,
			table0.APPROVED_AMT AS APPROVED_AMT LABEL='APPROVED_AMT' FORMAT=NLNUM18.5,
			table0.CASH_LIMIT_AMT AS CASH_LIMIT_AMT LABEL='CASH_LIMIT_AMT' FORMAT=NLNUM18.5,
			table0.CHARGE_OFF_AMT AS CHARGE_OFF_AMT LABEL='CHARGE_OFF_AMT' FORMAT=NLNUM18.5,
			table0.CLOSING_COST_AMT AS CLOSING_COST_AMT LABEL='CLOSING_COST_AMT' FORMAT=NLNUM18.5,
			table0.DOWNPAYMENT_AMT AS DOWNPAYMENT_AMT LABEL='DOWNPAYMENT_AMT' FORMAT=NLNUM18.5,
			table0.GUARANTEE_AMT AS GUARANTEE_AMT LABEL='GUARANTEE_AMT' FORMAT=NLNUM18.5,
			table0.OVERDRAFT_LIMIT_AMT AS OVERDRAFT_LIMIT_AMT LABEL='OVERDRAFT_LIMIT_AMT' FORMAT=NLNUM18.5,
			table0.ACCOUNT_RENEWAL_CNT AS ACCOUNT_RENEWAL_CNT LABEL='ACCOUNT_RENEWAL_CNT',
			table0.CURRENT_LIMIT_AMT AS CURRENT_TOTAL_LIMIT_AMT LABEL='CURRENT_TOTAL_LIMIT_AMT' FORMAT=NLNUM18.5,
			table5.CREDIT_FACILITY_TYPE_CD AS CREDIT_FACILITY_TYPE_CD LABEL='CREDIT_FACILITY_TYPE_CD' FORMAT=$3.,
			table8.FINANCIAL_PRODUCT_TYPE_CD AS FINANCIAL_PRODUCT_TYPE_CD LABEL='FINANCIAL_PRODUCT_TYPE_CD' FORMAT=$3.,
			table8.PRODUCT_SUB_TYPE_CD AS PRODUCT_SUB_TYPE_CD LABEL='PRODUCT_SUB_TYPE_CD' FORMAT=$3.,
			table10.TENURE_RANGE_NM AS TENURE_RANGE_NM LABEL='TENURE_RANGE_NM' FORMAT=$40.,
			table7.DELINQUENCY_RANGE_NM AS DELINQUENCY_RANGE_NM LABEL='DELINQUENCY_RANGE_NM' FORMAT=$40.,
			 ( table9.PERIOD_LAST_DTTM )  AS PERIOD_LAST_DTTM LABEL='PERIOD_LAST_DTTM' FORMAT=NLDATM21.,
			 ( (CASE WHEN table2.DAYS_PAYMENT_PAST_DUE_CNT > 30 THEN 1 ELSE 0 END) )  AS DPD_GT_30 LABEL='DPD_GT_30',
			 ( (CASE WHEN table2.DAYS_PAYMENT_PAST_DUE_CNT > 60 THEN 1 ELSE 0 END) )  AS DPD_GT_60 LABEL='DPD_GT_60',
			 ( (CASE WHEN table2.DAYS_PAYMENT_PAST_DUE_CNT > 90 THEN 1 ELSE 0 END) )  AS DPD_GT_90 LABEL='DPD_GT_90',
			 ( (CASE WHEN table2.DAYS_PAYMENT_PAST_DUE_CNT > 120 THEN 1 ELSE 0 END) )  AS DPD_GT_120 LABEL='DPD_GT_120',
			 ( (CASE WHEN table2.DAYS_PAYMENT_PAST_DUE_CNT > 180 THEN 1 ELSE 0 END) )  AS DPD_GT_180 LABEL='DPD_GT_180',
			 ( (CASE WHEN table0.CHARGE_OFF_FLG  in (&CHECK_FLAG_TRUE) THEN 1 ELSE 0 END) )  AS CHARGE_OFF_CNT LABEL='CHARGE_OFF_CNT',
			 ( (CASE WHEN table0.COLLECTIONS_STATUS_CD in  (&COL_STS_AGY) THEN 1 ELSE 0 END) )  AS COLLECTIONS_CNT LABEL='COLLECTIONS_CNT',   	
			 /* i18nOK:END */
			 ( CASE  WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&CHK_ACCOUNT_SUB_TYPE) THEN  &ACC_HIER_CHK 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&CCD_ACCOUNT_TYPE) THEN &ACC_HIER_CCD  
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&SAV_ACCOUNT_SUB_TYPE,&CHK_ACCOUNT_SUB_TYPE) AND table0.ALLOW_OVERDRAFT_FLG IN (&CHECK_FLAG_TRUE)  THEN &ACC_HIER_OD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN (&RDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_RD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN  (&SAV_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_SAV 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&MTG_ACCOUNT_TYPE, &LON_ACCOUNT_TYPE) AND table0.COLLATERAL_CD IS NOT NULL THEN &ACC_HIER_SLN       
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD  IN (&TDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_TD  
			 /* i18nOK:BEGIN */
			 WHEN table0.ACCOUNT_TYPE_CD IN (&LON_ACCOUNT_TYPE) AND (table0.COLLATERAL_CD IS NULL) THEN &ACC_HIER_ULN  ELSE ' '  END  )  AS ACCOUNT_HIERARCHY_CD LABEL='ACCOUNT_HIERARCHY_CD',    	
			 ( (CASE WHEN  table2.BALANCE_AMT < table0.REQUIRED_MIN_BALANCE_AMT THEN 1 ELSE 0 END) )  AS BALANCE_BELOW_LIMIT_CNT LABEL='BALANCE_BELOW_LIMIT_CNT',
			 ( (table2.BALANCE_AMT/table2.CURRENT_LIMIT_AMT)*100 )  AS LIMIT_USE_PCT LABEL='LIMIT_USE_PCT',
			 ( (CASE WHEN table2.BALANCE_AMT  >  0 THEN 1 ELSE 0 END) )  AS POSITIVE_BALANCE_CNT LABEL='POSITIVE_BALANCE_CNT',
			 ( (CASE WHEN table2.BALANCE_AMT =  0 THEN 1 ELSE 0 END) )  AS ZERO_BALANCE_CNT LABEL='ZERO_BALANCE_CNT',
			 ( (CASE WHEN table2.OVERDRAFT_CURRENT_AMT > 0 THEN 1 ELSE 0 END) )  AS OD_OVERDRAWN_CNT LABEL='OD_OVERDRAWN_CNT',
			 ( (table2.OVERDRAFT_CURRENT_AMT - table0.OVERDRAFT_LIMIT_AMT) )  AS OD_OVER_LIMIT_AMT LABEL='OD_OVER_LIMIT_AMT',
			 ( (CASE WHEN table2.OVERDRAFT_CURRENT_AMT >= table0.OVERDRAFT_LIMIT_AMT THEN 1 ELSE 0 END) )  AS OD_OVER_LIMIT_CNT LABEL='OD_OVER_LIMIT_CNT',
			 ( (table0.CURRENT_LIMIT_AMT - table2.BALANCE_AMT) )  AS OPEN_TO_BUY_AMT LABEL='OPEN_TO_BUY_AMT',
			 ( (((table2.BALANCE_AMT - table0.CURRENT_LIMIT_AMT))/table0.CURRENT_LIMIT_AMT)*100 )  AS OTL_PCT LABEL='OTL_PCT',
			 ( (table2.INTEREST_EXPECTED_AMT / table2.BALANCE_AMT) *100 )  AS OUTSTANDING_INT_TO_BALANCE_PCT LABEL='OUTSTANDING_INT_TO_BALANCE_PCT',
			 ( (table2.BALANCE_AMT - table0.CURRENT_LIMIT_AMT) )  AS OVER_LIMIT_AMT LABEL='OVER_LIMIT_AMT',
			 ( (CASE WHEN  table2.BALANCE_AMT >= table0.CASH_LIMIT_AMT THEN 1 ELSE 0 END) )  AS OVER_LIMIT_CNT LABEL='OVER_LIMIT_CNT',
			 ( CASE WHEN table0.CALLABLE_FACILITY_USED_FLG IN (&CHECK_FLAG_TRUE) THEN 1 ELSE 0 END )  AS CALLABLE_FACILITY_USED_CNT LABEL='CALLABLE_FACILITY_USED_CNT',
			 ( CASE WHEN table0.CLOSE_REASON_CD  IN (&CLOSE_REASON_CD_PPY) THEN 1 ELSE 0 END )  AS PREPAY_CLOSE_CNT LABEL='PREPAY_CLOSE_CNT',
			 ( (CASE WHEN table2.BALANCE_AMT  <  0 THEN 1 ELSE 0 END) )  AS NEGATIVE_BALANCE_CNT LABEL='NEGATIVE_BALANCE_CNT',
			 ( ((table2.BALANCE_AMT - table2.CURRENT_LIMIT_AMT) / table0.OVERDRAFT_LIMIT_AMT)*100 )  AS OTL_OD_LMT_PCT LABEL='OTL_OD_LMT_PCT' 				
			 /* i18nOK:END */
		FROM
			dim.ACCOUNT_DIM table0 Inner join fact.ACCOUNT_SNAPSHOT table2 on table0.ACCOUNT_SK = table2.ACCOUNT_SK 
			Inner join dim.CREDIT_FACILITY_DIM table5 on table5.CREDIT_FACILITY_SK = table2.CREDIT_FACILITY_SK 
			Inner join dim.DELINQUENCY_RANGE_DIM table7 on 
			table7.DELINQUENCY_RANGE_SK = table2.DELINQUENCY_RANGE_SK 
			Inner join dim.FINANCIAL_PRODUCT_DIM table8 on table8.PRODUCT_SK = table2.PRODUCT_SK 
			Inner join dim.TIME_DIM table9 on table9.TIME_SK = table2.TIME_SK 
			Inner join dim.TENURE_RANGE_DIM table10 on table10.TENURE_RANGE_SK = table2.CUSTOMER_TENURE_RANGE_SK ;
		quit;


		%dabt_err_chk(type=SQL);

		
			

		

		PROC SQL ;
		Create table work.IND_CUSTOMER_X_ACCOUNT as
		SELECT 
		/* i18nOK:BEGIN */
			table1.CUSTOMER_SK AS CUSTOMER_SK LABEL='CUSTOMER_SK' FORMAT=BEST12.,   	
			table1.CUSTOMER_RK AS CUSTOMER_RK LABEL='CUSTOMER_RK' FORMAT=12.,
			table1.ANNUAL_INCOME_AMT AS ANNUAL_INCOME_AMT LABEL='ANNUAL_INCOME_AMT' FORMAT=NLNUM18.5,
			table1.ASSET_OTHER_AMT AS ASSET_OTHER_AMT LABEL='ASSET_OTHER_AMT' FORMAT=NLNUM18.5,
			table1.BANKRUPTCY_STATUS_CD AS BANKRUPTCY_STATUS_CD LABEL='BANKRUPTCY_STATUS_CD' FORMAT=$3.,
			table1.BILL_PAY_SERVICE_FLG AS BILL_PAY_SERVICE_FLG LABEL='BILL_PAY_SERVICE_FLG' FORMAT=$1.,
			table1.BUSINESS_NATURE_CD AS BUSINESS_NATURE_CD LABEL='BUSINESS_NATURE_CD' FORMAT=$3.,
			table1.CHILDREN_CNT AS CHILDREN_CNT LABEL='CHILDREN_CNT' FORMAT=BEST12.,
			table1.CUSTOMER_COUNTRY_CD AS CUSTOMER_COUNTRY_CD LABEL='CUSTOMER_COUNTRY_CD' FORMAT=$3.,
			table1.CUSTOMER_ACTIVE_CD AS CUSTOMER_ACTIVE_CD LABEL='CUSTOMER_ACTIVE_CD' FORMAT=$3.,
			table1.CUSTOMER_CITY_NM AS CUSTOMER_CITY_NM LABEL='CUSTOMER_CITY_NM' FORMAT=$100.,
			table1.CUSTOMER_CLASS_CD AS CUSTOMER_CLASS_CD LABEL='CUSTOMER_CLASS_CD' FORMAT=$3.,
			table1.CUSTOMER_ID AS CUSTOMER_ID LABEL='CUSTOMER_ID' FORMAT=$32.,
			table1.CUSTOMER_LIFECYCLE_CD AS CUSTOMER_LIFECYCLE_CD LABEL='CUSTOMER_LIFECYCLE_CD' FORMAT=$3.,
			table1.CUSTOMER_POSTAL_CD AS CUSTOMER_POSTAL_CD LABEL='CUSTOMER_POSTAL_CD' FORMAT=$20.,
			table1.CUSTOMER_STATE_REGION_CD AS CUSTOMER_STATE_REGION_CD LABEL='CUSTOMER_STATE_REGION_CD' FORMAT=$4.,
			table1.CUSTOMER_TYPE_CD AS CUSTOMER_TYPE_CD LABEL='CUSTOMER_TYPE_CD' FORMAT=$3.,
			table1.EDUCATION_LEVEL_CD AS EDUCATION_LEVEL_CD LABEL='EDUCATION_LEVEL_CD' FORMAT=$10.,
			table1.EMPLOYEE_FLG AS EMPLOYEE_FLG LABEL='EMPLOYEE_FLG' FORMAT=$1.,
			table1.EMPLOYERS_CNT AS EMPLOYERS_CNT LABEL='EMPLOYERS_CNT' FORMAT=BEST12.,
			table1.EMPLOYMENT_POSITION_STATUS_CD AS EMPLOYMENT_POSITION_STATUS_CD LABEL='EMPLOYMENT_POSITION_STATUS_CD' FORMAT=$3.,
			table1.EMPLOYMENT_STATUS_CD AS EMPLOYMENT_STATUS_CD LABEL='EMPLOYMENT_STATUS_CD' FORMAT=$3.,
			table1.EMPLOYMENT_YEARS_CNT AS EMPLOYMENT_YEARS_CNT LABEL='EMPLOYMENT_YEARS_CNT' FORMAT=NLNUM6.2,
			table1.EVER_IN_COLLECTION_FLG AS EVER_IN_COLLECTION_FLG LABEL='EVER_IN_COLLECTION_FLG' FORMAT=$1.,
			table1.EXTERNAL_CREDIT_RATING1_CD AS EXTERNAL_CREDIT_RATING1_CD LABEL='EXTERNAL_CREDIT_RATING1_CD' FORMAT=$4.,
			table1.EXTERNAL_CREDIT_RATING2_CD AS EXTERNAL_CREDIT_RATING2_CD LABEL='EXTERNAL_CREDIT_RATING2_CD' FORMAT=$4.,
			table1.FIRST_ACCOUNT_TYPE_CD AS FIRST_ACCOUNT_TYPE_CD LABEL='FIRST_ACCOUNT_TYPE_CD' FORMAT=$3.,
			table1.GENDER_CD AS GENDER_CD LABEL='GENDER_CD' FORMAT=$3.,
			table1.HHOLD_RK AS HHOLD_RK LABEL='HHOLD_RK' FORMAT=BEST12.,
			table1.INCOME_CATEGORY_CD AS INCOME_CATEGORY_CD LABEL='INCOME_CATEGORY_CD' FORMAT=$3.,
			table1.INDUSTRY_CD AS INDUSTRY_CD LABEL='INDUSTRY_CD' FORMAT=$10.,
			table1.INTERNAL_CREDIT_RATING_CD AS INTERNAL_CREDIT_RATING_CD LABEL='INTERNAL_CREDIT_RATING_CD' FORMAT=$20.,
			table1.LEGAL_JUDGEMENT_FLG AS LEGAL_JUDGEMENT_FLG LABEL='LEGAL_JUDGEMENT_FLG' FORMAT=$1.,
			table1.LIABILITY_OTHER_AMT AS LIABILITY_OTHER_AMT LABEL='LIABILITY_OTHER_AMT' FORMAT=NLNUM18.5,
			table1.LIABILITY_REAL_ESTATE_AMT AS LIABILITY_REAL_ESTATE_AMT LABEL='LIABILITY_REAL_ESTATE_AMT' FORMAT=NLNUM18.5,
			table1.LIQUID_ASSETS_AMT AS LIQUID_ASSETS_AMT LABEL='LIQUID_ASSETS_AMT' FORMAT=NLNUM18.5,
			table1.LIQUID_NET_WORTH_AMT AS LIQUID_NET_WORTH_AMT LABEL='LIQUID_NET_WORTH_AMT' FORMAT=NLNUM18.5,
			table1.MARITAL_STATUS_CD AS MARITAL_STATUS_CD LABEL='MARITAL_STATUS_CD' FORMAT=$3.,
			table1.MONTHLY_ALIMONY_AMT AS MONTHLY_ALIMONY_AMT LABEL='MONTHLY_ALIMONY_AMT' FORMAT=BEST12.,
			table1.MONTHLY_BUSINESS_INCOME_AMT AS MONTHLY_BUSINESS_INCOME_AMT LABEL='MONTHLY_BUSINESS_INCOME_AMT' FORMAT=BEST12.,
			table1.MONTHLY_CHILD_ALLOW_AMT AS MONTHLY_CHILD_ALLOW_AMT LABEL='MONTHLY_CHILD_ALLOW_AMT' FORMAT=BEST12.,
			table1.MONTHLY_CHILD_SUPPORT_AMT AS MONTHLY_CHILD_SUPPORT_AMT LABEL='MONTHLY_CHILD_SUPPORT_AMT' FORMAT=BEST12.,
			table1.MONTHLY_INVESTMENT_AMT AS MONTHLY_INVESTMENT_AMT LABEL='MONTHLY_INVESTMENT_AMT' FORMAT=NLNUM18.5,
			table1.MONTHLY_OTHER_CHARGE_AMT AS MONTHLY_OTHER_CHARGE_AMT LABEL='MONTHLY_OTHER_CHARGE_AMT' FORMAT=BEST12.,
			table1.MONTHLY_OTHER_INCOME_AMT AS MONTHLY_OTHER_INCOME_AMT LABEL='MONTHLY_OTHER_INCOME_AMT' FORMAT=BEST12.,
			table1.MONTHLY_PRI_INCOME_SOURCE_CD AS MONTHLY_PRI_INCOME_SOURCE_CD LABEL='MONTHLY_PRI_INCOME_SOURCE_CD' FORMAT=$10.,
			table1.MONTHLY_RENTAL_AMT AS MONTHLY_RENTAL_AMT LABEL='MONTHLY_RENTAL_AMT' FORMAT=BEST12.,
			table1.MONTHLY_RENTAL_INCOME_AMT AS MONTHLY_RENTAL_INCOME_AMT LABEL='MONTHLY_RENTAL_INCOME_AMT' FORMAT=BEST12.,
			table1.MONTHLY_REPAYMENT_AMT AS MONTHLY_REPAYMENT_AMT LABEL='MONTHLY_REPAYMENT_AMT' FORMAT=BEST12.,
			table1.MONTHLY_REPAYMENT_OTHERS_AMT AS MONTHLY_REPAYMENT_OTHERS_AMT LABEL='MONTHLY_REPAYMENT_OTHERS_AMT' FORMAT=BEST12.,
			table1.MONTHLY_REPLACEMENT_INCOME_AMT AS MONTHLY_REPLACEMENT_INCOME_AMT LABEL='MONTHLY_REPLACEMENT_INCOME_AMT' FORMAT=BEST12.,
			table1.MONTHLY_SALARY_INCOME_AMT AS MONTHLY_SALARY_INCOME_AMT LABEL='MONTHLY_SALARY_INCOME_AMT' FORMAT=BEST12.,
			table1.NET_WORTH_AMT AS NET_WORTH_AMT LABEL='NET_WORTH_AMT' FORMAT=NLNUM18.5,
			table1.ORGANIZATION_TYPE_CD AS ORGANIZATION_TYPE_CD LABEL='ORGANIZATION_TYPE_CD' FORMAT=$3.,
			table1.OTHER_BANK_CLIENT_FLG AS OTHER_BANK_CLIENT_FLG LABEL='OTHER_BANK_CLIENT_FLG' FORMAT=$1.,
			table1.OTHER_CREDIT_CARDS_CNT AS OTHER_CREDIT_CARDS_CNT LABEL='OTHER_CREDIT_CARDS_CNT' FORMAT=BEST12.,
			table1.OWN_AUTOMOBILE_FLG AS OWN_AUTOMOBILE_FLG LABEL='OWN_AUTOMOBILE_FLG' FORMAT=$1.,
			table1.OWN_MOTORCYCLE_FLG AS OWN_MOTORCYCLE_FLG LABEL='OWN_MOTORCYCLE_FLG' FORMAT=$1.,
			table1.OWN_RESIDENCE_PROPERTY_FLG AS OWN_RESIDENCE_PROPERTY_FLG LABEL='OWN_RESIDENCE_PROPERTY_FLG' FORMAT=$1.,
			table1.PASSPORT_ISSUE_COUNTRY_CD AS PASSPORT_ISSUE_COUNTRY_CD LABEL='PASSPORT_ISSUE_COUNTRY_CD' FORMAT=$3.,
			table1.PENDING_LAWSUIT_FLG AS PENDING_LAWSUIT_FLG LABEL='PENDING_LAWSUIT_FLG' FORMAT=$1.,
			table1.PREFERRED_CHANNEL_CD AS PREFERRED_CHANNEL_CD LABEL='PREFERRED_CHANNEL_CD' FORMAT=$3.,
			table1.PRIMARY_CITIZENSHIP_COUNTRY_CD AS PRIMARY_CITIZENSHIP_COUNTRY_CD LABEL='PRIMARY_CITIZENSHIP_COUNTRY_CD' FORMAT=$3.,
			table1.PRIMARY_INTERNAL_ORG_RK AS PRIMARY_INTERNAL_ORG_RK LABEL='PRIMARY_INTERNAL_ORG_RK' FORMAT=BEST12.,
			 ( table1.PROCESSED_DTTM )  AS PROCESSED_DTTM LABEL='PROCESSED_DTTM' FORMAT=NLDATM21.,
			table1.REAL_ESTATE_AMT AS REAL_ESTATE_AMT LABEL='REAL_ESTATE_AMT' FORMAT=NLNUM18.5,
			table1.RESIDENCE_STATUS_CD AS RESIDENCE_STATUS_CD LABEL='RESIDENCE_STATUS_CD' FORMAT=$3.,
			table1.SECNDRY_CITIZENSHIP_COUNTRY_CD AS SECNDRY_CITIZENSHIP_COUNTRY_CD LABEL='SECNDRY_CITIZENSHIP_COUNTRY_CD' FORMAT=$3.,
			table1.SELF_EMPLOYMENT_FLG AS SELF_EMPLOYMENT_FLG LABEL='SELF_EMPLOYMENT_FLG' FORMAT=$1.,
			table1.STD_OCCUPATION_CD AS STD_OCCUPATION_CD LABEL='STD_OCCUPATION_CD' FORMAT=$3.,
			table1.TAX_BRACKET_CD AS TAX_BRACKET_CD LABEL='TAX_BRACKET_CD' FORMAT=$3.,
			table1.TAX_ID AS TAX_ID LABEL='TAX_ID' FORMAT=$32.,
			table1.TAX_ID_TYPE_CD AS TAX_ID_TYPE_CD LABEL='TAX_ID_TYPE_CD' FORMAT=$3.,
			table1.TOTAL_ASSET_AMT AS TOTAL_ASSET_AMT LABEL='TOTAL_ASSET_AMT' FORMAT=NLNUM18.5,
			table1.TOTAL_DEPENDENTS_CNT AS TOTAL_DEPENDENTS_CNT LABEL='TOTAL_DEPENDENTS_CNT' FORMAT=BEST12.,
			table1.TOTAL_EMPLOYMENT_YEARS_CNT AS TOTAL_EMPLOYMENT_YEARS_CNT LABEL='TOTAL_EMPLOYMENT_YEARS_CNT' FORMAT=NLNUM6.2,
			table1.TOTAL_LIABILITY_AMT AS TOTAL_LIABILITY_AMT LABEL='TOTAL_LIABILITY_AMT' FORMAT=NLNUM18.5,
			 ( table1.VALID_END_DTTM )  AS VALID_END_DTTM LABEL='VALID_END_DTTM' FORMAT=NLDATM21.,
			 ( table1.VALID_START_DTTM )  AS VALID_START_DTTM LABEL='VALID_START_DTTM' FORMAT=NLDATM21.,
			 ( table1.BIRTH_DT )  AS BIRTH_DT LABEL='BIRTH_DT' FORMAT=NLDATM21.,
			 ( table1.BANKRUPTCY_FILED_DT )  AS BANKRUPTCY_FILED_DT LABEL='BANKRUPTCY_FILED_DT' FORMAT=NLDATM21.,
			 ( table1.CURRENT_ADDRESS_START_DT )  AS CURRENT_ADDRESS_START_DT LABEL='CURRENT_ADDRESS_START_DT' FORMAT=NLDATM21.,
			 ( table1.CURRENT_COUNTRY_START_DT )  AS CURRENT_COUNTRY_START_DT LABEL='CURRENT_COUNTRY_START_DT' FORMAT=NLDATM21.,
			 ( table1.CURRENT_EMP_START_DT )  AS CURRENT_EMP_START_DT LABEL='CURRENT_EMP_START_DT' FORMAT=NLDATM21.,
			 ( table1.ELDEST_CHILD_BIRTH_DT )  AS ELDEST_CHILD_BIRTH_DT LABEL='ELDEST_CHILD_BIRTH_DT' FORMAT=NLDATM21.,
			 ( table1.EMPLOYMENT_START_DT )  AS EMPLOYMENT_START_DT LABEL='EMPLOYMENT_START_DT' FORMAT=NLDATM21.,
			 ( table1.OCCUPATION_START_DT )  AS OCCUPATION_START_DT LABEL='OCCUPATION_START_DT' FORMAT=NLDATM21.,
			 ( table1.FIRST_ACCOUNT_OPEN_DT )  AS FIRST_ACCOUNT_OPEN_DT LABEL='FIRST_ACCOUNT_OPEN_DT' FORMAT=NLDATM21.,
			 ( table1.RESIDENCE_STATUS_DT )  AS RESIDENCE_STATUS_DT LABEL='RESIDENCE_STATUS_DT' FORMAT=NLDATM21.,
			 ( table1.TEMPORARY_EMPLOYMENT_END_DT )  AS TEMPORARY_EMPLOYMENT_END_DT LABEL='TEMPORARY_EMPLOYMENT_END_DT' FORMAT=NLDATM21.,
			 ( table1.YOUNGEST_CHILD_BIRTH_DT )  AS YOUNGEST_CHILD_BIRTH_DT LABEL='YOUNGEST_CHILD_BIRTH_DT' FORMAT=NLDATM21.,
			table0.ACCOUNT_ID AS ACCOUNT_ID LABEL='ACCOUNT_ID' FORMAT=$32.,
			table0.ACCOUNT_LIFECYCLE_STG_CD AS ACCOUNT_LIFECYCLE_STG_CD LABEL='ACCOUNT_LIFECYCLE_STG_CD' FORMAT=$3.,
			table0.ACCOUNT_RENEWAL_CNT AS ACCOUNT_RENEWAL_CNT LABEL='ACCOUNT_RENEWAL_CNT',
			table0.ACCOUNT_RENEWAL_TYPE_CD AS ACCOUNT_RENEWAL_TYPE_CD LABEL='ACCOUNT_RENEWAL_TYPE_CD' FORMAT=$3.,
			table0.ACCOUNT_RK AS ACCOUNT_RK LABEL='ACCOUNT_RK' FORMAT=12.,
			table0.ACCOUNT_SK AS ACCOUNT_SK LABEL='ACCOUNT_SK' FORMAT=12.,
			table0.ACCOUNT_STATUS_CD AS ACCOUNT_STATUS_CD LABEL='ACCOUNT_STATUS_CD' FORMAT=$3.,
			table0.ACCOUNT_SUB_TYPE_CD AS ACCOUNT_SUB_TYPE_CD LABEL='ACCOUNT_SUB_TYPE_CD' FORMAT=$3.,
			table0.ACCOUNT_SUB_TYPE_DESC AS ACCOUNT_SUB_TYPE_DESC LABEL='ACCOUNT_SUB_TYPE_DESC' FORMAT=$100.,
			table0.ACCOUNT_TYPE_CD AS ACCOUNT_TYPE_CD LABEL='ACCOUNT_TYPE_CD' FORMAT=$3.,
			table0.ACCOUNT_TYPE_DESC AS ACCOUNT_TYPE_DESC LABEL='ACCOUNT_TYPE_DESC' FORMAT=$100.,
			table0.ACCT_HOLDERS_CNT AS ACCT_HOLDERS_CNT LABEL='ACCT_HOLDERS_CNT',
			table0.ACTUAL_ACCOUNT_OPENING_AMT AS ACTUAL_ACCOUNT_OPENING_AMT LABEL='ACTUAL_ACCOUNT_OPENING_AMT' FORMAT=NLNUM18.5,
			table0.ACTUAL_ADVANCE_AMT AS ACTUAL_ADVANCE_AMT LABEL='ACTUAL_ADVANCE_AMT' FORMAT=NLNUM18.5,
			table0.ADDITIONAL_CARD_CNT AS ADDITIONAL_CARD_CNT LABEL='ADDITIONAL_CARD_CNT',
			table0.ALLOW_OVERDRAFT_FLG AS ALLOW_OVERDRAFT_FLG LABEL='ALLOW_OVERDRAFT_FLG' FORMAT=$1.,
			table0.ANNUAL_FEES_AMT AS ANNUAL_FEES_AMT LABEL='ANNUAL_FEES_AMT' FORMAT=NLNUM18.5,
			table0.APPLICATION_RK AS APPLICATION_RK LABEL='APPLICATION_RK' FORMAT=12.,
			table0.APPROVED_AMT AS APPROVED_AMT LABEL='APPROVED_AMT' FORMAT=NLNUM18.5,
			table0.BROKER_FLG AS BROKER_FLG LABEL='BROKER_FLG' FORMAT=$1.,
			table0.CALLABLE_FACILITY_USED_FLG AS CALLABLE_FACILITY_USED_FLG LABEL='CALLABLE_FACILITY_USED_FLG' FORMAT=$1.,
			table0.CASH_BACK_FLG AS CASH_BACK_FLG LABEL='CASH_BACK_FLG' FORMAT=$1.,
			table0.CASH_BACK_PCT AS CASH_BACK_PCT LABEL='CASH_BACK_PCT' FORMAT=NLNUM9.4,
			table0.CASH_LIMIT_AMT AS CASH_LIMIT_AMT LABEL='CASH_LIMIT_AMT' FORMAT=NLNUM18.5,
			table0.CHARGE_OFF_AMT AS CHARGE_OFF_AMT LABEL='CHARGE_OFF_AMT' FORMAT=NLNUM18.5,
			table0.CHARGE_OFF_FLG AS CHARGE_OFF_FLG LABEL='CHARGE_OFF_FLG',
			table0.CHECK_BOOK_FLG AS CHECK_BOOK_FLG LABEL='CHECK_BOOK_FLG' FORMAT=$1.,
			table0.CHECKING_MAIN_FLG AS CHECKING_MAIN_FLG LABEL='CHECKING_MAIN_FLG' FORMAT=$1.,
			table0.CLOSE_REASON_CD AS CLOSE_REASON_CD LABEL='CLOSE_REASON_CD' FORMAT=$3.,
			table0.CLOSING_COST_AMT AS CLOSING_COST_AMT LABEL='CLOSING_COST_AMT' FORMAT=NLNUM18.5,
			table0.COLLATERAL_AMT AS COLLATERAL_AMT LABEL='COLLATERAL_AMT' FORMAT=NLNUM18.5,
			table0.COLLATERAL_CD AS COLLATERAL_CD LABEL='COLLATERAL_CD' FORMAT=$3.,
			table0.COLLECTIONS_STATUS_CD AS COLLECTIONS_STATUS_CD LABEL='COLLECTIONS_STATUS_CD' FORMAT=$3.,
			table0.CREATED_BY AS CREATED_BY LABEL='CREATED_BY' FORMAT=$20.,
			 ( table0.CREATED_DTTM )  AS CREATED_DTTM LABEL='CREATED_DTTM' FORMAT=NLDATM21.,
			table0.CREDIT_FACILITY_RK AS CREDIT_FACILITY_RK LABEL='CREDIT_FACILITY_RK' FORMAT=12.,
			table0.CURRENCY_CD AS CURRENCY_CD LABEL='CURRENCY_CD' FORMAT=$3.,
			table0.CURRENT_LIMIT_AMT AS CURRENT_LIMIT_AMT LABEL='CURRENT_LIMIT_AMT' FORMAT=NLNUM18.5,
			table0.DIRECT_DEBITS_CNT AS DIRECT_DEBITS_CNT LABEL='DIRECT_DEBITS_CNT',
			table0.DISBURSEMENT_TYPE_CD AS DISBURSEMENT_TYPE_CD LABEL='DISBURSEMENT_TYPE_CD' FORMAT=$3.,
			table0.DO_NOT_CONTACT_FLG AS DO_NOT_CONTACT_FLG LABEL='DO_NOT_CONTACT_FLG' FORMAT=$1.,
			table0.DOCUMENTATION_TYPE_CD AS DOCUMENTATION_TYPE_CD LABEL='DOCUMENTATION_TYPE_CD' FORMAT=$3.,
			table0.DOWNPAYMENT_AMT AS DOWNPAYMENT_AMT LABEL='DOWNPAYMENT_AMT' FORMAT=NLNUM18.5,
			table0.FINANCE_CHARGE_FLG AS FINANCE_CHARGE_FLG LABEL='FINANCE_CHARGE_FLG' FORMAT=$1.,
			table0.GRACE_PERIOD_DAYS_CNT AS GRACE_PERIOD_DAYS_CNT LABEL='GRACE_PERIOD_DAYS_CNT',
			table0.GUARANTEE_AMT AS GUARANTEE_AMT LABEL='GUARANTEE_AMT' FORMAT=NLNUM18.5,
			table0.GUARANTORS_CNT AS GUARANTORS_CNT LABEL='GUARANTORS_CNT',
			table0.HOME_STATUS_CD AS HOME_STATUS_CD LABEL='HOME_STATUS_CD' FORMAT=$3.,
			table0.HONEYMOON_PERIOD_FLG AS HONEYMOON_PERIOD_FLG LABEL='HONEYMOON_PERIOD_FLG' FORMAT=$1.,
			table0.IMPROVEMENTS_ALLOCATION_AMT AS IMPROVEMENTS_ALLOCATION_AMT LABEL='IMPROVEMENTS_ALLOCATION_AMT' FORMAT=NLNUM18.5,
			table0.INDIVIDUAL_ORGANIZATION_CD AS INDIVIDUAL_ORGANIZATION_CD LABEL='INDIVIDUAL_ORGANIZATION_CD',
			table0.INITIAL_LIMIT_AMT AS INITIAL_LIMIT_AMT LABEL='INITIAL_LIMIT_AMT' FORMAT=NLNUM18.5,
			table0.INTEREST_PAYOUT_FLG AS INTEREST_PAYOUT_FLG LABEL='INTEREST_PAYOUT_FLG' FORMAT=$1.,
			table0.LIEN_INDICATOR_FLG AS LIEN_INDICATOR_FLG LABEL='LIEN_INDICATOR_FLG' FORMAT=$1.,
			table0.LINKED_ACCOUNT_FLG AS LINKED_ACCOUNT_FLG LABEL='LINKED_ACCOUNT_FLG' FORMAT=$1.,
			table0.LINKED_DEP_ACCT_FLG AS LINKED_DEP_ACCT_FLG LABEL='LINKED_DEP_ACCT_FLG' FORMAT=$1.,
			table0.MIN_ACCOUNT_OPENING_AMT AS MIN_ACCOUNT_OPENING_AMT LABEL='MIN_ACCOUNT_OPENING_AMT' FORMAT=NLNUM18.5,
			table0.MIN_PAYMENT_FLG AS MIN_PAYMENT_FLG LABEL='MIN_PAYMENT_FLG' FORMAT=$1.,
			table0.MIN_REDRAW_AMT AS MIN_REDRAW_AMT LABEL='MIN_REDRAW_AMT' FORMAT=NLNUM18.5,
			table0.MORTGAGE_INSURED_FLG AS MORTGAGE_INSURED_FLG LABEL='MORTGAGE_INSURED_FLG' FORMAT=$1.,
			table0.MORTGAGE_OPEN_TO_BUY_AMT AS MORTGAGE_OPEN_TO_BUY_AMT LABEL='MORTGAGE_OPEN_TO_BUY_AMT' FORMAT=NLNUM18.5,
			table0.MULTI_RATE_FLG AS MULTI_RATE_FLG LABEL='MULTI_RATE_FLG' FORMAT=$1.,
			table0.NOMINEES_CNT AS NOMINEES_CNT LABEL='NOMINEES_CNT',
			table0.OFFSET_ACCOUNT_FLG AS OFFSET_ACCOUNT_FLG LABEL='OFFSET_ACCOUNT_FLG' FORMAT=$1.,
			table0.OPENING_CAMPAIGN_CD AS OPENING_CAMPAIGN_CD LABEL='OPENING_CAMPAIGN_CD',
			table0.OPENING_CHANNEL_CD AS OPENING_CHANNEL_CD LABEL='OPENING_CHANNEL_CD' FORMAT=$3.,
			table0.OVERDRAFT_LIMIT_AMT AS OVERDRAFT_LIMIT_AMT LABEL='OVERDRAFT_LIMIT_AMT' FORMAT=NLNUM18.5,
			table0.OWNED_BY_INTERNAL_ORG_RK AS OWNED_BY_INTERNAL_ORG_RK LABEL='OWNED_BY_INTERNAL_ORG_RK' FORMAT=12.,
			table0.PAYMENT_DAY_OF_MONTH AS PAYMENT_DAY_OF_MONTH LABEL='PAYMENT_DAY_OF_MONTH',
			table0.PAYMENT_FREQUENCY_CD AS PAYMENT_FREQUENCY_CD LABEL='PAYMENT_FREQUENCY_CD' FORMAT=$3.,
			table0.PAYMENT_INSURED_FLG AS PAYMENT_INSURED_FLG LABEL='PAYMENT_INSURED_FLG' FORMAT=$1.,
			table0.PAYMENT_MODE_CD AS PAYMENT_MODE_CD LABEL='PAYMENT_MODE_CD' FORMAT=$3.,
			table0.PORTABILITY_FLG AS PORTABILITY_FLG LABEL='PORTABILITY_FLG' FORMAT=$1.,
			table0.PRIMARY_CUSTOMER_RK AS PRIMARY_CUSTOMER_RK LABEL='PRIMARY_CUSTOMER_RK',
			table0.PRIMARY_PRODUCT_RK AS PRIMARY_PRODUCT_RK LABEL='PRIMARY_PRODUCT_RK' FORMAT=12.,
			 ( table0.PROCESSED_DTTM )  AS PROCESSED_DTTM_2 LABEL='PROCESSED_DTTM' FORMAT=NLDATM21.,
			table0.PROVISIONAL_CREDIT_LIMIT_AMT AS PROVISIONAL_CREDIT_LIMIT_AMT LABEL='PROVISIONAL_CREDIT_LIMIT_AMT' FORMAT=NLNUM18.5,
			table0.PURPOSE_CD AS PURPOSE_CD LABEL='PURPOSE_CD' FORMAT=$3.,
			table0.REDRAW_FLG AS REDRAW_FLG LABEL='REDRAW_FLG' FORMAT=$1.,
			table0.REGULAR_PERIODIC_PAYMENT_AMT AS REGULAR_PERIODIC_PAYMENT_AMT LABEL='REGULAR_PERIODIC_PAYMENT_AMT' FORMAT=NLNUM18.5,
			table0.REPAYMENT_HOLIDAY_FLG AS REPAYMENT_HOLIDAY_FLG LABEL='REPAYMENT_HOLIDAY_FLG' FORMAT=$1.,
			table0.REQUIRED_MIN_BALANCE_AMT AS REQUIRED_MIN_BALANCE_AMT LABEL='REQUIRED_MIN_BALANCE_AMT' FORMAT=NLNUM18.5,
			table0.SAFE_DEPOSIT_FLG AS SAFE_DEPOSIT_FLG LABEL='SAFE_DEPOSIT_FLG' FORMAT=$1.,
			table0.SECURITY_CD AS SECURITY_CD LABEL='SECURITY_CD' FORMAT=$3.,
			table0.SECURITY_DEPOSIT_AMT AS SECURITY_DEPOSIT_AMT LABEL='SECURITY_DEPOSIT_AMT' FORMAT=NLNUM18.5,
			table0.SECURITY_DEPOSIT_REFUND_AMT AS SECURITY_DEPOSIT_REFUND_AMT LABEL='SECURITY_DEPOSIT_REFUND_AMT' FORMAT=NLNUM18.5,
			table0.SENIORITY_CD AS SENIORITY_CD LABEL='SENIORITY_CD' FORMAT=$3.,
			table0.SIGNATORIES_CNT AS SIGNATORIES_CNT LABEL='SIGNATORIES_CNT',
			table0.SOURCE_SYSTEM_CD AS SOURCE_SYSTEM_CD LABEL='SOURCE_SYSTEM_CD' FORMAT=$3.,
			table0.SPECIAL_INTEREST_RT AS SPECIAL_INTEREST_RT LABEL='SPECIAL_INTEREST_RT' FORMAT=NLNUM9.4,
			table0.SPECIAL_RATE_TYPE_CD AS SPECIAL_RATE_TYPE_CD LABEL='SPECIAL_RATE_TYPE_CD' FORMAT=$3.,
			table0.SPLIT_LOAN_FLG AS SPLIT_LOAN_FLG LABEL='SPLIT_LOAN_FLG' FORMAT=$1.,
			table0.STANDING_ORDERS_CNT AS STANDING_ORDERS_CNT LABEL='STANDING_ORDERS_CNT',
			table0.STATEMENT_FREQUENCY_CD AS STATEMENT_FREQUENCY_CD LABEL='STATEMENT_FREQUENCY_CD' FORMAT=$3.,
			table0.STEP_UP_FACILITY_USED_FLG AS STEP_UP_FACILITY_USED_FLG LABEL='STEP_UP_FACILITY_USED_FLG' FORMAT=$1.,
			 ( table0.VALID_END_DTTM )  AS VALID_END_DTTM_2 LABEL='VALID_END_DTTM' FORMAT=NLDATM21.,
			 ( table0.VALID_START_DTTM )  AS VALID_START_DTTM_2 LABEL='VALID_START_DTTM' FORMAT=NLDATM21.,
			 ( table0.CARD_EXPIRATION_DT )  AS CARD_EXPIRATION_DT LABEL='CARD_EXPIRATION_DT' FORMAT=NLDATM21.,
			 ( table0.CARD_ISSUE_DT )  AS CARD_ISSUE_DT LABEL='CARD_ISSUE_DT' FORMAT=NLDATM21.,
			 ( table0.CARD_REISSUE_DT )  AS CARD_REISSUE_DT LABEL='CARD_REISSUE_DT' FORMAT=NLDATM21.,
			 ( table0.CHARGE_OFF_DT )  AS CHARGE_OFF_DT LABEL='CHARGE_OFF_DT' FORMAT=NLDATM21.,
			 ( table0.CLOSE_DT )  AS CLOSE_DT LABEL='CLOSE_DT' FORMAT=NLDATM21.,
			 ( table0.CURRENT_LIMIT_DT )  AS CURRENT_LIMIT_DT LABEL='CURRENT_LIMIT_DT' FORMAT=NLDATM21.,
			 ( table0.HONEYMOON_START_DT )  AS HONEYMOON_START_DT LABEL='HONEYMOON_START_DT' FORMAT=NLDATM21.,
			 ( table0.HONEYMOON_END_DT )  AS HONEYMOON_END_DT LABEL='HONEYMOON_END_DT' FORMAT=NLDATM21.,
			 ( table0.OVERDRAFT_LIMIT_DT )  AS OVERDRAFT_LIMIT_DT LABEL='OVERDRAFT_LIMIT_DT' FORMAT=NLDATM21.,
			 ( table0.OPEN_DT )  AS OPEN_DT LABEL='OPEN_DT' FORMAT=NLDATM21.,
			 ( table0.PROV_CREDIT_LIMIT_OPEN_DT )  AS PROV_CREDIT_LIMIT_OPEN_DT LABEL='PROV_CREDIT_LIMIT_OPEN_DT' FORMAT=NLDATM21.,
			 ( table0.PROV_CREDIT_LIMIT_CLOSE_DT )  AS PROV_CREDIT_LIMIT_CLOSE_DT LABEL='PROV_CREDIT_LIMIT_CLOSE_DT' FORMAT=NLDATM21.,
			 ( table0.REGISTER_ONLINE_DT )  AS REGISTER_ONLINE_DT LABEL='REGISTER_ONLINE_DT' FORMAT=NLDATM21.,
			 ( table0.REPAYMENT_HOLIDAY_END_DT )  AS REPAYMENT_HOLIDAY_END_DT LABEL='REPAYMENT_HOLIDAY_END_DT' FORMAT=NLDATM21.,
			 ( table0.REPAYMENT_HOLIDAY_START_DT )  AS REPAYMENT_HOLIDAY_START_DT LABEL='REPAYMENT_HOLIDAY_START_DT' FORMAT=NLDATM21.,
			 ( table0.SPECIAL_RATE_END_DT )  AS SPECIAL_RATE_END_DT LABEL='SPECIAL_RATE_END_DT' FORMAT=NLDATM21.,
			 ( table0.SPECIAL_RATE_START_DT )  AS SPECIAL_RATE_START_DT LABEL='SPECIAL_RATE_START_DT' FORMAT=NLDATM21.,
			 ( COALESCE(table1.MONTHLY_SALARY_INCOME_AMT,0) + COALESCE(table1.MONTHLY_BUSINESS_INCOME_AMT,0) )  AS MONTHLY_INCOME_AMT LABEL='MONTHLY_INCOME_AMT',
			 ( COALESCE(table1.MONTHLY_SALARY_INCOME_AMT,0) + COALESCE(table1.MONTHLY_BUSINESS_INCOME_AMT,0) + COALESCE(table1.MONTHLY_RENTAL_INCOME_AMT,0) +
			 COALESCE(table1.MONTHLY_REPLACEMENT_INCOME_AMT,0) + COALESCE(table1.MONTHLY_OTHER_INCOME_AMT,0) + COALESCE(table1.MONTHLY_CHILD_ALLOW_AMT,0) - 
			 COALESCE(table1.MONTHLY_RENTAL_AMT,0) - COALESCE(table1.MONTHLY_ALIMONY_AMT,0) - COALESCE(table1.MONTHLY_CHILD_SUPPORT_AMT,0) -
			 COALESCE(table1.MONTHLY_REPAYMENT_AMT,0) - COALESCE(table1.MONTHLY_REPAYMENT_OTHERS_AMT,0) -COALESCE(table1.MONTHLY_OTHER_CHARGE_AMT,0) )  AS NET_MONTHLY_INCOME_AMT LABEL='NET_MONTHLY_INCOME_AMT',
			 ( CASE  WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&CHK_ACCOUNT_SUB_TYPE) THEN  &ACC_HIER_CHK 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&CCD_ACCOUNT_TYPE) THEN &ACC_HIER_CCD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&SAV_ACCOUNT_SUB_TYPE,&CHK_ACCOUNT_SUB_TYPE) AND table0.ALLOW_OVERDRAFT_FLG IN (&CHECK_FLAG_TRUE)  THEN &ACC_HIER_OD
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN (&RDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_RD
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN  (&SAV_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_SAV
			 WHEN table0.ACCOUNT_TYPE_CD IN (&MTG_ACCOUNT_TYPE, &LON_ACCOUNT_TYPE) AND table0.COLLATERAL_CD IS NOT NULL THEN &ACC_HIER_SLN  
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD  IN (&TDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_TD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&LON_ACCOUNT_TYPE) AND (table0.COLLATERAL_CD IS NULL) THEN &ACC_HIER_ULN  ELSE ' '  END )  AS ACCOUNT_HIERARCHY_CD LABEL='ACCOUNT_HIERARCHY_CD' 
		FROM
			dim.CUSTOMER_DIM table1 Inner join dim.ACCOUNT_DIM table0 on table1.CUSTOMER_RK = table0.PRIMARY_CUSTOMER_RK ;
		quit;
		%dabt_err_chk(type=SQL);


		

		PROC SQL ;
		Create table work.ALL_APPLICATION_DIM as
		SELECT 
			table0.APPLICATION_RK AS APPLICATION_RK LABEL='APPLICATION_RK',
			table0.CUSTOMER_RK AS CUSTOMER_RK LABEL='CUSTOMER_RK',
			table0.APPLICATION_ID AS APPLICATION_ID LABEL='APPLICATION_ID',
			table0.APPLICATION_RK AS APPLICATION_RK_2 LABEL='APPLICATION_RK_2' FORMAT=F12.0,
			 ( table0.VALID_START_DTTM )  AS VALID_START_DTTM LABEL='VALID_START_DTTM' FORMAT=NLDATM21.,
			 ( table0.VALID_END_DTTM )  AS VALID_END_DTTM LABEL='VALID_END_DTTM' FORMAT=NLDATM21.,
			table0.APPLICATION_SK AS APPLICATION_SK LABEL='APPLICATION_SK',
			table0.CUSTOMER_TYPE_CD AS CUSTOMER_TYPE_CD LABEL='CUSTOMER_TYPE_CD',
			table0.PURPOSE_CD AS PURPOSE_CD LABEL='PURPOSE_CD',
			table0.APPLICANTS_CNT AS APPLICANTS_CNT LABEL='APPLICANTS_CNT',
			table0.GUARANTORS_CNT AS GUARANTORS_CNT LABEL='GUARANTORS_CNT',
			table0.NOMINEES_CNT AS NOMINEES_CNT LABEL='NOMINEES_CNT',
			table0.SIGNATORIES_CNT AS SIGNATORIES_CNT LABEL='SIGNATORIES_CNT',
			table0.LINKED_ACCOUNT_FLG AS LINKED_ACCOUNT_FLG LABEL='LINKED_ACCOUNT_FLG',
			table0.LINKED_DEPOSIT_ACCOUNT_FLG AS LINKED_DEPOSIT_ACCOUNT_FLG LABEL='LINKED_DEPOSIT_ACCOUNT_FLG',
			table0.PRIOR_MORTGAGE_CNT AS PRIOR_MORTGAGE_CNT LABEL='PRIOR_MORTGAGE_CNT',
			table0.LOAN_TERM_MTHS_CNT AS LOAN_TERM_MTHS_CNT LABEL='LOAN_TERM_MTHS_CNT',
			table0.APPLIED_AMT AS APPLIED_AMT LABEL='APPLIED_AMT',
			table0.LOAN_SECURED_FLG AS LOAN_SECURED_FLG LABEL='LOAN_SECURED_FLG',
			table0.CREDIT_CARD_CONSOLIDATION_AMT AS CREDIT_CARD_CONSOLIDATION_AMT LABEL='CREDIT_CARD_CONSOLIDATION_AMT',
			table0.MORTGAGE_CONSOLIDATION_AMT AS MORTGAGE_CONSOLIDATION_AMT LABEL='MORTGAGE_CONSOLIDATION_AMT',
			table0.LOAN_CONSOLIDATION_AMT AS LOAN_CONSOLIDATION_AMT LABEL='LOAN_CONSOLIDATION_AMT',
			table0.CREDIT_CARD_CONSOLIDATION_CNT AS CREDIT_CARD_CONSOLIDATION_CNT LABEL='CREDIT_CARD_CONSOLIDATION_CNT',
			table0.MORTGAGE_CONSOLIDATION_CNT AS MORTGAGE_CONSOLIDATION_CNT LABEL='MORTGAGE_CONSOLIDATION_CNT',
			table0.LOAN_CONSOLIDATION_CNT AS LOAN_CONSOLIDATION_CNT LABEL='LOAN_CONSOLIDATION_CNT',
			table0.SAVINGS_IN_CONSOLIDATION_AMT AS SAVINGS_IN_CONSOLIDATION_AMT LABEL='SAVINGS_IN_CONSOLIDATION_AMT',
			table0.COLLATERAL_CD AS COLLATERAL_CD LABEL='COLLATERAL_CD',
			table0.COLLATERAL_AMT AS COLLATERAL_AMT LABEL='COLLATERAL_AMT',
			table0.BORROWED_DOWNPAYMENT_FLG AS BORROWED_DOWNPAYMENT_FLG LABEL='BORROWED_DOWNPAYMENT_FLG',
			table0.BORROWED_DOWNPAYMENT_PCT AS BORROWED_DOWNPAYMENT_PCT LABEL='BORROWED_DOWNPAYMENT_PCT',
			table0.FORECLOSED_FLG AS FORECLOSED_FLG LABEL='FORECLOSED_FLG',
			table0.CLLTRL_MTHLY_INS_PREM_AMT AS CLLTRL_MTHLY_INS_PREM_AMT LABEL='CLLTRL_MTHLY_INS_PREM_AMT',
			table0.CLLTRL_ONE_TIME_INS_PREM_AMT AS CLLTRL_ONE_TIME_INS_PREM_AMT LABEL='CLLTRL_ONE_TIME_INS_PREM_AMT',
			table0.OUTCOME_CD AS OUTCOME_CD LABEL='OUTCOME_CD',
			table0.DECISION_CD AS DECISION_CD LABEL='DECISION_CD',
			table0.DECISION_OVERRIDE_FLG AS DECISION_OVERRIDE_FLG LABEL='DECISION_OVERRIDE_FLG',
			table0.OVERRIDE_REASON_CD AS OVERRIDE_REASON_CD LABEL='OVERRIDE_REASON_CD',
			table0.SOURCE_CD AS SOURCE_CD LABEL='SOURCE_CD',
			table0.PROCESSING_CHARGES_AMT AS PROCESSING_CHARGES_AMT LABEL='PROCESSING_CHARGES_AMT',
			table0.PRODUCT_RK AS PRODUCT_RK LABEL='PRODUCT_RK' FORMAT=12.,
			table0.CHANNEL_CD AS CHANNEL_CD LABEL='CHANNEL_CD',
			table0.COUNTRY_CD AS COUNTRY_CD LABEL='COUNTRY_CD',
			table0.CUSTOMER_RK AS CUSTOMER_RK_2 LABEL='CUSTOMER_RK_2' FORMAT=F12.0,
			 ( table0.APPLICATION_DT )  AS APPLICATION_DT LABEL='APPLICATION_DT' FORMAT=NLDATM21.,
			 ( table0.CLLTRL_INS_END_DT )  AS CLLTRL_INS_END_DT LABEL='CLLTRL_INS_END_DT' FORMAT=NLDATM21.,
			 ( table0.CLLTRL_INS_START_DT )  AS CLLTRL_INS_START_DT LABEL='CLLTRL_INS_START_DT' FORMAT=NLDATM21.,
			 ( table0.OUTCOME_DT )  AS OUTCOME_DT LABEL='OUTCOME_DT' FORMAT=NLDATM21.,
			table3.FINANCIAL_PRODUCT_TYPE_CD AS FINANCIAL_PRODUCT_TYPE_CD LABEL='FINANCIAL_PRODUCT_TYPE_CD',
			table3.PRODUCT_SUB_TYPE_CD AS PRODUCT_SUB_TYPE_CD LABEL='PRODUCT_SUB_TYPE_CD',
			 ( CASE WHEN table0.CUSTOMER_RK= . THEN 0 ELSE 1 END  )  AS PRI_APPT_EXISTING_CUST_CNT LABEL='PRI_APPT_EXISTING_CUST_CNT' FORMAT=F12.0,
			 ( CASE WHEN table3.FINANCIAL_PRODUCT_TYPE_CD  IN (&CCD_PRD_TYPE) THEN &CCD_PRD_TYPE
		 WHEN  table0.LOAN_SECURED_FLG  IN (&CHECK_FLAG_TRUE) AND  table3.FINANCIAL_PRODUCT_TYPE_CD  IN (&LON_PRD_TYPE,&MTG_PRD_TYPE) THEN &PRD_HIER_SLN
		WHEN  table3.FINANCIAL_PRODUCT_TYPE_CD  IN (&LON_PRD_TYPE) AND COALESCEC(table0.LOAN_SECURED_FLG ,&CHECK_FLAG_FALSE) = &CHECK_FLAG_FALSE THEN &PRD_HIER_ULN 
		WHEN table3.FINANCIAL_PRODUCT_TYPE_CD  IN (&LON_PRD_TYPE,&MTG_PRD_TYPE) THEN &NRV_ASSET_PRD_CAT_TYPE 
		ELSE ' '
		 END )  AS PRODUCT_HIERARCHY_CD LABEL='PRODUCT_HIERARCHY_CD',
			 ( 1 )  AS APPLICATION_CNT LABEL='APPLICATION_CNT' 
		FROM
						dim.APPLICATION_DIM table0 left join dim.FINANCIAL_PRODUCT_DIM table3 on (table3.PRODUCT_RK = table0.PRODUCT_RK 
				   and APPLICATION_DT ge table3.VALID_START_DTTM and APPLICATION_DT lt table3.VALID_END_DTTM ) ;
		quit;

		%dabt_err_chk(type=SQL);


		PROC SQL ;
		Create table CONTACTS_FACT_BASE as
		SELECT 
			table1.CUSTOMER_RK AS CUSTOMER_RK LABEL='CUSTOMER_RK',
			table3.NO_OF_CONTACTS AS NO_OF_CONTACTS LABEL='NO_OF_CONTACTS',
			table5.TRANSACTION_TYPE_CD AS TRANSACTION_TYPE_CD LABEL='TRANSACTION_TYPE_CD' FORMAT=$3.,
			 ( table4.PERIOD_LAST_DTTM )  AS PERIOD_LAST_DTTM LABEL='PERIOD_LAST_DTTM' FORMAT=NLDATM21.,
			table0.CHANNEL_CD AS CHANNEL_CD LABEL='CHANNEL_CD' FORMAT=$3.,
			table2.FINANCIAL_PRODUCT_TYPE_CD AS FINANCIAL_PRODUCT_TYPE_CD LABEL='FINANCIAL_PRODUCT_TYPE_CD' FORMAT=$3.,
			table2.PRODUCT_SUB_TYPE_CD AS PRODUCT_SUB_TYPE_CD LABEL='PRODUCT_SUB_TYPE_CD' FORMAT=$3. 
		FROM
			dim.CHANNEL_DIM table0 Inner join fact.CONTACTS_FACT table3 on table0.CHANNEL_SK = table3.CHANNEL_SK 
			Inner join dim.FINANCIAL_PRODUCT_DIM table2 on table2.PRODUCT_SK = table3.PRODUCT_SK 
			Inner join dim.CUSTOMER_DIM table1 on table1.CUSTOMER_SK = table3.CUSTOMER_SK
			 
				Inner join dim.TIME_DIM table4 on table4.TIME_SK = table3.TIME_SK 
			Inner join dim.TRANSACTION_TYPE_DIM table5 on table5.TRANSACTION_TYPE_SK = table3.TRANSACTION_TYPE_SK ;
		quit;

		%dabt_err_chk(type=SQL);
		
		PROC SQL ;
		Create table work.ACCOUNT_TRANSACTION_BASE as
		SELECT 
			table0.ACCOUNT_RK AS ACCOUNT_RK LABEL='ACCOUNT_RK' FORMAT=12.,
			table2.CUSTOMER_RK AS CUSTOMER_RK LABEL='CUSTOMER_RK' FORMAT=12.,
			table1.CREDIT_FACILITY_RK AS CREDIT_FACILITY_RK LABEL='CREDIT_FACILITY_RK' FORMAT=12.,
			 ( table12.PERIOD_LAST_DTTM )  AS PERIOD_LAST_DTTM LABEL='PERIOD_LAST_DTTM' FORMAT=NLDATM21.,
			table9.LATE_PAYMENT_CNT AS LATE_PAYMENT_CNT LABEL='Late Payment Count' FORMAT=BEST12.,
			table9.MAX_TRANSACTION_AMT AS MAX_TRANSACTION_AMT LABEL='Max Transaction Amount' FORMAT=NLNUM18.5,
			table9.MIN_TRANSACTION_AMT AS MIN_TRANSACTION_AMT LABEL='Min Transaction Amount' FORMAT=NLNUM18.5,
			table9.OVER_LIMIT_CNT AS OVER_LIMIT_CNT LABEL='Over Limit Count' FORMAT=BEST12.,
			table9.TRANSACTION_AMT AS TRANSACTION_AMT LABEL='Transaction Amount' FORMAT=NLNUM18.5,
			table9.TRANSACTION_CNT AS TRANSACTION_CNT LABEL='Transaction Count' FORMAT=BEST12.,
			table0.ACCOUNT_SUB_TYPE_CD AS ACCOUNT_SUB_TYPE_CD LABEL='Account Sub Type Code' FORMAT=$3.,
			table0.ACCOUNT_TYPE_CD AS ACCOUNT_TYPE_CD LABEL='Account Type Code' FORMAT=$3.,
			table7.FINANCIAL_PRODUCT_TYPE_CD AS FINANCIAL_PRODUCT_TYPE_CD LABEL='Financial Product Type Code',
			table7.PRODUCT_SUB_TYPE_CD AS PRODUCT_SUB_TYPE_CD LABEL='Product Sub Type Code',
			table1.CREDIT_FACILITY_TYPE_CD AS CREDIT_FACILITY_TYPE_CD LABEL='Credit Facility Type Code' FORMAT=$3.,
			table3.CHANNEL_CD AS CHANNEL_CD LABEL='Channel Code',
			table4.COUNTRY_CD AS COUNTRY_CD LABEL='Country Code',
			table6.FEE_REASON_TYPE_CD AS FEE_REASON_TYPE_CD LABEL='Fee Reason Type Code',
			table8.INTERNAL_ORG_TYPE_CD AS INTERNAL_ORG_TYPE_CD LABEL='Internal Org Type Code',
			table10.MEDIUM_CD AS MEDIUM_CD LABEL='Medium Code',
			table13.TRANSACTION_STATUS_CD AS TRANSACTION_STATUS_CD LABEL='Transaction Status Code',
			table5.TRANSACTION_TYPE_CD AS TRANSACTION_TYPE_CD LABEL='Transaction Type Code',
			table5.CREDIT_DEBIT_FLG AS CREDIT_DEBIT_FLG LABEL='Credit Debit Flag',
			table11.MERCHANT_CATEGORY_CD AS MERCHANT_CATEGORY_CD LABEL='Merchant Category Code',
			table14.TRANSACTION_STATUS_REASON_CD AS TRANSACTION_STATUS_REASON_CD LABEL='Transaction Status Reason Code',
			 ( CASE  WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&CHK_ACCOUNT_SUB_TYPE) THEN  &ACC_HIER_CHK 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&CCD_ACCOUNT_TYPE) THEN &ACC_HIER_CCD  
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&SAV_ACCOUNT_SUB_TYPE,&CHK_ACCOUNT_SUB_TYPE) AND table0.ALLOW_OVERDRAFT_FLG IN (&CHECK_FLAG_TRUE)  THEN &ACC_HIER_OD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN (&RDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_RD
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN  (&SAV_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_SAV 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&MTG_ACCOUNT_TYPE, &LON_ACCOUNT_TYPE) AND table0.COLLATERAL_CD IS NOT NULL THEN &ACC_HIER_SLN     
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD  IN (&TDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_TD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&LON_ACCOUNT_TYPE) AND (table0.COLLATERAL_CD IS NULL) THEN &ACC_HIER_ULN  ELSE ' '  END  )  AS ACCOUNT_HIERARCHY_CD LABEL='ACCOUNT_HIERARCHY_CD',
			 ( (case when KUPCASE(table4.COUNTRY_CD)  = KUPCASE(table8.INTERNAL_ORG_COUNTRY_CD) then 0 else 1 end) )  AS INTERNATIONAL_CNT LABEL='INTERNATIONAL_CNT'     	
			 /* i18nOK:END */
		FROM
			fact.ACCOUNT_TRANSACTION_FACT table9 Inner join dim.ACCOUNT_DIM table0 
			on table9.ACCOUNT_SK = table0.ACCOUNT_SK
			Inner join dim.CREDIT_FACILITY_DIM table1 
			on table9.CREDIT_FACILITY_SK = table1.CREDIT_FACILITY_SK 
			Inner join dim.CUSTOMER_DIM table2 
			on table9.CUSTOMER_SK = table2.CUSTOMER_SK 
			Inner join dim.CHANNEL_DIM table3
			on table9.CHANNEL_SK = table3.CHANNEL_SK
			Inner join dim.COUNTRY_DIM table4 
			on table9.COUNTRY_SK = table4.COUNTRY_SK 
			Inner join dim.TRANSACTION_TYPE_DIM table5
			on table9.TRANSACTION_TYPE_SK = table5.TRANSACTION_TYPE_SK
			Inner join dim.FEE_REASON_DIM table6 on 
			table9.FEE_REASON_TYPE_SK = table6.FEE_REASON_TYPE_SK 
			Inner join dim.FINANCIAL_PRODUCT_DIM table7 
			on table9.PRODUCT_SK = table7.PRODUCT_SK 
			Inner join dim.INTERNAL_ORG_DIM table8 
			on table9.INTERNAL_ORG_SK = table8.INTERNAL_ORG_SK 
			Inner join dim.MEDIUM_DIM table10 
			on table9.MEDIUM_SK = table10.MEDIUM_SK 
			Inner join dim.MERCHANT_CATEGORY_DIM table11 
			on table9.MERCHANT_CATEGORY_SK = table11.MERCHANT_CATEGORY_SK 
			Inner join dim.TIME_DIM table12 
			on table9.TIME_SK = table12.TIME_SK 
			Inner join dim.TRANSACTION_STATUS_DIM table13
			on table9.TRANSACTION_STATUS_SK = table13.TRANSACTION_STATUS_SK 
			Inner join dim.TRANSACTION_STATUS_REASON_DIM table14 
			on table9.TRANSACTION_STATUS_REASON_SK = table14.TRANSACTION_STATUS_REASON_SK ;
		quit;

		%dabt_err_chk(type=SQL);


		PROC SQL ;
		Create table WORK.RECOVERY_FACT_BASE as
		SELECT 
		/* i18nOK:BEGIN */
			table0.ACCOUNT_RK AS ACCOUNT_RK LABEL='ACCOUNT_RK',    	
			table3.CREDIT_FACILITY_RK AS CREDIT_FACILITY_RK LABEL='CREDIT_FACILITY_RK',
			table4.CUSTOMER_RK AS CUSTOMER_RK LABEL='CUSTOMER_RK',
			table7.RECOVERY_COST_AMT AS RECOVERY_COST_AMT LABEL='RECOVERY_COST_AMT',
			table7.VALUE_AT_RECOVERY_AMT AS VALUE_AT_RECOVERY_AMT LABEL='VALUE_AT_RECOVERY_AMT',
			table7.VALUE_REALIZED_AMT AS VALUE_REALIZED_AMT LABEL='VALUE_REALIZED_AMT',
			 ( table6.PERIOD_LAST_DTTM )  AS PERIOD_LAST_DTTM LABEL='PERIOD_LAST_DTTM' FORMAT=NLDATM21.,
			table0.ACCOUNT_TYPE_CD AS ACCOUNT_TYPE_CD LABEL='ACCOUNT_TYPE_CD',
			table0.ACCOUNT_SUB_TYPE_CD AS ACCOUNT_SUB_TYPE_CD LABEL='ACCOUNT_SUB_TYPE_CD',
			table5.FINANCIAL_PRODUCT_TYPE_CD AS FINANCIAL_PRODUCT_TYPE_CD LABEL='FINANCIAL_PRODUCT_TYPE_CD',
			table5.PRODUCT_SUB_TYPE_CD AS PRODUCT_SUB_TYPE_CD LABEL='PRODUCT_SUB_TYPE_CD',
			table8.RECOVERY_FROM_TYPE_CD AS RECOVERY_FROM_TYPE_CD LABEL='RECOVERY_FROM_TYPE_CD',
			table3.CREDIT_FACILITY_TYPE_CD AS CREDIT_FACILITY_TYPE_CD LABEL='CREDIT_FACILITY_TYPE_CD',     	
			/* i18nOK:END */
			 ( CASE  WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&CHK_ACCOUNT_SUB_TYPE) THEN  &ACC_HIER_CHK 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&CCD_ACCOUNT_TYPE) THEN &ACC_HIER_CCD  
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND table0.ACCOUNT_SUB_TYPE_CD IN (&SAV_ACCOUNT_SUB_TYPE,&CHK_ACCOUNT_SUB_TYPE) AND table0.ALLOW_OVERDRAFT_FLG IN (&CHECK_FLAG_TRUE)  THEN &ACC_HIER_OD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN (&RDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_RD 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD IN  (&SAV_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_SAV 
			 WHEN table0.ACCOUNT_TYPE_CD IN (&MTG_ACCOUNT_TYPE, &LON_ACCOUNT_TYPE) AND table0.COLLATERAL_CD IS NOT NULL THEN &ACC_HIER_SLN     
			 WHEN table0.ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  table0.ACCOUNT_SUB_TYPE_CD  IN (&TDP_ACCOUNT_SUB_TYPE) THEN &ACC_HIER_TD  
			 WHEN table0.ACCOUNT_TYPE_CD IN (&LON_ACCOUNT_TYPE) AND (table0.COLLATERAL_CD IS NULL) THEN &ACC_HIER_ULN  ELSE ' '  END  )  AS ACCOUNT_HIERARCHY_CD LABEL='ACCOUNT_HIERARCHY_CD'    	/* i18nOK:LINE */
		FROM
			fact.RECOVERY_FACT table7 Inner join dim.ACCOUNT_DIM table0 on table7.ACCOUNT_SK = table0.ACCOUNT_SK 
			Inner join dim.CREDIT_FACILITY_DIM table3 on table3.CREDIT_FACILITY_SK = table7.CREDIT_FACILITY_SK 
			Inner join dim.CUSTOMER_DIM table4 on table4.CUSTOMER_SK = table7.CUSTOMER_SK 
			Inner join dim.FINANCIAL_PRODUCT_DIM table5 on table5.PRODUCT_SK = table7.PRODUCT_SK 
			Inner join dim.TIME_DIM table6 on table6.TIME_SK = table7.TIME_SK
			Inner join dim.RECOVERY_FROM_TYPE_DIM table8 on table8.RECOVERY_FROM_TYPE_SK = table7.RECOVERY_FROM_TYPE_SK ;
		quit;
		

		/* Run cport for creating XPT */

		proc cport lib=work file="&path_to_source_im_xpt/BNKF_IM_RMCR.xpt";   	/* i18nOK:LINE */
			SELECT INQUIRY_FACT_BASE OUTBOUND_COMM_FACT_BASE ACCOUNT_SNAPSHOT_BASE IND_CUSTOMER_X_ACCOUNT CONTACTS_FACT_BASE ACCOUNT_TRANSACTION_BASE ;
		run; 

		%let job_rc=&syscc;
		
		proc cport lib=work file="&path_to_source_im_xpt/CSB_IM_RMCR.xpt";     	/* i18nOK:LINE */
			SELECT CORP_CRD_FACILITY_X_CUSTOMER CORP_ACCOUNT_X_CUSTOMER ALL_APPLICATION_DIM RECOVERY_FACT_BASE;
		run; 
		
		%let job_rc=&syscc;
	%end;/*end to check if banking content applied*/
	
	%mend rmcr_63_infomaps_export;
	
	/********************************************************************
	MACRO DEFINITON ENDS FOR MULTITABLE VIEWS
	*********************************************************************/
	
	/******************************************************
	Call macros for create export packages at staging area
	*******************************************************/
	

	%rmcr_63_infomaps_export();

	%if &job_rc > 4 %then %do;
		%put ERROR: Some error occurred in exporting infomaps;
		%return;
	%end;

%mend rmcr_63_source_infomap_export; 

