CREATE TABLE &LIBREF..ACCOUNT_OTHER_INFO_BASE (
     ACCOUNT_RK           NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     PERIOD_LAST_DTTM     DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DTTM',
     LIMIT_INCR_CNT       NUMERIC(1) label='LIMIT_INCR_CNT',
     LIMIT_DECR_CNT       NUMERIC(1) label='LIMIT_DECR_CNT',
     OD_LIMIT_INC_CNT     NUMERIC(1) label='OD_LIMIT_INC_CNT',
     OD_LIMIT_DEC_CNT     NUMERIC(1) label='OD_LIMIT_DEC_CNT',
     CUSTOMER_RK          NUMERIC(10) NOT NULL FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     CREDIT_FACILITY_RK   NUMERIC(10) NOT NULL FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     ACCOUNT_TYPE_CD      VARCHAR(3) label='_CD',
     ACCOUNT_SUB_TYPE_CD  VARCHAR(3) label='_CD',
     ACCOUNT_HIERARCHY_CD VARCHAR(3) label='_CD',
     CREDIT_FACILITY_TYPE_CD VARCHAR(3) label='_CD',
     FINANCIAL_PRODUCT_TYPE_CD VARCHAR(3) label='_CD',
     PRODUCT_SUB_TYPE_CD  VARCHAR(3) label='_CD',
     TENURE_MTH_CNT       NUMERIC(6) label='TENURE_MTH_CNT',
     TERM_TYPE_CD         VARCHAR(3) label='_CD',
     UNUTILIZED_MTH_CNT   NUMERIC(6) label='UNUTILIZED_MTH_CNT',
     UNUTILIZED_MTH_TO_TENURE_PCT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='UNUTILIZED_MTH_TO_TENURE_PCT',
     CONSTRAINT PRIM_KEY PRIMARY KEY (ACCOUNT_RK, PERIOD_LAST_DTTM)
);

