CREATE TABLE &LIBREF..ACCOUNT_COUNTRY_DETAIL (
     ACCOUNT_RK           NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='ACCOUNT_RK',
     VALID_START_DTTM     DATE NOT NULL FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='VALID_START_DTTM',
     POSTAL_CD            VARCHAR(20) label='POSTAL_CD',
     CITY_NM              VARCHAR(100) label='CITY_NM',
     STATE_REGION_CD      VARCHAR(4) label='STATE_REGION_CD',
     COUNTRY_CD           VARCHAR(3) label='COUNTRY_CD',
     VALID_END_DTTM       DATE NOT NULL FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='VALID_END_DTTM',
     CREATED_BY           VARCHAR(20) label='CREATED_BY',
     CREATED_DTTM         DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='CREATED_DTTM',
     PROCESSED_DTTM       DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='PROCESSED_DTTM',
     CONSTRAINT PRIM_KEY PRIMARY KEY (ACCOUNT_RK, VALID_START_DTTM)
);

