CREATE TABLE &LIBREF..ACCOUNT_DETAIL (
     ACCOUNT_RK           NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     VALID_START_DTTM     DATE NOT NULL FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DTTM',
     VALID_END_DTTM       DATE NOT NULL FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DTTM',
     INTEREST_RT          NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='INTEREST_RT',
     INTEREST_RT_TYPE_CD  VARCHAR(10) label='INTEREST_RT_TYPE_CD',
     INTEREST_RT_CHANGE_REASON_CD VARCHAR(3) label='_CD',
     REFERENCE_RT         NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='REFERENCE_RT',
     MATURITY_DT          DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DT',
     RENEWAL_DT           DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DT',
     MATURITY_DT_CHANGE_REASON_CD VARCHAR(3) label='_CD',
     WORST_STATUS_LAST_12_MTH_CD VARCHAR(3) label='_CD',
     WORST_STATUS_LAST_12_MTH_DT DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DT',
     TERM                 NUMERIC(8) label='No or Amt',
     TERM_TIME_UOM_CD     VARCHAR(3) label='_CD',
     CREATED_BY           VARCHAR(20) label='CREATED_BY',
     CREATED_DTTM         DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DTTM',
     PROCESSED_DTTM       DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DTTM',
     CONSTRAINT PRIM_KEY PRIMARY KEY (ACCOUNT_RK, VALID_START_DTTM)
);

