create table  &LIBREF..CONTACTS_FACT_BASE 
(CUSTOMER_RK num (8) "CUSTOMER_RK ",
NO_OF_CONTACTS num (8) "NO_OF_CONTACTS ",
TRANSACTION_TYPE_CD char (3) "TRANSACTION_TYPE_CD ",
PERIOD_LAST_DTTM num (8) "PERIOD_LAST_DTTM ",
CHANNEL_CD char (3) "CHANNEL_CD ",
FINANCIAL_PRODUCT_TYPE_CD char (3) "FINANCIAL_PRODUCT_TYPE_CD ",
PRODUCT_SUB_TYPE_CD char (3) "PRODUCT_SUB_TYPE_CD ")
;
