create table  &LIBREF..CORP_CUST_COUNTRY_SNAPSHOT 
(CUSTOMER_RK num (8) "_RKorSK ",
COUNTRY_CD char (3) "_CD ",
PERIOD_LAST_DTTM num (8) "_DTTM ",
INFLATION_RT num (8) "INFLATION_RT ",
EMPLOYMENT_GROWTH_RT num (8) "EMPLOYMENT_GROWTH_RT ",
ANNUAL_GDP_GROWTH_RT num (8) "ANNUAL_GDP_GROWTH_RT ",
POPULATION_GROWTH_RT num (8) "POPULATION_GROWTH_RT ",
AVG_PERSONAL_INCOME_GROWTH_RT num (8) "AVG_PERSONAL_INCOME_GROWTH_RT ",
HOUSE_PRICE_INDEX_RT num (8) "HOUSE_PRICE_INDEX_RT ",
UNEMPLOYMENT_RT num (8) "UNEMPLOYMENT_RT ",
TREASURY_10_YR_RT num (8) "TREASURY_10_YR_RT ",
TREASURY_1_YEAR_RT num (8) "TREASURY_1_YEAR_RT ",
CASH_FLOW_DISCOUNT_RT num (8) "CASH_FLOW_DISCOUNT_RT ",
CONSUMER_PRICE_INDEX_RT num (8) "CONSUMER_PRICE_INDEX_RT ")
;