CREATE TABLE &LIBREF..COUNTRY_DETAIL (
     COUNTRY_CD           VARCHAR(3) label='Country Code',
     VALID_START_DTTM     DATE NOT NULL FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='From Date',
     VALID_END_DTTM       DATE NOT NULL FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='To Date',
     INFLATION_RT         NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='Inflation Rate',
     ANNUAL_GDP_GROWTH_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='Annual GDP Growth Rate',
     EMPLOYMENT_GROWTH_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='Employment growth rate',
     POPULATION_GROWTH_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='Population Growth Rate',
     AVG_PERSONAL_INCOME_GROWTH_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='Average Personal Growth Rate',
     HOUSE_PRICE_INDEX_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='House Price Index Rate',
     UNEMPLOYMENT_RT      NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='Unemployment Rate',
     TREASURY_10_YR_RT    NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='10-year Treasury rate',
     TREASURY_1_YEAR_RT   NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='1-year Treasury rate',
     CASH_FLOW_DISCOUNT_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='Cash flow discount rate',
     CONSUMER_PRICE_INDEX_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='Consumer Price Index',
     CREATED_BY           VARCHAR(20) label='CREATED_BY',
     CREATED_DTTM         DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DTTM',
     PROCESSED_DTTM       DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='Processed Datetime',
     CONSTRAINT PRIM_KEY PRIMARY KEY (COUNTRY_CD, VALID_START_DTTM)
);

