CREATE TABLE &LIBREF..COUNTRY_SNAPSHOT_BASE (
     COUNTRY_CD           VARCHAR(3) label='_CD',
     PERIOD_LAST_DTTM     DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DTTM',
     INFLATION_RT         NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='INFLATION_RT',
     EMPLOYMENT_GROWTH_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='EMPLOYMENT_GROWTH_RT',
     ANNUAL_GDP_GROWTH_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='ANNUAL_GDP_GROWTH_RT',
     POPULATION_GROWTH_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='POPULATION_GROWTH_RT',
     AVG_PERSONAL_INCOME_GROWTH_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='AVG_PERSONAL_INCOME_GROWTH_RT',
     HOUSE_PRICE_INDEX_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='HOUSE_PRICE_INDEX_RT',
     UNEMPLOYMENT_RT      NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='UNEMPLOYMENT_RT',
     TREASURY_10_YR_RT    NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='TREASURY_10_YR_RT',
     TREASURY_1_YEAR_RT   NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='TREASURY_1_YEAR_RT',
     CASH_FLOW_DISCOUNT_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='CASH_FLOW_DISCOUNT_RT',
     CONSUMER_PRICE_INDEX_RT NUMERIC(9,4) FORMAT=NLNUM9.4 INFORMAT=NLNUM9.4 label='CONSUMER_PRICE_INDEX_RT',
     CONSTRAINT PRIM_KEY PRIMARY KEY (COUNTRY_CD, PERIOD_LAST_DTTM)
);

