CREATE TABLE &LIBREF..DEFAULT_EVENT_DIM (
     DEFAULT_EVENT_SK     NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     VALID_START_DTTM     DATE NOT NULL FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DTTM',
     VALID_END_DTTM       DATE NOT NULL FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DTTM',
     DEFAULT_EVENT_RK     NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     DEFAULT_EVENT_ID     VARCHAR(32) label='_Id',
     DEFAULT_DT           DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DT',
     ACCOUNT_RK           NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     EXPOSURE_AT_DEFAULT_AMT NUMERIC(18,5) FORMAT=NLNUM18.5 INFORMAT=NLNUM18.5 label='_AMT',
     DEFAULT_REASON_CD    VARCHAR(3) label='_CD',
     DEFAULT_STATUS_CD    VARCHAR(3) label='_CD',
     DEFAULT_TYPE_CD      VARCHAR(3) label='_CD',
     CREATED_BY           VARCHAR(20) label='CREATED_BY',
     CREATED_DTTM         DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DTTM',
     PROCESSED_DTTM       DATE FORMAT=&DTTMFMT INFORMAT=&DTTMFMT label='_DTTM',
     CONSTRAINT PRIM_KEY PRIMARY KEY (DEFAULT_EVENT_SK)
);

