create table  &LIBREF..OUTBOUND_COMM_FACT_BASE 
(ACCOUNT_RK num (8) "ACCOUNT_RK ",
CREDIT_FACILITY_RK num (8) "CREDIT_FACILITY_RK ",
CUSTOMER_RK num (8) "CUSTOMER_RK ",
OUTBOUND_COMM_CNT num (8) "OUTBOUND_COMM_CNT ",
PERIOD_LAST_DTTM num (8) "PERIOD_LAST_DTTM ",
ACCOUNT_TYPE_CD char (3) "ACCOUNT_TYPE_CD ",
ACCOUNT_SUB_TYPE_CD char (3) "ACCOUNT_SUB_TYPE_CD ",
FINANCIAL_PRODUCT_TYPE_CD char (3) "FINANCIAL_PRODUCT_TYPE_CD ",
PRODUCT_SUB_TYPE_CD char (3) "PRODUCT_SUB_TYPE_CD ",
CREDIT_FACILITY_TYPE_CD char (3) "CREDIT_FACILITY_TYPE_CD ",
TRANSACTION_TYPE_CD char (3) "TRANSACTION_TYPE_CD ",
CHANNEL_CD char (3) "CHANNEL_CD ",
ACCOUNT_HIERARCHY_CD char (3) "ACCOUNT_HIERARCHY_CD ")
;
