CREATE TABLE &LIBREF..RECOVERY_FACT (
     ACCOUNT_SK           NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     TIME_SK              NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     CUSTOMER_SK          NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='CUSTOMER_SK',
     DEFAULT_EVENT_SK     NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     RECOVERY_FROM_TYPE_SK NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     CREDIT_FACILITY_SK   NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='Credit Facility Key',
     SEGMENT_SK           NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     PRODUCT_SK           NUMERIC(10) FORMAT=&FMTRK INFORMAT=&FMTRK label='_RKorSK',
     VALUE_REALIZED_AMT   NUMERIC(18,5) FORMAT=NLNUM18.5 INFORMAT=NLNUM18.5 label='_AMT',
     RECOVERY_COST_AMT    NUMERIC(18,5) FORMAT=NLNUM18.5 INFORMAT=NLNUM18.5 label='_AMT',
     VALUE_AT_RECOVERY_AMT NUMERIC(18,5) FORMAT=NLNUM18.5 INFORMAT=NLNUM18.5 label='_AMT'
);

