/*****************************************************************************************
 * Copyright (c) 2019 by SAS Institute Inc., Cary, NC, USA.            
 *                                                                     
 * NAME			: rmcr_create_single_table_view  					                       
 *                                                                 
 * LOGIC		: This macro is invoked to generate the Views from base tables.
 *
 * USAGE		: %rmcr_create_single_table_view
 *
 * Called By	: 
 *                                                                 
 * PARAMETERS	:  
 *														   
 * Authors		: BIS Team
 *****************************************************************************************/
 
%macro rmcr_create_single_table_view();

	/* initiate cas session */
	
	%dabt_initiate_cas_session(cas_session_ref=create_view);
	
	%let default_value=.;
	%let high_date=&valid_high_dttm.; 

	
	/* New definition for CORP_CUSTOMER_SEC_OWNER_DETAIL */
	%let etls_viewExist = %eval(%sysfunc(exist(bankcrfm.CORP_CUSTOMER_SEC_OWNER_DETAIL, DATA)) or 
											%sysfunc(exist(bankcrfm.CORP_CUSTOMER_SEC_OWNER_DETAIL, VIEW))); 

	%if &etls_viewExist. eq 0 %then %do;
		proc cas;
		table.view/PROMOTE=TRUE
			/* I18NOK:BEGIN */
		caslib="bankcrfm"
		name="CORP_CUSTOMER_SEC_OWNER_DETAIL"
		tables={{
		name="CORPORATE_OWNER_DETAIL"
		caslib="bankcrfm"
		varlist={'OWNER_RK','VALID_START_DTTM','VALID_END_DTTM','OWNER_ID','CUSTOMER_RK',
										'BIRTH_DT','GENDER_CD','EDUCATION_LEVEL_CD','MARITAL_STATUS_CD','TAX_ID',
										'TAX_ID_TYPE_CD','OWNERSHIP_AMT','PERCENT_OWNED','RESIDENT_STATUS_CD',
										'ANNUAL_SALARY_BUSINESS_AMT','LIQUID_ASSETS_AMT','REAL_ESTATE_AMT',
										'ASSET_OTHER_AMT','TOTAL_ASSETS_AMT','LIABILITY_REAL_ESTATE_AMT',
										'MONTHLY_HOUSING_AMT','LIABILITY_OTHER_AMT','TOTAL_LIABILITY_AMT',
										'NET_WORTH_AMT','PENDING_LAWSUIT_FLG','BANKRUPTCY_FILED_DT',
										'BANKRUPTCY_STATUS_CD','POSTAL_CD','STATE_REGION_CD','TAX_BRACKET_CD',
										'DEPENDENTS_CNT','EMPLOYMENT_STATUS_CD','EMPLOYMENT_YEARS_CNT',
										'NO_OF_EMPLOYERS_CNT','TOTAL_EMPLOYMENT_YEARS_CNT','STD_OCCUPATION_CD',
										'TIME_RESIDENCE_YEAR_CNT','OTHER_CREDIT_CARDS_CNT','LIQUID_NET_WORTH_AMT',
										'LEGAL_JUDGEMENT_FLG','MAINTENANCE_FLG','OWNER_TYPE_CD','ANNUAL_INCOME_AMT',
										'HHOLD_INCOME_AMT','FRAUD_FLG','DELINQUENCY_FLG','FORECLOSED_FLG'}
		where="OWNER_TYPE_CD IN (&SEC_OWNER_TYPE_CD.)"
			/* I18NOK:END */
		}
		}
		;
		run;
		quit;
	%end;	
		
	/* New definition for CORP_CUSTOMER_PRI_OWNER_DETAIL */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.CORP_CUSTOMER_PRI_OWNER_DETAIL, DATA)) or 
											%sysfunc(exist(bankcrfm.CORP_CUSTOMER_PRI_OWNER_DETAIL, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
		proc cas;
		table.view/PROMOTE=TRUE
			/* I18NOK:BEGIN */
		caslib="bankcrfm"
		name="CORP_CUSTOMER_PRI_OWNER_DETAIL"
		tables={{
		name="CORPORATE_OWNER_DETAIL"
		caslib="bankcrfm"
		varlist={'OWNER_RK','VALID_START_DTTM','VALID_END_DTTM','OWNER_ID','CUSTOMER_RK',
										'BIRTH_DT','GENDER_CD','EDUCATION_LEVEL_CD','MARITAL_STATUS_CD','TAX_ID',
										'TAX_ID_TYPE_CD','OWNERSHIP_AMT','PERCENT_OWNED','RESIDENT_STATUS_CD',
										'ANNUAL_SALARY_BUSINESS_AMT','LIQUID_ASSETS_AMT','REAL_ESTATE_AMT',
										'ASSET_OTHER_AMT','TOTAL_ASSETS_AMT','LIABILITY_REAL_ESTATE_AMT',
										'MONTHLY_HOUSING_AMT','LIABILITY_OTHER_AMT','TOTAL_LIABILITY_AMT',
										'NET_WORTH_AMT','PENDING_LAWSUIT_FLG','BANKRUPTCY_FILED_DT',
										'BANKRUPTCY_STATUS_CD','POSTAL_CD','STATE_REGION_CD','TAX_BRACKET_CD',
										'DEPENDENTS_CNT','EMPLOYMENT_STATUS_CD','EMPLOYMENT_YEARS_CNT',
										'NO_OF_EMPLOYERS_CNT','TOTAL_EMPLOYMENT_YEARS_CNT','STD_OCCUPATION_CD',
										'TIME_RESIDENCE_YEAR_CNT','OTHER_CREDIT_CARDS_CNT','LIQUID_NET_WORTH_AMT',
										'LEGAL_JUDGEMENT_FLG','MAINTENANCE_FLG','OWNER_TYPE_CD','ANNUAL_INCOME_AMT',
										'HHOLD_INCOME_AMT','FRAUD_FLG','DELINQUENCY_FLG','FORECLOSED_FLG'}
		where="OWNER_TYPE_CD IN (&PRI_OWNER_TYPE_CD.)"
			/* I18NOK:END */
		}
		}
		;
		run;
		quit;
	%end;

	/* New definition for ALL_APPLICANT_DIM */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.ALL_APPLICANT_DIM, DATA)) or 
											%sysfunc(exist(bankcrfm.ALL_APPLICANT_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
		proc cas;
		table.view/PROMOTE=TRUE
			/* I18NOK:BEGIN */
		caslib="bankcrfm"
		name="ALL_APPLICANT_DIM"
		tables={{
		name="APPLICANT_DIM"
		caslib="bankcrfm"
		varlist={
		 'AGE', 'ANNUAL_INCOME_AMT','ANNUAL_SALARY_BUSINESS_AMT','APPLICANT_BIRTH_DT','APPLICANT_CITY_NM','APPLICANT_COUNTRY_CD','APPLICANT_ID','APPLICANT_NM','APPLICANT_POSTAL_CD','APPLICANT_RK','APPLICANT_SK', 'APPLICANT_STATE_REGION_CD','APPLICANT_TYPE_CD','APPLICATION_DT','APPLICATION_RK','ASSET_OTHER_AMT','BANKRUPTCY_FILED_DT','BANKRUPTCY_STATUS_CD', 'BUSINESS_COMMENCED_DT','BUSINESS_ESTABLISHED_DT', 'BUSINESS_NATURE_CD', 'CHILDREN_CNT','CREATED_BY','CREATED_DTTM','CURRENT_ADDRESS_START_DT','CURRENT_COUNTRY_START_DT','CURRENT_EMP_START_DT','CURRENT_EMP_TYPE_START_DT','CUSTOMER_RK','DEPENDENTS_CNT', 'EDUCATION_LEVEL_CD', 'ELDEST_CHILD_BIRTH_DT','EMPLOYMENT_POSITION_STATUS_CD','EMPLOYMENT_START_DT','EMPLOYMENT_STATUS_CD','EMPLOYMENT_YEARS_CNT','EXTERNAL_ORG_RK','FAMILY_MEMBER_ACCOUNT_CNT', 'GENDER_CD', 'HHOLD_INCOME_AMT', 'HHOLD_INDIVIDUALS_CNT','INDUSTRY_CD','INTERNAL_CREDIT_RATING_CD','LAST_APPLICATION_REFUSED_DT','LEGAL_JUDGEMENT_FLG','LIABILITY_OTHER_AMT','LIABILITY_REAL_ESTATE_AMT','LIQUID_ASSETS_AMT','LIQUID_NET_WORTH_AMT', 'MAINTENANCE_FLG', 'MARITAL_STATUS_CD', 'MONTHLY_ALIMONY_AMT', 'MONTHLY_BUSINESS_INCOME_AMT', 'MONTHLY_CHILD_ALLOW_AMT', 'MONTHLY_CHILD_SUPPORT_AMT','MONTHLY_HOUSING_AMT', 'MONTHLY_INVESTMENT_AMT', 'MONTHLY_OTHER_CHARGE_AMT', 'MONTHLY_OTHER_INCOME_AMT', 'MONTHLY_PRI_INCOME_SOURCE_CD', 'MONTHLY_RENTAL_AMT','MONTHLY_RENTAL_INCOME_AMT','MONTHLY_REPAYMENT_AMT', 'MONTHLY_REPAYMENT_OTHERS_AMT', 'MONTHLY_REPLACEMENT_INCOME_AMT', 'MONTHLY_SALARY_INCOME_AMT', 'MONTHS_AT_PREVIOUS_ADDRESS_CNT', 'NET_WORTH_AMT','NO_OF_EMPLOYERS_CNT','NUM_EMPLOYEES_CNT','NUM_OFFICES_CNT', 'ORGANIZATION_NM', 'OTHER_CREDIT_CARDS_CNT', 'OWN_AUTOMOBILE_FLG', 'OWN_MOTORCYCLE_FLG', 'OWN_RESIDENCE_PROPERTY_FLG', 'OWNERSHIP_AMT', 'OWNERSHIP_CD', 'OWNERSHIP_CNT','PASSPORT_ISSUE_COUNTRY_CD', 'PENDING_LAWSUIT_FLG', 'PERCENT_OWNED', 'PRIMARY_CITIZENSHIP_COUNTRY_CD', 'PROCESSED_DTTM', 'REAL_ESTATE_AMT', 'RELATIONSHIP_CD', 'RESIDENCE_STATUS_CD', 'SELF_EMPLOYMENT_FLG', 'STD_OCCUPATION_CD','TAX_BRACKET_CD', 'TAX_ID', 'TAX_ID_TYPE_CD', 'TEMPORARY_EMPLOYMENT_END_DT', 'TIME_RESIDENCE_YEAR_CNT', 'TOTAL_ASSET_AMT','TOTAL_EMPLOYMENT_YEARS_CNT', 'TOTAL_LIABILITY_AMT', 'VALID_END_DTTM','VALID_START_DTTM', 'YOUNGEST_CHILD_BIRTH_DT'}
		computedVars={{name="LAST_MONTH_END_DT"}}
		computedVarsprogram="LAST_MONTH_END_DT=IF APPLICATION_DT=intnx('DTMONTH',APPLICATION_DT ,0,'END') THEN APPLICATION_DT
				ELSE IF APPLICATION_DT < intnx('DTMONTH',APPLICATION_DT ,0,'END') THEN intnx('DTMONTH',APPLICATION_DT, -1,'END')
				ELSE IF (&FM_GRAIN. = 2 AND APPLICATION_DT = intnx('DTWEEK',APPLICATION_DT ,0,'END')) THEN APPLICATION_DT
				ELSE IF (&FM_GRAIN. = 2 AND APPLICATION_DT < intnx('DTWEEK',APPLICATION_DT ,0,'END')) THEN intnx('DTWEEK',APPLICATION_DT, -1,'END')
				ELSE IF &FM_GRAIN. = 3 THEN APPLICATION_DT
				ELSE &default_value. ; "
		where="valid_end_dttm=&high_date"
			/* I18NOK:END */
		}
		}
		;
		QUIT;
			
	%end;

	/* New definition for GUR_CORP_APPLICANT_DIM */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.GUR_CORP_APPLICANT_DIM, DATA)) or %sysfunc(exist(bankcrfm.GUR_CORP_APPLICANT_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
		proc cas;
		table.view/PROMOTE=TRUE
			/* I18NOK:BEGIN */
		caslib="bankcrfm"
		name="GUR_CORP_APPLICANT_DIM"
		tables={{
		name="APPLICANT_DIM"
		caslib="bankcrfm"
		varlist={'APPLICANT_SK','APPLICANT_RK','APPLICATION_RK','CUSTOMER_RK','APPLICANT_ID','APPLICANT_TYPE_CD',
				'APPLICANT_NM','RELATIONSHIP_CD','APPLICANT_CITY_NM','APPLICANT_POSTAL_CD','APPLICANT_STATE_REGION_CD',
				'CURRENT_COUNTRY_START_DT','PENDING_LAWSUIT_FLG','LEGAL_JUDGEMENT_FLG','BANKRUPTCY_STATUS_CD',
				'BANKRUPTCY_FILED_DT','INTERNAL_CREDIT_RATING_CD','OTHER_CREDIT_CARDS_CNT','CURRENT_ADDRESS_START_DT',
				'BUSINESS_NATURE_CD','TAX_BRACKET_CD','TAX_ID','TAX_ID_TYPE_CD','ANNUAL_INCOME_AMT','MAINTENANCE_FLG',
				'LAST_APPLICATION_REFUSED_DT','VALID_START_DTTM','VALID_END_DTTM','PROCESSED_DTTM','OWNERSHIP_AMT','INDUSTRY_CD',
				'ORGANIZATION_NM','NUM_EMPLOYEES_CNT','OWNERSHIP_CNT','EXTERNAL_ORG_RK','OWNERSHIP_CD','PERCENT_OWNED',
				'NUM_OFFICES_CNT','BUSINESS_ESTABLISHED_DT','BUSINESS_COMMENCED_DT','APPLICATION_DT'}
			computedVars={{name="CURR_ADD_MTH_CNT"} {name="CUSTOMER_EXIST_CNT"}{name="COUNTRY_CD"}}
			computedVarsprogram="CURR_ADD_MTH_CNT=intck('DTMONTH',CURRENT_ADDRESS_START_DT,APPLICATION_DT ); CUSTOMER_EXIST_CNT=IF CUSTOMER_RK > 0 THEN 1 ELSE 0;
									COUNTRY_CD=PRIMARY_CITIZENSHIP_COUNTRY_CD;"
				where= "APPLICANT_TYPE_CD IN (&GUR1_APP_TYPE_CD.) AND valid_end_dttm=&high_date." 
					/* I18NOK:END */
		}
		}
		;
		QUIT;
	%end;

	/* New definition for GUR_IND_APPLICANT_DIM */

	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.GUR_IND_APPLICANT_DIM, DATA)) or %sysfunc(exist(bankcrfm.GUR_IND_APPLICANT_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
		proc cas;
			table.view/PROMOTE=TRUE
				/* I18NOK:BEGIN */
			caslib="bankcrfm"
			name="GUR_IND_APPLICANT_DIM"
			tables={{
			name="APPLICANT_DIM"
			caslib="bankcrfm" 	
			varlist={'APPLICANT_SK','APPLICANT_RK','APPLICATION_RK','CUSTOMER_RK','APPLICANT_ID',
						'APPLICANT_TYPE_CD','APPLICANT_BIRTH_DT','GENDER_CD','MARITAL_STATUS_CD',
						'RELATIONSHIP_CD','APPLICANT_CITY_NM','APPLICANT_POSTAL_CD','APPLICANT_STATE_REGION_CD',
						'APPLICANT_COUNTRY_CD','EDUCATION_LEVEL_CD','STD_OCCUPATION_CD','PRIMARY_CITIZENSHIP_COUNTRY_CD',
						'DEPENDENTS_CNT','PASSPORT_ISSUE_COUNTRY_CD','CURRENT_COUNTRY_START_DT','CHILDREN_CNT',
						'ELDEST_CHILD_BIRTH_DT','YOUNGEST_CHILD_BIRTH_DT','PENDING_LAWSUIT_FLG',
						'LEGAL_JUDGEMENT_FLG','BANKRUPTCY_STATUS_CD','BANKRUPTCY_FILED_DT',
						'FAMILY_MEMBER_ACCOUNT_CNT','HHOLD_INDIVIDUALS_CNT','INTERNAL_CREDIT_RATING_CD',
						'OTHER_CREDIT_CARDS_CNT','OWN_RESIDENCE_PROPERTY_FLG','OWN_AUTOMOBILE_FLG',
						'CURRENT_ADDRESS_START_DT','OWN_MOTORCYCLE_FLG','TIME_RESIDENCE_YEAR_CNT',
						'RESIDENCE_STATUS_CD','EMPLOYMENT_POSITION_STATUS_CD','MONTHS_AT_PREVIOUS_ADDRESS_CNT',
						'EMPLOYMENT_STATUS_CD','NO_OF_EMPLOYERS_CNT','TEMPORARY_EMPLOYMENT_END_DT',
						'EMPLOYMENT_YEARS_CNT','TOTAL_EMPLOYMENT_YEARS_CNT','BUSINESS_NATURE_CD',
						'CURRENT_EMP_START_DT','EMPLOYMENT_START_DT','TAX_BRACKET_CD','TAX_ID','TAX_ID_TYPE_CD',
						'MONTHLY_SALARY_INCOME_AMT','MONTHLY_BUSINESS_INCOME_AMT','MONTHLY_PRI_INCOME_SOURCE_CD',
						'MONTHLY_RENTAL_INCOME_AMT','MONTHLY_REPLACEMENT_INCOME_AMT','MONTHLY_OTHER_INCOME_AMT',
						'MONTHLY_CHILD_ALLOW_AMT','ANNUAL_INCOME_AMT','HHOLD_INCOME_AMT','MONTHLY_HOUSING_AMT',
						'MONTHLY_ALIMONY_AMT','MONTHLY_CHILD_SUPPORT_AMT','MONTHLY_REPAYMENT_AMT',
						'MONTHLY_REPAYMENT_OTHERS_AMT','MONTHLY_OTHER_CHARGE_AMT','MAINTENANCE_FLG',
						'MONTHLY_INVESTMENT_AMT','LIQUID_ASSETS_AMT','ASSET_OTHER_AMT','REAL_ESTATE_AMT',
						'TOTAL_ASSET_AMT','LIABILITY_REAL_ESTATE_AMT','LIABILITY_OTHER_AMT','TOTAL_LIABILITY_AMT',
						'NET_WORTH_AMT','LIQUID_NET_WORTH_AMT','LAST_APPLICATION_REFUSED_DT','MONTHLY_RENTAL_AMT',
						'INDUSTRY_CD','CURRENT_EMP_TYPE_START_DT','ANNUAL_SALARY_BUSINESS_AMT','SELF_EMPLOYMENT_FLG',
						'AGE','VALID_START_DTTM','VALID_END_DTTM','APPLICATION_DT','BUSINESS_ESTABLISHED_DT','BUSINESS_COMMENCED_DT'}
			 
			computedVars={{name="CURR_ADD_MTH_CNT"}{name="CURR_BSS_SNC_MTH_CNT"}{name="CURR_EMP_TYP_MTH_CNT"}{name="CUSTOMER_EXIST_CNT"}{name="ELD_CHLD_AGE_NO"}{name="TMP_EMP_EXPI_MTH_CNT"}
										{name="YNG_CHLD_AGE_NO"}{name="MONTHLY_INCOME_AMT", formattedLength = "8",format="NLNUM18.5"} {name="NET_MONTHLY_INCOME_AMT", formattedLength = "8",format="NLNUM18.5"}
										{name="MONTHLY_EXPENSE_AMT",format="NLNUM18.5"}{name="FRGN_CNTRY_MTH_CNT"}{name="COUNTRY_CD"}}
										
			computedVarsprogram="CURR_ADD_MTH_CNT=intck('DTMONTH',CURRENT_ADDRESS_START_DT,APPLICATION_DT ); CURR_BSS_SNC_MTH_CNT=intck('DTMONTH',CURRENT_EMP_START_DT,APPLICATION_DT );
										CURR_EMP_TYP_MTH_CNT=intck('DTMONTH',CURRENT_EMP_TYPE_START_DT,APPLICATION_DT );CUSTOMER_EXIST_CNT=IF CUSTOMER_RK > 0 THEN 1 ELSE 0;
										ELD_CHLD_AGE_NO=intck('dtyear',ELDEST_CHILD_BIRTH_DT,APPLICATION_DT );TMP_EMP_EXPI_MTH_CNT=intck('dtmonth',APPLICATION_DT,TEMPORARY_EMPLOYMENT_END_DT );
										YNG_CHLD_AGE_NO=intck('dtyear',YOUNGEST_CHILD_BIRTH_DT,APPLICATION_DT );MONTHLY_INCOME_AMT=sum(MONTHLY_BUSINESS_INCOME_AMT, MONTHLY_SALARY_INCOME_AMT, MONTHLY_CHILD_ALLOW_AMT , MONTHLY_OTHER_INCOME_AMT ,MONTHLY_RENTAL_INCOME_AMT, MONTHLY_REPLACEMENT_INCOME_AMT);NET_MONTHLY_INCOME_AMT=SUM(MONTHLY_SALARY_INCOME_AMT ,MONTHLY_BUSINESS_INCOME_AMT ,MONTHLY_RENTAL_INCOME_AMT,MONTHLY_REPLACEMENT_INCOME_AMT ,MONTHLY_OTHER_INCOME_AMT ,MONTHLY_CHILD_ALLOW_AMT ,-MONTHLY_INVESTMENT_AMT  ,-MONTHLY_ALIMONY_AMT , -MONTHLY_CHILD_SUPPORT_AMT ,-MONTHLY_HOUSING_AMT ,-MONTHLY_REPAYMENT_AMT ,-MONTHLY_REPAYMENT_OTHERS_AMT ,-MONTHLY_OTHER_CHARGE_AMT );
										MONTHLY_EXPENSE_AMT=sum( MONTHLY_CHILD_SUPPORT_AMT , MONTHLY_HOUSING_AMT ,MONTHLY_OTHER_CHARGE_AMT  , MONTHLY_INVESTMENT_AMT , 
										MONTHLY_REPAYMENT_AMT, MONTHLY_RENTAL_AMT ,MONTHLY_REPAYMENT_OTHERS_AMT, MONTHLY_ALIMONY_AMT );
										FRGN_CNTRY_MTH_CNT=intck('DTMONTH',CURRENT_COUNTRY_START_DT,APPLICATION_DT );COUNTRY_CD=PRIMARY_CITIZENSHIP_COUNTRY_CD;"
			where= "APPLICANT_TYPE_CD IN (&GUR1_APP_TYPE_CD.) AND valid_end_dttm=&high_date."
				/* I18NOK:END */
		}
		}
		;
		QUIT;   
	%end;

	/* New definition for NOM_CORP_APPLICANT_DIM */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.NOM_CORP_APPLICANT_DIM, DATA)) or %sysfunc(exist(bankcrfm.NOM_CORP_APPLICANT_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
			
		proc cas;
			table.view/PROMOTE=TRUE
				/* I18NOK:BEGIN */
			caslib="bankcrfm"
			name="NOM_CORP_APPLICANT_DIM"
			tables={{
			name="APPLICANT_DIM"
			caslib="bankcrfm"
			varlist={'APPLICANT_SK','APPLICANT_RK','APPLICATION_RK','CUSTOMER_RK','APPLICANT_ID','APPLICANT_TYPE_CD',
					'APPLICANT_NM','RELATIONSHIP_CD','APPLICANT_CITY_NM','APPLICANT_POSTAL_CD','APPLICANT_STATE_REGION_CD',
					'CURRENT_COUNTRY_START_DT','PENDING_LAWSUIT_FLG','LEGAL_JUDGEMENT_FLG','BANKRUPTCY_STATUS_CD',
					'BANKRUPTCY_FILED_DT','INTERNAL_CREDIT_RATING_CD','OTHER_CREDIT_CARDS_CNT','CURRENT_ADDRESS_START_DT',
					'BUSINESS_NATURE_CD','TAX_BRACKET_CD','TAX_ID','TAX_ID_TYPE_CD','ANNUAL_INCOME_AMT','MAINTENANCE_FLG',
					'LAST_APPLICATION_REFUSED_DT','VALID_START_DTTM','VALID_END_DTTM','PROCESSED_DTTM','OWNERSHIP_AMT','INDUSTRY_CD',
					'ORGANIZATION_NM','NUM_EMPLOYEES_CNT','OWNERSHIP_CNT','EXTERNAL_ORG_RK','OWNERSHIP_CD','PERCENT_OWNED',
					'NUM_OFFICES_CNT','BUSINESS_ESTABLISHED_DT','BUSINESS_COMMENCED_DT','APPLICATION_DT'}
			computedVars={{name="CURR_ADD_MTH_CNT"} {name="CUSTOMER_EXIST_CNT"}{name="COUNTRY_CD"}}
			computedVarsprogram="CURR_ADD_MTH_CNT=intck('DTMONTH',CURRENT_ADDRESS_START_DT,APPLICATION_DT ); CUSTOMER_EXIST_CNT=IF CUSTOMER_RK > 0 THEN 1 ELSE 0;
									COUNTRY_CD=PRIMARY_CITIZENSHIP_COUNTRY_CD;"
			where= "APPLICANT_TYPE_CD IN (&NOM1_APP_TYPE_CD.) AND valid_end_dttm=&high_date." 
				/* I18NOK:END */
		}
		}
		;
		QUIT;
	%end;

	/* New definition for NOM_IND_APPLICANT_DIM */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.NOM_IND_APPLICANT_DIM, DATA)) or %sysfunc(exist(bankcrfm.NOM_IND_APPLICANT_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
				 
		proc cas;
			table.view/PROMOTE=TRUE
				/* I18NOK:BEGIN */
			caslib="bankcrfm"
			name="NOM_IND_APPLICANT_DIM"
			tables={{
			name="APPLICANT_DIM"
			caslib="bankcrfm" 	
			varlist={'APPLICANT_SK','APPLICANT_RK','APPLICATION_RK','CUSTOMER_RK','APPLICANT_ID',
						'APPLICANT_TYPE_CD','APPLICANT_BIRTH_DT','GENDER_CD','MARITAL_STATUS_CD',
						'RELATIONSHIP_CD','APPLICANT_CITY_NM','APPLICANT_POSTAL_CD','APPLICANT_STATE_REGION_CD',
						'APPLICANT_COUNTRY_CD','EDUCATION_LEVEL_CD','STD_OCCUPATION_CD','PRIMARY_CITIZENSHIP_COUNTRY_CD',
						'DEPENDENTS_CNT','PASSPORT_ISSUE_COUNTRY_CD','CURRENT_COUNTRY_START_DT','CHILDREN_CNT',
						'ELDEST_CHILD_BIRTH_DT','YOUNGEST_CHILD_BIRTH_DT','PENDING_LAWSUIT_FLG',
						'LEGAL_JUDGEMENT_FLG','BANKRUPTCY_STATUS_CD','BANKRUPTCY_FILED_DT',
						'FAMILY_MEMBER_ACCOUNT_CNT','HHOLD_INDIVIDUALS_CNT','INTERNAL_CREDIT_RATING_CD',
						'OTHER_CREDIT_CARDS_CNT','OWN_RESIDENCE_PROPERTY_FLG','OWN_AUTOMOBILE_FLG',
						'CURRENT_ADDRESS_START_DT','OWN_MOTORCYCLE_FLG','TIME_RESIDENCE_YEAR_CNT',
						'RESIDENCE_STATUS_CD','EMPLOYMENT_POSITION_STATUS_CD','MONTHS_AT_PREVIOUS_ADDRESS_CNT',
						'EMPLOYMENT_STATUS_CD','NO_OF_EMPLOYERS_CNT','TEMPORARY_EMPLOYMENT_END_DT',
						'EMPLOYMENT_YEARS_CNT','TOTAL_EMPLOYMENT_YEARS_CNT','BUSINESS_NATURE_CD',
						'CURRENT_EMP_START_DT','EMPLOYMENT_START_DT','TAX_BRACKET_CD','TAX_ID','TAX_ID_TYPE_CD',
						'MONTHLY_SALARY_INCOME_AMT','MONTHLY_BUSINESS_INCOME_AMT','MONTHLY_PRI_INCOME_SOURCE_CD',
						'MONTHLY_RENTAL_INCOME_AMT','MONTHLY_REPLACEMENT_INCOME_AMT','MONTHLY_OTHER_INCOME_AMT',
						'MONTHLY_CHILD_ALLOW_AMT','ANNUAL_INCOME_AMT','HHOLD_INCOME_AMT','MONTHLY_HOUSING_AMT',
						'MONTHLY_ALIMONY_AMT','MONTHLY_CHILD_SUPPORT_AMT','MONTHLY_REPAYMENT_AMT',
						'MONTHLY_REPAYMENT_OTHERS_AMT','MONTHLY_OTHER_CHARGE_AMT','MAINTENANCE_FLG',
						'MONTHLY_INVESTMENT_AMT','LIQUID_ASSETS_AMT','ASSET_OTHER_AMT','REAL_ESTATE_AMT',
						'TOTAL_ASSET_AMT','LIABILITY_REAL_ESTATE_AMT','LIABILITY_OTHER_AMT','TOTAL_LIABILITY_AMT',
						'NET_WORTH_AMT','LIQUID_NET_WORTH_AMT','LAST_APPLICATION_REFUSED_DT','MONTHLY_RENTAL_AMT',
						'INDUSTRY_CD','CURRENT_EMP_TYPE_START_DT','ANNUAL_SALARY_BUSINESS_AMT','SELF_EMPLOYMENT_FLG',
						'AGE','VALID_START_DTTM','VALID_END_DTTM','APPLICATION_DT','BUSINESS_ESTABLISHED_DT','BUSINESS_COMMENCED_DT'}
			 
			computedVars={{name="CURR_ADD_MTH_CNT"}{name="CURR_BSS_SNC_MTH_CNT"}{name="CURR_EMP_TYP_MTH_CNT"}{name="CUSTOMER_EXIST_CNT"}{name="ELD_CHLD_AGE_NO"}{name="TMP_EMP_EXPI_MTH_CNT"}
										{name="YNG_CHLD_AGE_NO"}{name="MONTHLY_INCOME_AMT", formattedLength = "8",format="NLNUM18.5"} {name="NET_MONTHLY_INCOME_AMT", formattedLength = "8",format="NLNUM18.5"}
										{name="MONTHLY_EXPENSE_AMT",format="NLNUM18.5"}{name="FRGN_CNTRY_MTH_CNT"}{name="COUNTRY_CD"}}
										
			computedVarsprogram="CURR_ADD_MTH_CNT=intck('DTMONTH',CURRENT_ADDRESS_START_DT,APPLICATION_DT ); CURR_BSS_SNC_MTH_CNT=intck('DTMONTH',CURRENT_EMP_START_DT,APPLICATION_DT );
										CURR_EMP_TYP_MTH_CNT=intck('DTMONTH',CURRENT_EMP_TYPE_START_DT,APPLICATION_DT );CUSTOMER_EXIST_CNT=IF CUSTOMER_RK > 0 THEN 1 ELSE 0;
										ELD_CHLD_AGE_NO=intck('dtyear',ELDEST_CHILD_BIRTH_DT,APPLICATION_DT );TMP_EMP_EXPI_MTH_CNT=intck('dtmonth',APPLICATION_DT,TEMPORARY_EMPLOYMENT_END_DT );
										YNG_CHLD_AGE_NO=intck('dtyear',YOUNGEST_CHILD_BIRTH_DT,APPLICATION_DT );MONTHLY_INCOME_AMT=sum(MONTHLY_BUSINESS_INCOME_AMT, MONTHLY_SALARY_INCOME_AMT,MONTHLY_CHILD_ALLOW_AMT,MONTHLY_OTHER_INCOME_AMT,MONTHLY_RENTAL_INCOME_AMT, MONTHLY_REPLACEMENT_INCOME_AMT );NET_MONTHLY_INCOME_AMT=SUM(MONTHLY_SALARY_INCOME_AMT ,MONTHLY_BUSINESS_INCOME_AMT ,MONTHLY_RENTAL_INCOME_AMT,MONTHLY_REPLACEMENT_INCOME_AMT ,MONTHLY_OTHER_INCOME_AMT ,MONTHLY_CHILD_ALLOW_AMT ,-MONTHLY_INVESTMENT_AMT  ,-MONTHLY_ALIMONY_AMT , -MONTHLY_CHILD_SUPPORT_AMT ,-MONTHLY_HOUSING_AMT ,-MONTHLY_REPAYMENT_AMT ,-MONTHLY_REPAYMENT_OTHERS_AMT ,-MONTHLY_OTHER_CHARGE_AMT );
										MONTHLY_EXPENSE_AMT=sum( MONTHLY_CHILD_SUPPORT_AMT , MONTHLY_HOUSING_AMT ,MONTHLY_OTHER_CHARGE_AMT  , MONTHLY_INVESTMENT_AMT , 	MONTHLY_REPAYMENT_AMT, MONTHLY_RENTAL_AMT ,MONTHLY_REPAYMENT_OTHERS_AMT, MONTHLY_ALIMONY_AMT );
										FRGN_CNTRY_MTH_CNT=intck('DTMONTH',CURRENT_COUNTRY_START_DT,APPLICATION_DT );COUNTRY_CD=PRIMARY_CITIZENSHIP_COUNTRY_CD;"
			where= "APPLICANT_TYPE_CD IN (&NOM1_APP_TYPE_CD.) AND valid_end_dttm=&high_date."
				/* I18NOK:END */
		}
		}
		;
		QUIT;   
	%end;


	 /* New definition for PRI_CORP_APPLICANT_DIM */
	 
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.PRI_CORP_APPLICANT_DIM, DATA)) or %sysfunc(exist(bankcrfm.PRI_CORP_APPLICANT_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
			
		proc cas;
			table.view/PROMOTE=TRUE
				/* I18NOK:BEGIN */
			caslib="bankcrfm"
			name="PRI_CORP_APPLICANT_DIM"
			tables={{
			name="APPLICANT_DIM"
			caslib="bankcrfm"
			varlist={'APPLICANT_SK','APPLICANT_RK','APPLICATION_RK','CUSTOMER_RK','APPLICANT_ID','APPLICANT_TYPE_CD',
					'APPLICANT_NM','RELATIONSHIP_CD','APPLICANT_CITY_NM','APPLICANT_POSTAL_CD','APPLICANT_STATE_REGION_CD',
					'CURRENT_COUNTRY_START_DT','PENDING_LAWSUIT_FLG','LEGAL_JUDGEMENT_FLG','BANKRUPTCY_STATUS_CD',
					'BANKRUPTCY_FILED_DT','INTERNAL_CREDIT_RATING_CD','OTHER_CREDIT_CARDS_CNT','CURRENT_ADDRESS_START_DT',
					'BUSINESS_NATURE_CD','TAX_BRACKET_CD','TAX_ID','TAX_ID_TYPE_CD','ANNUAL_INCOME_AMT','MAINTENANCE_FLG',
					'LAST_APPLICATION_REFUSED_DT','VALID_START_DTTM','VALID_END_DTTM','PROCESSED_DTTM','OWNERSHIP_AMT','INDUSTRY_CD',
					'ORGANIZATION_NM','NUM_EMPLOYEES_CNT','OWNERSHIP_CNT','EXTERNAL_ORG_RK','OWNERSHIP_CD','PERCENT_OWNED',
					'NUM_OFFICES_CNT','BUSINESS_ESTABLISHED_DT','BUSINESS_COMMENCED_DT','APPLICATION_DT'}
			computedVars={{name="CURR_ADD_MTH_CNT"} {name="CUSTOMER_EXIST_CNT"}{name="COUNTRY_CD"}}
			computedVarsprogram="CURR_ADD_MTH_CNT=intck('DTMONTH',CURRENT_ADDRESS_START_DT,APPLICATION_DT ); CUSTOMER_EXIST_CNT=IF CUSTOMER_RK > 0 THEN 1 ELSE 0;
									COUNTRY_CD=PRIMARY_CITIZENSHIP_COUNTRY_CD;"
			where= "APPLICANT_TYPE_CD IN (&PRI_APP_TYPE_CD.) AND valid_end_dttm=&high_date." 
				/* I18NOK:END */
		}
		}
		;
		QUIT;
		
	%end;
			
	/* New definition for PRI_IND_APPLICANT_DIM */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.PRI_IND_APPLICANT_DIM, DATA)) or %sysfunc(exist(bankcrfm.PRI_IND_APPLICANT_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
				   
		proc cas;
			table.view/PROMOTE=TRUE
				/* I18NOK:BEGIN */
			caslib="bankcrfm"
			name="PRI_IND_APPLICANT_DIM"
			tables={{
			name="APPLICANT_DIM"
			caslib="bankcrfm" 	
			varlist={'APPLICANT_SK','APPLICANT_RK','APPLICATION_RK','CUSTOMER_RK','APPLICANT_ID',
						'APPLICANT_TYPE_CD','APPLICANT_BIRTH_DT','GENDER_CD','MARITAL_STATUS_CD',
						'RELATIONSHIP_CD','APPLICANT_CITY_NM','APPLICANT_POSTAL_CD','APPLICANT_STATE_REGION_CD',
						'APPLICANT_COUNTRY_CD','EDUCATION_LEVEL_CD','STD_OCCUPATION_CD','PRIMARY_CITIZENSHIP_COUNTRY_CD',
						'DEPENDENTS_CNT','PASSPORT_ISSUE_COUNTRY_CD','CURRENT_COUNTRY_START_DT','CHILDREN_CNT',
						'ELDEST_CHILD_BIRTH_DT','YOUNGEST_CHILD_BIRTH_DT','PENDING_LAWSUIT_FLG',
						'LEGAL_JUDGEMENT_FLG','BANKRUPTCY_STATUS_CD','BANKRUPTCY_FILED_DT',
						'FAMILY_MEMBER_ACCOUNT_CNT','HHOLD_INDIVIDUALS_CNT','INTERNAL_CREDIT_RATING_CD',
						'OTHER_CREDIT_CARDS_CNT','OWN_RESIDENCE_PROPERTY_FLG','OWN_AUTOMOBILE_FLG',
						'CURRENT_ADDRESS_START_DT','OWN_MOTORCYCLE_FLG','TIME_RESIDENCE_YEAR_CNT',
						'RESIDENCE_STATUS_CD','EMPLOYMENT_POSITION_STATUS_CD','MONTHS_AT_PREVIOUS_ADDRESS_CNT',
						'EMPLOYMENT_STATUS_CD','NO_OF_EMPLOYERS_CNT','TEMPORARY_EMPLOYMENT_END_DT',
						'EMPLOYMENT_YEARS_CNT','TOTAL_EMPLOYMENT_YEARS_CNT','BUSINESS_NATURE_CD',
						'CURRENT_EMP_START_DT','EMPLOYMENT_START_DT','TAX_BRACKET_CD','TAX_ID','TAX_ID_TYPE_CD',
						'MONTHLY_SALARY_INCOME_AMT','MONTHLY_BUSINESS_INCOME_AMT','MONTHLY_PRI_INCOME_SOURCE_CD',
						'MONTHLY_RENTAL_INCOME_AMT','MONTHLY_REPLACEMENT_INCOME_AMT','MONTHLY_OTHER_INCOME_AMT',
						'MONTHLY_CHILD_ALLOW_AMT','ANNUAL_INCOME_AMT','HHOLD_INCOME_AMT','MONTHLY_HOUSING_AMT',
						'MONTHLY_ALIMONY_AMT','MONTHLY_CHILD_SUPPORT_AMT','MONTHLY_REPAYMENT_AMT',
						'MONTHLY_REPAYMENT_OTHERS_AMT','MONTHLY_OTHER_CHARGE_AMT','MAINTENANCE_FLG',
						'MONTHLY_INVESTMENT_AMT','LIQUID_ASSETS_AMT','ASSET_OTHER_AMT','REAL_ESTATE_AMT',
						'TOTAL_ASSET_AMT','LIABILITY_REAL_ESTATE_AMT','LIABILITY_OTHER_AMT','TOTAL_LIABILITY_AMT',
						'NET_WORTH_AMT','LIQUID_NET_WORTH_AMT','LAST_APPLICATION_REFUSED_DT','MONTHLY_RENTAL_AMT',
						'INDUSTRY_CD','CURRENT_EMP_TYPE_START_DT','ANNUAL_SALARY_BUSINESS_AMT','SELF_EMPLOYMENT_FLG',
						'AGE','VALID_START_DTTM','VALID_END_DTTM','APPLICATION_DT','BUSINESS_ESTABLISHED_DT','BUSINESS_COMMENCED_DT'}
			 
			computedVars={{name="CURR_ADD_MTH_CNT"}{name="CURR_BSS_SNC_MTH_CNT"}{name="CURR_EMP_TYP_MTH_CNT"}{name="CUSTOMER_EXIST_CNT"}{name="ELD_CHLD_AGE_NO"}{name="TMP_EMP_EXPI_MTH_CNT"}
										{name="YNG_CHLD_AGE_NO"}{name="MONTHLY_INCOME_AMT", formattedLength = "8",format="NLNUM18.5"} {name="NET_MONTHLY_INCOME_AMT", formattedLength = "8",format="NLNUM18.5"}
										{name="MONTHLY_EXPENSE_AMT",format="NLNUM18.5"}{name="FRGN_CNTRY_MTH_CNT"}{name="COUNTRY_CD"}}
										
			computedVarsprogram="CURR_ADD_MTH_CNT=intck('DTMONTH',CURRENT_ADDRESS_START_DT,APPLICATION_DT ); CURR_BSS_SNC_MTH_CNT=intck('DTMONTH',CURRENT_EMP_START_DT,APPLICATION_DT );
										CURR_EMP_TYP_MTH_CNT=intck('DTMONTH',CURRENT_EMP_TYPE_START_DT,APPLICATION_DT );CUSTOMER_EXIST_CNT=IF CUSTOMER_RK > 0 THEN 1 ELSE 0;
										ELD_CHLD_AGE_NO=intck('dtyear',ELDEST_CHILD_BIRTH_DT,APPLICATION_DT );TMP_EMP_EXPI_MTH_CNT=intck('dtmonth',APPLICATION_DT,TEMPORARY_EMPLOYMENT_END_DT );
										YNG_CHLD_AGE_NO=intck('dtyear',YOUNGEST_CHILD_BIRTH_DT,APPLICATION_DT );MONTHLY_INCOME_AMT=sum(MONTHLY_BUSINESS_INCOME_AMT, MONTHLY_SALARY_INCOME_AMT,MONTHLY_CHILD_ALLOW_AMT,MONTHLY_OTHER_INCOME_AMT,MONTHLY_RENTAL_INCOME_AMT, MONTHLY_REPLACEMENT_INCOME_AMT );NET_MONTHLY_INCOME_AMT=SUM(MONTHLY_SALARY_INCOME_AMT ,MONTHLY_BUSINESS_INCOME_AMT ,MONTHLY_RENTAL_INCOME_AMT,MONTHLY_REPLACEMENT_INCOME_AMT ,MONTHLY_OTHER_INCOME_AMT ,MONTHLY_CHILD_ALLOW_AMT ,-MONTHLY_INVESTMENT_AMT  ,-MONTHLY_ALIMONY_AMT , -MONTHLY_CHILD_SUPPORT_AMT ,-MONTHLY_HOUSING_AMT ,-MONTHLY_REPAYMENT_AMT ,-MONTHLY_REPAYMENT_OTHERS_AMT ,-MONTHLY_OTHER_CHARGE_AMT );
										MONTHLY_EXPENSE_AMT=sum( MONTHLY_CHILD_SUPPORT_AMT , MONTHLY_HOUSING_AMT ,MONTHLY_OTHER_CHARGE_AMT  , MONTHLY_INVESTMENT_AMT , 	MONTHLY_REPAYMENT_AMT, MONTHLY_RENTAL_AMT ,MONTHLY_REPAYMENT_OTHERS_AMT, MONTHLY_ALIMONY_AMT );
										FRGN_CNTRY_MTH_CNT=intck('DTMONTH',CURRENT_COUNTRY_START_DT,APPLICATION_DT );COUNTRY_CD=PRIMARY_CITIZENSHIP_COUNTRY_CD;"
			where= "APPLICANT_TYPE_CD IN (&PRI_APP_TYPE_CD.) AND valid_end_dttm=&high_date."
				/* I18NOK:END */
		}
		}
		;
		QUIT; 
	%end;
			
	/* New definition for SEC_CORP_APPLICANT_DIM */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.SEC_CORP_APPLICANT_DIM, DATA)) or %sysfunc(exist(bankcrfm.SEC_CORP_APPLICANT_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
				   
		proc cas;
				table.view/PROMOTE=TRUE
					/* I18NOK:BEGIN */
				caslib="bankcrfm"
				name="SEC_CORP_APPLICANT_DIM"
				tables={{
				name="APPLICANT_DIM"
				caslib="bankcrfm"
				varlist={'APPLICANT_SK','APPLICANT_RK','APPLICATION_RK','CUSTOMER_RK','APPLICANT_ID','APPLICANT_TYPE_CD',
						'APPLICANT_NM','RELATIONSHIP_CD','APPLICANT_CITY_NM','APPLICANT_POSTAL_CD','APPLICANT_STATE_REGION_CD',
						'CURRENT_COUNTRY_START_DT','PENDING_LAWSUIT_FLG','LEGAL_JUDGEMENT_FLG','BANKRUPTCY_STATUS_CD',
						'BANKRUPTCY_FILED_DT','INTERNAL_CREDIT_RATING_CD','OTHER_CREDIT_CARDS_CNT','CURRENT_ADDRESS_START_DT',
						'BUSINESS_NATURE_CD','TAX_BRACKET_CD','TAX_ID','TAX_ID_TYPE_CD','ANNUAL_INCOME_AMT','MAINTENANCE_FLG',
						'LAST_APPLICATION_REFUSED_DT','VALID_START_DTTM','VALID_END_DTTM','PROCESSED_DTTM','OWNERSHIP_AMT','INDUSTRY_CD',
						'ORGANIZATION_NM','NUM_EMPLOYEES_CNT','OWNERSHIP_CNT','EXTERNAL_ORG_RK','OWNERSHIP_CD','PERCENT_OWNED',
						'NUM_OFFICES_CNT','BUSINESS_ESTABLISHED_DT','BUSINESS_COMMENCED_DT','APPLICATION_DT'}
				computedVars={{name="CURR_ADD_MTH_CNT"} {name="CUSTOMER_EXIST_CNT"}{name="COUNTRY_CD"}}
				computedVarsprogram="CURR_ADD_MTH_CNT=intck('DTMONTH',CURRENT_ADDRESS_START_DT,APPLICATION_DT ); CUSTOMER_EXIST_CNT=IF CUSTOMER_RK > 0 THEN 1 ELSE 0;
										COUNTRY_CD=PRIMARY_CITIZENSHIP_COUNTRY_CD;"
				where= "APPLICANT_TYPE_CD IN (&SEC_APP_TYPE_CD.) AND valid_end_dttm=&high_date." 
					/* I18NOK:END */
		}
		}
		;
		QUIT;
	%end;


	/* New definition for SEC_IND_APPLICANT_DIM */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.SEC_IND_APPLICANT_DIM, DATA)) or %sysfunc(exist(bankcrfm.SEC_IND_APPLICANT_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
				   
		proc cas;
			table.view/PROMOTE=TRUE
				/* I18NOK:BEGIN */
			caslib="bankcrfm"
			name="SEC_IND_APPLICANT_DIM"
			tables={{
			name="APPLICANT_DIM"
			caslib="bankcrfm" 	
			varlist={'APPLICANT_SK','APPLICANT_RK','APPLICATION_RK','CUSTOMER_RK','APPLICANT_ID',
						'APPLICANT_TYPE_CD','APPLICANT_BIRTH_DT','GENDER_CD','MARITAL_STATUS_CD',
						'RELATIONSHIP_CD','APPLICANT_CITY_NM','APPLICANT_POSTAL_CD','APPLICANT_STATE_REGION_CD',
						'APPLICANT_COUNTRY_CD','EDUCATION_LEVEL_CD','STD_OCCUPATION_CD',
						'DEPENDENTS_CNT','PASSPORT_ISSUE_COUNTRY_CD','CURRENT_COUNTRY_START_DT','CHILDREN_CNT',
						'ELDEST_CHILD_BIRTH_DT','YOUNGEST_CHILD_BIRTH_DT','PENDING_LAWSUIT_FLG',
						'LEGAL_JUDGEMENT_FLG','BANKRUPTCY_STATUS_CD','BANKRUPTCY_FILED_DT',
						'FAMILY_MEMBER_ACCOUNT_CNT','HHOLD_INDIVIDUALS_CNT','INTERNAL_CREDIT_RATING_CD',
						'OTHER_CREDIT_CARDS_CNT','OWN_RESIDENCE_PROPERTY_FLG','OWN_AUTOMOBILE_FLG',
						'CURRENT_ADDRESS_START_DT','OWN_MOTORCYCLE_FLG','TIME_RESIDENCE_YEAR_CNT',
						'RESIDENCE_STATUS_CD','EMPLOYMENT_POSITION_STATUS_CD','MONTHS_AT_PREVIOUS_ADDRESS_CNT',
						'EMPLOYMENT_STATUS_CD','NO_OF_EMPLOYERS_CNT','TEMPORARY_EMPLOYMENT_END_DT',
						'EMPLOYMENT_YEARS_CNT','TOTAL_EMPLOYMENT_YEARS_CNT','BUSINESS_NATURE_CD',
						'CURRENT_EMP_START_DT','EMPLOYMENT_START_DT','TAX_BRACKET_CD','TAX_ID','TAX_ID_TYPE_CD',
						'MONTHLY_SALARY_INCOME_AMT','MONTHLY_BUSINESS_INCOME_AMT','MONTHLY_PRI_INCOME_SOURCE_CD',
						'MONTHLY_RENTAL_INCOME_AMT','MONTHLY_REPLACEMENT_INCOME_AMT','MONTHLY_OTHER_INCOME_AMT',
						'MONTHLY_CHILD_ALLOW_AMT','ANNUAL_INCOME_AMT','HHOLD_INCOME_AMT','MONTHLY_HOUSING_AMT',
						'MONTHLY_ALIMONY_AMT','MONTHLY_CHILD_SUPPORT_AMT','MONTHLY_REPAYMENT_AMT',
						'MONTHLY_REPAYMENT_OTHERS_AMT','MONTHLY_OTHER_CHARGE_AMT','MAINTENANCE_FLG',
						'MONTHLY_INVESTMENT_AMT','LIQUID_ASSETS_AMT','ASSET_OTHER_AMT','REAL_ESTATE_AMT',
						'TOTAL_ASSET_AMT','LIABILITY_REAL_ESTATE_AMT','LIABILITY_OTHER_AMT','TOTAL_LIABILITY_AMT',
						'NET_WORTH_AMT','LIQUID_NET_WORTH_AMT','LAST_APPLICATION_REFUSED_DT','MONTHLY_RENTAL_AMT',
						'INDUSTRY_CD','CURRENT_EMP_TYPE_START_DT','ANNUAL_SALARY_BUSINESS_AMT','SELF_EMPLOYMENT_FLG',
						'AGE','VALID_START_DTTM','VALID_END_DTTM','APPLICATION_DT','BUSINESS_ESTABLISHED_DT','BUSINESS_COMMENCED_DT'}
			 
			computedVars={{name="CURR_ADD_MTH_CNT"}{name="CURR_BSS_SNC_MTH_CNT"}{name="CURR_EMP_TYP_MTH_CNT"}{name="CUSTOMER_EXIST_CNT"}{name="ELD_CHLD_AGE_NO"}{name="TMP_EMP_EXPI_MTH_CNT"}
						 {name="YNG_CHLD_AGE_NO"}{name="MONTHLY_INCOME_AMT", formattedLength = "8",format="NLNUM18.5"} {name="NET_MONTHLY_INCOME_AMT", formattedLength = "8",format="NLNUM18.5"}
						 {name="MONTHLY_EXPENSE_AMT",format="NLNUM18.5"}{name="FRGN_CNTRY_MTH_CNT"}{name="COUNTRY_CD"}}
										
			computedVarsprogram="CURR_ADD_MTH_CNT=intck('DTMONTH',CURRENT_ADDRESS_START_DT,APPLICATION_DT ); CURR_BSS_SNC_MTH_CNT=intck('DTMONTH',CURRENT_EMP_START_DT,APPLICATION_DT );
										CURR_EMP_TYP_MTH_CNT=intck('DTMONTH',CURRENT_EMP_TYPE_START_DT,APPLICATION_DT );CUSTOMER_EXIST_CNT=IF CUSTOMER_RK > 0 THEN 1 ELSE 0;
										ELD_CHLD_AGE_NO=intck('dtyear',ELDEST_CHILD_BIRTH_DT,APPLICATION_DT );TMP_EMP_EXPI_MTH_CNT=intck('dtmonth',APPLICATION_DT,TEMPORARY_EMPLOYMENT_END_DT );
										YNG_CHLD_AGE_NO=intck('dtyear',YOUNGEST_CHILD_BIRTH_DT,APPLICATION_DT );MONTHLY_INCOME_AMT=sum(MONTHLY_BUSINESS_INCOME_AMT, MONTHLY_SALARY_INCOME_AMT,MONTHLY_CHILD_ALLOW_AMT,MONTHLY_OTHER_INCOME_AMT,MONTHLY_RENTAL_INCOME_AMT, MONTHLY_REPLACEMENT_INCOME_AMT);NET_MONTHLY_INCOME_AMT=SUM(MONTHLY_SALARY_INCOME_AMT ,MONTHLY_BUSINESS_INCOME_AMT ,MONTHLY_RENTAL_INCOME_AMT,MONTHLY_REPLACEMENT_INCOME_AMT ,MONTHLY_OTHER_INCOME_AMT ,MONTHLY_CHILD_ALLOW_AMT ,-MONTHLY_INVESTMENT_AMT  ,-MONTHLY_ALIMONY_AMT , -MONTHLY_CHILD_SUPPORT_AMT ,-MONTHLY_HOUSING_AMT ,-MONTHLY_REPAYMENT_AMT ,-MONTHLY_REPAYMENT_OTHERS_AMT ,-MONTHLY_OTHER_CHARGE_AMT );
										MONTHLY_EXPENSE_AMT=sum( MONTHLY_CHILD_SUPPORT_AMT , MONTHLY_HOUSING_AMT ,MONTHLY_OTHER_CHARGE_AMT  , MONTHLY_INVESTMENT_AMT , 	MONTHLY_REPAYMENT_AMT, MONTHLY_RENTAL_AMT ,MONTHLY_REPAYMENT_OTHERS_AMT, MONTHLY_ALIMONY_AMT );
										FRGN_CNTRY_MTH_CNT=intck('DTMONTH',CURRENT_COUNTRY_START_DT,APPLICATION_DT );COUNTRY_CD=PRIMARY_CITIZENSHIP_COUNTRY_CD;"
			where= "APPLICANT_TYPE_CD IN (&SEC_APP_TYPE_CD.) AND valid_end_dttm=&high_date."
				/* I18NOK:END */
		}
		}
		;
		QUIT; 	
	%end;
	
	/* New definition for CORP_CUSTOMER_DIM */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.CORP_CUSTOMER_DIM, DATA)) or %sysfunc(exist(bankcrfm.CORP_CUSTOMER_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
				   
		proc cas;
				table.view/PROMOTE=TRUE
					/* I18NOK:BEGIN */
				caslib="bankcrfm"
				name="CORP_CUSTOMER_DIM"
				tables={{
				name="CUSTOMER_DIM"
				caslib="bankcrfm"
				vars={{name="CUSTOMER_RK",LABEL="CUSTOMER_RK"},{name ="CUSTOMER_SK",LABEL="CUSTOMER_SK", FORMAT="12."},
					 {name ="CUSTOMER_ID",LABEL="CUSTOMER_ID"},{name ="ORGANIZATION_TYPE_CD",LABEL="ORGANIZATION_TYPE_CD"},{name="CUSTOMER_CITY_NM",LABEL="CUSTOMER_CITY_NM"},
					 {name ="CUSTOMER_POSTAL_CD",LABEL="CUSTOMER_POSTAL_CD"},{name ="CUSTOMER_STATE_REGION_CD",LABEL="CUSTOMER_STATE_REGION_CD"}
					 {name ="CUSTOMER_COUNTRY_CD",LABEL="CUSTOMER_COUNTRY_CD"},{name ="CUSTOMER_TYPE_CD",LABEL="CUSTOMER_TYPE_CD"},
					 {name ="CUSTOMER_ACTIVE_CD",LABEL="CUSTOMER_ACTIVE_CD"},{name ="CUSTOMER_LIFECYCLE_CD",LABEL="CUSTOMER_LIFECYCLE_CD"},
					 {name ="BANKRUPTCY_STATUS_CD",LABEL="BANKRUPTCY_STATUS_CD"},{name ="PENDING_LAWSUIT_FLG",LABEL="PENDING_LAWSUIT_FLG"},
					 {name ="LEGAL_JUDGEMENT_FLG",LABEL="LEGAL_JUDGEMENT_FLG"},{name ="TAX_BRACKET_CD",LABEL="TAX_BRACKET_CD"},
					 {name ="TAX_ID",LABEL="TAX_ID"},{name ="TAX_ID_TYPE_CD",LABEL="TAX_ID_TYPE_CD"},{name ="FIRST_ACCOUNT_TYPE_CD",LABEL="FIRST_ACCOUNT_TYPE_CD"},
					 {name ="EVER_IN_COLLECTION_FLG",LABEL="EVER_IN_COLLECTION_FLG"},{name ="PREFERRED_CHANNEL_CD",LABEL="PREFERRED_CHANNEL_CD"},
					 {name ="OTHER_BANK_CLIENT_FLG",LABEL="OTHER_BANK_CLIENT_FLG"},{name ="OTHER_CREDIT_CARDS_CNT",LABEL="OTHER_CREDIT_CARDS_CNT"},
					 {name ="ANNUAL_INCOME_AMT",LABEL="ANNUAL_INCOME_AMT"},{name ="INTERNAL_CREDIT_RATING_CD",LABEL="INTERNAL_CREDIT_RATING_CD"},
					 {name ="PRIMARY_INTERNAL_ORG_RK",LABEL="PRIMARY_INTERNAL_ORG_RK", FORMAT="12."},{name ="INDUSTRY_CD",LABEL="INDUSTRY_CD"},
					 {name ="NUM_EMPLOYEES_CNT",LABEL="NUM_EMPLOYEES_CNT"},{name ="EXTERNAL_CREDIT_RATING1_CD",LABEL="EXTERNAL_CREDIT_RATING1_CD"},
					 {name ="NUM_OFFICES_CNT",LABEL="NUM_OFFICES_CNT"},{name ="EXTERNAL_CREDIT_RATING2_CD",LABEL="EXTERNAL_CREDIT_RATING2_CD"},
					 {name ="OWNERSHIP_CNT",LABEL="OWNERSHIP_CNT"},{name ="CUSTOMER_CLASS_CD",LABEL="CUSTOMER_CLASS_CD"},{name ="OWNERSHIP_CD",LABEL="OWNERSHIP_CD"},
					 {name ="BUSINESS_NATURE_CD",LABEL="BUSINESS_NATURE_CD"},{name="VALID_START_DTTM",LABEL="VALID_START_DTTM", FORMAT="NLDATM21."},
					 {name="VALID_END_DTTM",LABEL="VALID_END_DTTM", FORMAT="NLDATM21."},
					 {name="CURRENT_COUNTRY_START_DT",LABEL="CURRENT_COUNTRY_START_DT", FORMAT="NLDATM21."},{name="BANKRUPTCY_FILED_DT",LABEL="BANKRUPTCY_FILED_DT", FORMAT="NLDATM21."},
					 {name="INCORPORATION_DT",LABEL="INCORPORATION_DT", FORMAT="NLDATM21."},{name="BUSINESS_ESTABLISHED_DT",LABEL="BUSINESS_ESTABLISHED_DT", FORMAT="NLDATM21."},
					 {name="BUSINESS_COMMENCED_DT",LABEL="BUSINESS_COMMENCED_DT", FORMAT="NLDATM21."},{name="CURRENT_ADDRESS_START_DT",LABEL="CURRENT_ADDRESS_START_DT", FORMAT="NLDATM21."},
					 {name="FIRST_ACCOUNT_OPEN_DT",LABEL="FIRST_ACCOUNT_OPEN_DT", FORMAT="NLDATM21." }}
					 	/* I18NOK:END */
		}
		}
		;
		QUIT;
	%end;
	
	/* New definition for IND_ACCOUNT_DIM */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.IND_ACCOUNT_DIM, DATA)) or %sysfunc(exist(bankcrfm.IND_ACCOUNT_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
				   
		proc cas;
				table.view/PROMOTE=TRUE
					/* I18NOK:BEGIN */
				caslib="bankcrfm"
				name="IND_ACCOUNT_DIM"
				tables={{
				name="ACCOUNT_DIM"
				caslib="bankcrfm"
				vars={{name="ACCOUNT_RK",LABEL="ACCOUNT_RK"},
					 {name="ACCOUNT_ID",LABEL="ACCOUNT_ID",FORMAT="$32."},
					 {name="ACCOUNT_LIFECYCLE_STG_CD",LABEL="ACCOUNT_LIFECYCLE_STG_CD",FORMAT="$3."},
					 {name="ACCOUNT_RENEWAL_CNT",LABEL="ACCOUNT_RENEWAL_CNT",FORMAT="BEST12."},
					 {name="ACCOUNT_RENEWAL_TYPE_CD",LABEL="ACCOUNT_RENEWAL_TYPE_CD",FORMAT="$3."},
					 {name="ACCOUNT_SK",LABEL="ACCOUNT_SK",FORMAT="BEST12."},
					 {name="ACCOUNT_STATUS_CD",LABEL="ACCOUNT_STATUS_CD", FORMAT="$3."},
					 {name="ACCOUNT_SUB_TYPE_CD",LABEL="ACCOUNT_SUB_TYPE_CD", FORMAT="$3."},
					 {name="ACCOUNT_SUB_TYPE_DESC" , LABEL="ACCOUNT_SUB_TYPE_DESC" ,FORMAT="$100."},
					 {name="ACCOUNT_TYPE_CD" , LABEL="ACCOUNT_TYPE_CD" ,FORMAT="$3."},
					 {name="ACCOUNT_TYPE_DESC" , LABEL="ACCOUNT_TYPE_DESC", FORMAT="$100."},
					 {name="ACCT_HOLDERS_CNT" , LABEL="ACCT_HOLDERS_CNT" ,FORMAT="BEST12."},
					 {name="ACTUAL_ACCOUNT_OPENING_AMT" , LABEL="ACTUAL_ACCOUNT_OPENING_AMT" ,FORMAT="NLNUM18.5"},
					 {name="ACTUAL_ADVANCE_AMT" , LABEL="ACTUAL_ADVANCE_AMT", FORMAT="NLNUM18.5"},
					 {name="ADDITIONAL_CARD_CNT" , LABEL="ADDITIONAL_CARD_CNT" ,FORMAT="BEST12."},
					 {name="ALLOW_OVERDRAFT_FLG" , LABEL="ALLOW_OVERDRAFT_FLG", FORMAT="$1."},
					 {name="ANNUAL_FEES_AMT" , LABEL="ANNUAL_FEES_AMT", FORMAT="NLNUM18.5"},
					 {name="APPLICATION_RK" , LABEL="APPLICATION_RK" ,FORMAT="BEST12."},
					 {name="APPROVED_AMT" , LABEL="APPROVED_AMT", FORMAT="NLNUM18.5"},
					 {name="BROKER_FLG" , LABEL="BROKER_FLG", FORMAT="$1."},
					 {name="CALLABLE_FACILITY_USED_FLG" , LABEL="CALLABLE_FACILITY_USED_FLG", FORMAT="$1."},
					 {name="CASH_BACK_FLG" , LABEL="CASH_BACK_FLG", FORMAT="$1."},
					 {name="CASH_BACK_PCT" , LABEL="CASH_BACK_PCT", FORMAT="NLNUM9.4"},
					 {name="CASH_LIMIT_AMT" , LABEL="CASH_LIMIT_AMT", FORMAT="NLNUM18.5"},
					 {name="CHARGE_OFF_AMT" , LABEL="CHARGE_OFF_AMT", FORMAT="NLNUM18.5"},
					 {name="CHARGE_OFF_FLG" , LABEL="CHARGE_OFF_FLG", FORMAT="$1."},
					 {name="CHECKING_MAIN_FLG" , LABEL="CHECKING_MAIN_FLG", FORMAT="$1."},
					 {name="CHECK_BOOK_FLG" , LABEL="CHECK_BOOK_FLG", FORMAT="$1."},
					 {name="CLOSE_REASON_CD" , LABEL="CLOSE_REASON_CD", FORMAT="$3."},
					 {name="CLOSING_COST_AMT" , LABEL="CLOSING_COST_AMT", FORMAT="NLNUM18.5"},
					 {name="COLLATERAL_AMT" , LABEL="COLLATERAL_AMT", FORMAT="NLNUM18.5"},
					 {name="COLLATERAL_CD" , LABEL="COLLATERAL_CD", FORMAT="$3."},
					 {name="COLLECTIONS_STATUS_CD" , LABEL="COLLECTIONS_STATUS_CD", FORMAT="$3."},
					 {name="CREATED_BY" , LABEL="CREATED_BY", FORMAT="$20."},
					 {name="CREATED_DTTM" , LABEL="CREATED_DTTM", FORMAT="NLDATM21."},
					 {name="CREDIT_FACILITY_RK" , LABEL="CREDIT_FACILITY_RK", FORMAT="BEST12."},
					 {name="CURRENCY_CD" , LABEL="CURRENCY_CD", FORMAT="$3."},
					 {name="CURRENT_LIMIT_AMT" , LABEL="CURRENT_LIMIT_AMT", FORMAT="NLNUM18.5"},
					 {name="DIRECT_DEBITS_CNT" , LABEL="DIRECT_DEBITS_CNT", FORMAT="BEST12."},
					 {name="DISBURSEMENT_TYPE_CD" , LABEL="DISBURSEMENT_TYPE_CD", FORMAT="$3."},
					 {name="DO_NOT_CONTACT_FLG" , LABEL="DO_NOT_CONTACT_FLG", FORMAT="$1."},
					 {name="DOCUMENTATION_TYPE_CD" , LABEL="DOCUMENTATION_TYPE_CD", FORMAT="$3."},
					 {name="DOWNPAYMENT_AMT" , LABEL="DOWNPAYMENT_AMT" ,FORMAT="NLNUM18.5"},
					 {name="FINANCE_CHARGE_FLG" , LABEL="FINANCE_CHARGE_FLG", FORMAT="$1."},
					 {name="GRACE_PERIOD_DAYS_CNT" , LABEL="GRACE_PERIOD_DAYS_CNT", FORMAT="BEST12."},
					 {name="GUARANTEE_AMT" , LABEL="GUARANTEE_AMT", FORMAT="NLNUM18.5"},
					 {name="GUARANTORS_CNT" , LABEL="GUARANTORS_CNT", FORMAT="BEST12."},
					 {name="HOME_STATUS_CD" , LABEL="HOME_STATUS_CD", FORMAT="$3."},
					 {name="HONEYMOON_PERIOD_FLG" , LABEL="HONEYMOON_PERIOD_FLG", FORMAT="$1."},
					 {name="IMPROVEMENTS_ALLOCATION_AMT" , LABEL="IMPROVEMENTS_ALLOCATION_AMT", FORMAT="NLNUM18.5"},
					 {name="INDIVIDUAL_ORGANIZATION_CD" , LABEL="INDIVIDUAL_ORGANIZATION_CD", FORMAT="$3."},
					 {name="INITIAL_LIMIT_AMT" , LABEL="INITIAL_LIMIT_AMT", FORMAT="NLNUM18.5"},
					 {name="INTEREST_PAYOUT_FLG" , LABEL="INTEREST_PAYOUT_FLG", FORMAT="$1."},
					 {name="LIEN_INDICATOR_FLG" , LABEL="LIEN_INDICATOR_FLG", FORMAT="$1."},
					 {name="LINKED_ACCOUNT_FLG" , LABEL="LINKED_ACCOUNT_FLG", FORMAT="$1."},
					 {name="LINKED_DEP_ACCT_FLG" , LABEL="LINKED_DEP_ACCT_FLG", FORMAT="$1."},
					 {name="MIN_ACCOUNT_OPENING_AMT" , LABEL="MIN_ACCOUNT_OPENING_AMT" ,FORMAT="NLNUM18.5"},
					 {name="MIN_PAYMENT_FLG" , LABEL="MIN_PAYMENT_FLG" ,FORMAT="$1."},
					 {name="MIN_REDRAW_AMT" , LABEL="MIN_REDRAW_AMT" ,FORMAT="NLNUM18.5"},
					 {name="MORTGAGE_INSURED_FLG" , LABEL="MORTGAGE_INSURED_FLG", FORMAT="$1."},
					 {name="MORTGAGE_OPEN_TO_BUY_AMT" , LABEL="MORTGAGE_OPEN_TO_BUY_AMT" ,FORMAT="NLNUM18.5"},
					 {name="MULTI_RATE_FLG" , LABEL="MULTI_RATE_FLG", FORMAT="$1."},
					 {name="NOMINEES_CNT" , LABEL="NOMINEES_CNT", FORMAT="BEST12."},
					 {name="OFFSET_ACCOUNT_FLG" , LABEL="OFFSET_ACCOUNT_FLG", FORMAT="$1."},
					 {name="OPENING_CAMPAIGN_CD" , LABEL="OPENING_CAMPAIGN_CD", FORMAT="$30."},
					 {name="OPENING_CHANNEL_CD" , LABEL="OPENING_CHANNEL_CD", FORMAT="$3."},
					 {name="OVERDRAFT_LIMIT_AMT" , LABEL="OVERDRAFT_LIMIT_AMT" ,FORMAT="NLNUM18.5"},
					 {name="OWNED_BY_INTERNAL_ORG_RK" , LABEL="OWNED_BY_INTERNAL_ORG_RK", FORMAT="BEST12."},
					 {name="PAYMENT_DAY_OF_MONTH" , LABEL="PAYMENT_DAY_OF_MONTH" ,FORMAT="BEST12."},
					 {name="PAYMENT_FREQUENCY_CD" , LABEL="PAYMENT_FREQUENCY_CD", FORMAT="$3."},
					 {name="PAYMENT_INSURED_FLG" , LABEL="PAYMENT_INSURED_FLG", FORMAT="$1."},
					 {name="PAYMENT_MODE_CD" , LABEL="PAYMENT_MODE_CD", FORMAT="$3."},
					 {name="PORTABILITY_FLG" , LABEL="PORTABILITY_FLG", FORMAT="$1."},
					 {name="PRIMARY_CUSTOMER_RK" , LABEL="PRIMARY_CUSTOMER_RK", FORMAT="BEST12."},
					 {name="PRIMARY_PRODUCT_RK" , LABEL="PRIMARY_PRODUCT_RK", FORMAT="BEST12."},
					 {name="PROCESSED_DTTM" , LABEL="PROCESSED_DTTM", FORMAT="NLDATM21."},
					 {name="PROVISIONAL_CREDIT_LIMIT_AMT" , LABEL="PROVISIONAL_CREDIT_LIMIT_AMT", FORMAT="NLNUM18.5"},
					 {name="PURPOSE_CD" , LABEL="PURPOSE_CD", FORMAT="$3."},
					 {name="REDRAW_FLG" , LABEL="REDRAW_FLG", FORMAT="$1."},
					 {name="REGULAR_PERIODIC_PAYMENT_AMT" , LABEL="REGULAR_PERIODIC_PAYMENT_AMT", FORMAT="NLNUM18.5"},
					 {name="REPAYMENT_HOLIDAY_FLG" , LABEL="REPAYMENT_HOLIDAY_FLG" ,FORMAT="$1."},
					 {name="REQUIRED_MIN_BALANCE_AMT" , LABEL="REQUIRED_MIN_BALANCE_AMT", FORMAT="NLNUM18.5"},
					 {name="SAFE_DEPOSIT_FLG" , LABEL="SAFE_DEPOSIT_FLG" ,FORMAT="$1."},
					 {name="SECURITY_CD" , LABEL="SECURITY_CD" ,FORMAT="$3."},
					 {name="SECURITY_DEPOSIT_AMT" , LABEL="SECURITY_DEPOSIT_AMT" ,FORMAT="NLNUM18.5"},
					 {name="SECURITY_DEPOSIT_REFUND_AMT" , LABEL="SECURITY_DEPOSIT_REFUND_AMT" ,FORMAT="NLNUM18.5"},
					 {name="SENIORITY_CD" , LABEL="SENIORITY_CD" ,FORMAT="$3."},
					 {name="SIGNATORIES_CNT" , LABEL="SIGNATORIES_CNT", FORMAT="BEST12."},
					 {name="SOURCE_SYSTEM_CD" , LABEL="SOURCE_SYSTEM_CD", FORMAT="$3."},
					 {name="SPECIAL_INTEREST_RT" , LABEL="SPECIAL_INTEREST_RT", FORMAT="NLNUM9.4"},
					 {name="SPECIAL_RATE_TYPE_CD" , LABEL="SPECIAL_RATE_TYPE_CD", FORMAT="$3."},
					 {name="SPLIT_LOAN_FLG" , LABEL="SPLIT_LOAN_FLG" FORMAT="$1."},
					 {name="STANDING_ORDERS_CNT" , LABEL="STANDING_ORDERS_CNT", FORMAT="BEST12."},
					 {name="STATEMENT_FREQUENCY_CD" , LABEL="STATEMENT_FREQUENCY_CD", FORMAT="$3."},
					 {name="STEP_UP_FACILITY_USED_FLG" , LABEL="STEP_UP_FACILITY_USED_FLG" ,FORMAT="$1."},
					 {name="VALID_END_DTTM" , LABEL="VALID_END_DTTM" ,FORMAT="NLDATM21."},
					 {name="VALID_START_DTTM" , LABEL="VALID_START_DTTM" ,FORMAT="NLDATM21."},
					 {name="CARD_EXPIRATION_DT" , LABEL="CARD_EXPIRATION_DT", FORMAT="NLDATM21."},
					 {name="CARD_ISSUE_DT" , LABEL="CARD_ISSUE_DT", FORMAT="NLDATM21."},
					 {name="CARD_REISSUE_DT" , LABEL="CARD_REISSUE_DT", FORMAT="NLDATM21."},
					 {name="CHARGE_OFF_DT" , LABEL="CHARGE_OFF_DT", FORMAT="NLDATM21."},
					 {name="CLOSE_DT" , LABEL="CLOSE_DT", FORMAT="NLDATM21."},
					 {name="CURRENT_LIMIT_DT" , LABEL="CURRENT_LIMIT_DT", FORMAT="NLDATM21."},
					 {name="HONEYMOON_END_DT" , LABEL="HONEYMOON_END_DT" ,FORMAT="NLDATM21."},
					 {name="HONEYMOON_START_DT" , LABEL="HONEYMOON_START_DT" ,FORMAT="NLDATM21."},
					 {name="OVERDRAFT_LIMIT_DT" , LABEL="OVERDRAFT_LIMIT_DT" ,FORMAT="NLDATM21."},
					 {name="OPEN_DT" , LABEL="OPEN_DT" ,FORMAT="NLDATM21."},
					 {name="PROV_CREDIT_LIMIT_CLOSE_DT" , LABEL="PROV_CREDIT_LIMIT_CLOSE_DT" ,FORMAT="NLDATM21."},
					 {name="PROV_CREDIT_LIMIT_OPEN_DT" , LABEL="PROV_CREDIT_LIMIT_OPEN_DT", FORMAT="NLDATM21."},
					 {name="REGISTER_ONLINE_DT" , LABEL="REGISTER_ONLINE_DT", FORMAT="NLDATM21."},
					 {name="REPAYMENT_HOLIDAY_END_DT" , LABEL="REPAYMENT_HOLIDAY_END_DT" ,FORMAT="NLDATM21."},
					 {name="REPAYMENT_HOLIDAY_START_DT" , LABEL="REPAYMENT_HOLIDAY_START_DT", FORMAT="NLDATM21."},
					 {name="SPECIAL_RATE_END_DT" , LABEL="SPECIAL_RATE_END_DT", FORMAT="NLDATM21."},
					 {name="SPECIAL_RATE_START_DT" , LABEL="SPECIAL_RATE_START_DT", FORMAT="NLDATM21."}}
			computedVars={{name="ACCOUNT_HIERARCHY_CD"}{name="CUSTOMER_RK"}}
			computedVarsprogram="ACCOUNT_HIERARCHY_CD=IF (ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND ACCOUNT_SUB_TYPE_CD IN (&CHK_ACCOUNT_SUB_TYPE)) THEN &ACC_HIER_CHK 
					 ELSE IF (ACCOUNT_TYPE_CD IN (&CCD_ACCOUNT_TYPE)) THEN &ACC_HIER_CCD 
					 ELSE IF (ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND ACCOUNT_SUB_TYPE_CD IN (&SAV_ACCOUNT_SUB_TYPE,&CHK_ACCOUNT_SUB_TYPE) AND ALLOW_OVERDRAFT_FLG IN (&CHECK_FLAG_TRUE)) THEN &ACC_HIER_OD
					 ELSE IF (ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  ACCOUNT_SUB_TYPE_CD IN (&RDP_ACCOUNT_SUB_TYPE)) THEN &ACC_HIER_RD
					 ELSE IF (ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  ACCOUNT_SUB_TYPE_CD IN  (&SAV_ACCOUNT_SUB_TYPE)) THEN &ACC_HIER_SAV
					 ELSE IF (ACCOUNT_TYPE_CD IN (&MTG_ACCOUNT_TYPE, &LON_ACCOUNT_TYPE) AND COLLATERAL_CD ne '') THEN &ACC_HIER_SLN  
					 ELSE IF (ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  ACCOUNT_SUB_TYPE_CD  IN (&TDP_ACCOUNT_SUB_TYPE)) THEN &ACC_HIER_TD 
					 ELSE IF (ACCOUNT_TYPE_CD IN (&LON_ACCOUNT_TYPE) AND (COLLATERAL_CD eq '' )) THEN &ACC_HIER_ULN
					 ELSE ' ';CUSTOMER_RK=PRIMARY_CUSTOMER_RK;"
					 	/* I18NOK:END */
		}
	    }
		;
		QUIT;
	%end;
	
	/* New definition for IND_CUSTOMER_DIM */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.IND_CUSTOMER_DIM, DATA)) or %sysfunc(exist(bankcrfm.IND_CUSTOMER_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
				   
		proc cas;
				table.view/PROMOTE=TRUE
					/* I18NOK:BEGIN */
				caslib="bankcrfm"
				name="IND_CUSTOMER_DIM"
				tables={{
				name="CUSTOMER_DIM"
				caslib="bankcrfm"
				vars={{name="CUSTOMER_RK",LABEL="CUSTOMER_RK"},
					 {name="ANNUAL_INCOME_AMT",LABEL="ANNUAL_INCOME_AMT",FORMAT="NLNUM18.5"},
					 {name="ASSET_OTHER_AMT" LABEL="ASSET_OTHER_AMT" ,FORMAT="NLNUM18.5"},
					 {name="BANKRUPTCY_STATUS_CD" , LABEL="BANKRUPTCY_STATUS_CD" ,FORMAT="$3."},
					 {name="BILL_PAY_SERVICE_FLG" , LABEL="BILL_PAY_SERVICE_FLG" ,FORMAT="$1."},
					 {name="BIRTH_DT" , LABEL="BIRTH_DT" ,FORMAT="NLDATE10."},
					 {name="BUSINESS_NATURE_CD" , LABEL="BUSINESS_NATURE_CD" ,FORMAT="$3."},
					 {name="CHILDREN_CNT" , LABEL="CHILDREN_CNT" ,FORMAT="BEST12."},
					 {name="CUSTOMER_COUNTRY_CD" , LABEL="CUSTOMER_COUNTRY_CD" ,FORMAT="$3."},
					 {name="CUSTOMER_ACTIVE_CD" , LABEL="CUSTOMER_ACTIVE_CD" ,FORMAT="$3."},
					 {name="CUSTOMER_CITY_NM" , LABEL="CUSTOMER_CITY_NM" ,FORMAT="$100."},
					 {name="CUSTOMER_CLASS_CD" , LABEL="CUSTOMER_CLASS_CD" ,FORMAT="$3."},
					 {name="CUSTOMER_ID" , LABEL="CUSTOMER_ID" ,FORMAT="$32."},
					 {name="CUSTOMER_LIFECYCLE_CD" , LABEL="CUSTOMER_LIFECYCLE_CD" ,FORMAT="$3."},
					 {name="CUSTOMER_POSTAL_CD" , LABEL="CUSTOMER_POSTAL_CD" ,FORMAT="$20."},
					 {name="CUSTOMER_SK" , LABEL="CUSTOMER_SK" ,FORMAT="BEST12."},
					 {name="CUSTOMER_STATE_REGION_CD" , LABEL="CUSTOMER_STATE_REGION_CD" ,FORMAT="$4."},
					 {name="CUSTOMER_TYPE_CD" , LABEL="CUSTOMER_TYPE_CD" ,FORMAT="$3."},
					 {name="EDUCATION_LEVEL_CD" , LABEL="EDUCATION_LEVEL_CD" ,FORMAT="$4."},
					 {name="EMPLOYEE_FLG" , LABEL="EMPLOYEE_FLG" ,FORMAT="$1."},
					 {name="EMPLOYERS_CNT" , LABEL="EMPLOYERS_CNT" ,FORMAT="BEST12."},
					 {name="EMPLOYMENT_POSITION_STATUS_CD" , LABEL="EMPLOYMENT_POSITION_STATUS_CD" ,FORMAT="$3."},
					 {name="EMPLOYMENT_STATUS_CD" , LABEL="EMPLOYMENT_STATUS_CD" ,FORMAT="$3."},
					 {name="EMPLOYMENT_YEARS_CNT" , LABEL="EMPLOYMENT_YEARS_CNT" ,FORMAT="BEST12."},
					 {name="EVER_IN_COLLECTION_FLG" , LABEL="EVER_IN_COLLECTION_FLG" ,FORMAT="$1."},
					 {name="EXTERNAL_CREDIT_RATING1_CD" , LABEL="EXTERNAL_CREDIT_RATING1_CD" ,FORMAT="$4."},
					 {name="EXTERNAL_CREDIT_RATING2_CD" , LABEL="EXTERNAL_CREDIT_RATING2_CD" ,FORMAT="$4."},
					 {name="FIRST_ACCOUNT_TYPE_CD" , LABEL="FIRST_ACCOUNT_TYPE_CD" ,FORMAT="$3."},
					 {name="GENDER_CD" , LABEL="GENDER_CD" ,FORMAT="$3."},
					 {name="HHOLD_RK" , LABEL="HHOLD_RK" ,FORMAT="BEST12."},
					 {name="INCOME_CATEGORY_CD" , LABEL="INCOME_CATEGORY_CD" ,FORMAT="$3."},
					 {name="INDUSTRY_CD" , LABEL="INDUSTRY_CD" ,FORMAT="$4."},
					 {name="INTERNAL_CREDIT_RATING_CD" , LABEL="INTERNAL_CREDIT_RATING_CD" ,FORMAT="$20."},
					 {name="LEGAL_JUDGEMENT_FLG" , LABEL="LEGAL_JUDGEMENT_FLG" ,FORMAT="BEST12."},
					 {name="LIABILITY_OTHER_AMT" , LABEL="LIABILITY_OTHER_AMT" ,FORMAT="NLNUM18.5"},
					 {name="LIABILITY_REAL_ESTATE_AMT" , LABEL="LIABILITY_REAL_ESTATE_AMT" ,FORMAT="NLNUM18.5"},
					 {name="LIQUID_ASSETS_AMT" , LABEL="LIQUID_ASSETS_AMT" ,FORMAT="NLNUM18.5"},
					 {name="LIQUID_NET_WORTH_AMT" , LABEL="LIQUID_NET_WORTH_AMT" ,FORMAT="NLNUM18.5"},
					 {name="MARITAL_STATUS_CD" , LABEL="MARITAL_STATUS_CD" ,FORMAT="$3."},
					 {name="MONTHLY_ALIMONY_AMT" , LABEL="MONTHLY_ALIMONY_AMT" ,FORMAT="BEST12."},
					 {name="MONTHLY_BUSINESS_INCOME_AMT" , LABEL="MONTHLY_BUSINESS_INCOME_AMT" ,FORMAT="BEST12."},
					 {name="MONTHLY_CHILD_ALLOW_AMT" , LABEL="MONTHLY_CHILD_ALLOW_AMT" ,FORMAT="BEST12."},
					 {name="MONTHLY_CHILD_SUPPORT_AMT" , LABEL="MONTHLY_CHILD_SUPPORT_AMT" ,FORMAT="BEST12."},
					 {name="MONTHLY_INVESTMENT_AMT" , LABEL="MONTHLY_INVESTMENT_AMT" ,FORMAT="NLNUM18.5"},
					 {name="MONTHLY_OTHER_CHARGE_AMT" , LABEL="MONTHLY_OTHER_CHARGE_AMT" ,FORMAT="BEST12."},
					 {name="MONTHLY_OTHER_INCOME_AMT" , LABEL="MONTHLY_OTHER_INCOME_AMT" ,FORMAT="BEST12."},
					 {name="MONTHLY_PRI_INCOME_SOURCE_CD" , LABEL="MONTHLY_PRI_INCOME_SOURCE_CD" ,FORMAT="$4."},
					 {name="MONTHLY_RENTAL_AMT" , LABEL="MONTHLY_RENTAL_AMT" ,FORMAT="BEST12."},
					 {name="MONTHLY_RENTAL_INCOME_AMT" , LABEL="MONTHLY_RENTAL_INCOME_AMT" ,FORMAT="BEST12."},
					 {name="MONTHLY_REPAYMENT_AMT" , LABEL="MONTHLY_REPAYMENT_AMT" ,FORMAT="BEST12."},
					 {name="MONTHLY_REPAYMENT_OTHERS_AMT" , LABEL="MONTHLY_REPAYMENT_OTHERS_AMT" ,FORMAT="BEST12."},
					 {name="MONTHLY_REPLACEMENT_INCOME_AMT" , LABEL="MONTHLY_REPLACEMENT_INCOME_AMT" ,FORMAT="BEST12."},
					 {name="MONTHLY_SALARY_INCOME_AMT" , LABEL="MONTHLY_SALARY_INCOME_AMT" ,FORMAT="BEST12."},
					 {name="NET_WORTH_AMT" , LABEL="NET_WORTH_AMT" ,FORMAT="NLNUM18.5"},
					 {name="ORGANIZATION_TYPE_CD" , LABEL="ORGANIZATION_TYPE_CD" ,FORMAT="$3."},
					 {name="OTHER_BANK_CLIENT_FLG" , LABEL="OTHER_BANK_CLIENT_FLG" ,FORMAT="BEST12."},
					 {name="OTHER_CREDIT_CARDS_CNT" , LABEL="OTHER_CREDIT_CARDS_CNT" ,FORMAT="BEST12."},
					 {name="OWN_AUTOMOBILE_FLG" , LABEL="OWN_AUTOMOBILE_FLG" ,FORMAT="BEST12."},
					 {name="OWN_MOTORCYCLE_FLG" , LABEL="OWN_MOTORCYCLE_FLG" ,FORMAT="BEST12."},
					 {name="OWN_RESIDENCE_PROPERTY_FLG" , LABEL="OWN_RESIDENCE_PROPERTY_FLG" ,FORMAT="BEST12."},
					 {name="PASSPORT_ISSUE_COUNTRY_CD" , LABEL="PASSPORT_ISSUE_COUNTRY_CD" ,FORMAT="$3."},
					 {name="PENDING_LAWSUIT_FLG" , LABEL="PENDING_LAWSUIT_FLG" ,FORMAT="BEST12."},
					 {name="PREFERRED_CHANNEL_CD" , LABEL="PREFERRED_CHANNEL_CD" ,FORMAT="$3."},
					 {name="PRIMARY_CITIZENSHIP_COUNTRY_CD" , LABEL="PRIMARY_CITIZENSHIP_COUNTRY_CD" ,FORMAT="$3."},
					 {name="PRIMARY_INTERNAL_ORG_RK" , LABEL="PRIMARY_INTERNAL_ORG_RK" ,FORMAT="BEST12."},
					 {name="PROCESSED_DTTM" , LABEL="PROCESSED_DTTM" ,FORMAT="NLDATM21."},
					 {name="REAL_ESTATE_AMT" , LABEL="REAL_ESTATE_AMT" ,FORMAT="NLNUM18.5"},
					 {name="RESIDENCE_STATUS_CD" , LABEL="RESIDENCE_STATUS_CD" ,FORMAT="$3."},
					 {name="SECNDRY_CITIZENSHIP_COUNTRY_CD" , LABEL="SECNDRY_CITIZENSHIP_COUNTRY_CD" ,FORMAT="$3."},
					 {name="SELF_EMPLOYMENT_FLG" , LABEL="SELF_EMPLOYMENT_FLG" ,FORMAT="BEST12."},
					 {name="STD_OCCUPATION_CD" , LABEL="STD_OCCUPATION_CD" ,FORMAT="$3."},
					 {name="TAX_BRACKET_CD" , LABEL="TAX_BRACKET_CD" ,FORMAT="$3."},
					 {name="TAX_ID" , LABEL="TAX_ID" ,FORMAT="$32."},
					 {name="TAX_ID_TYPE_CD" , LABEL="TAX_ID_TYPE_CD" ,FORMAT="$3."},
					 {name="TOTAL_ASSET_AMT" , LABEL="TOTAL_ASSET_AMT" ,FORMAT="NLNUM18.5"},
					 {name="TOTAL_DEPENDENTS_CNT" , LABEL="TOTAL_DEPENDENTS_CNT" ,FORMAT="BEST12."},
					 {name="TOTAL_EMPLOYMENT_YEARS_CNT" , LABEL="TOTAL_EMPLOYMENT_YEARS_CNT" ,FORMAT="BEST12."},
					 {name="TOTAL_LIABILITY_AMT" , LABEL="TOTAL_LIABILITY_AMT" ,FORMAT="NLNUM18.5"},
					 {name="VALID_END_DTTM" , LABEL="VALID_END_DTTM" ,FORMAT="NLDATM21."},
					 {name="VALID_START_DTTM" , LABEL="VALID_START_DTTM" ,FORMAT="NLDATM21."},
					 {name="BANKRUPTCY_FILED_DT" , LABEL="BANKRUPTCY_FILED_DT" ,FORMAT="NLDATM21."},
					 {name="CURRENT_ADDRESS_START_DT" , LABEL="CURRENT_ADDRESS_START_DT" ,FORMAT="NLDATM21."},
					 {name="CURRENT_COUNTRY_START_DT" , LABEL="CURRENT_COUNTRY_START_DT" ,FORMAT="NLDATM21."},
					 {name="CURRENT_EMP_START_DT" , LABEL="CURRENT_EMP_START_DT" ,FORMAT="NLDATM21."},
					 {name="ELDEST_CHILD_BIRTH_DT" , LABEL="ELDEST_CHILD_BIRTH_DT" ,FORMAT="NLDATM21."},
					 {name="EMPLOYMENT_START_DT" , LABEL="EMPLOYMENT_START_DT" ,FORMAT="NLDATM21."},
					 {name="FIRST_ACCOUNT_OPEN_DT" , LABEL="FIRST_ACCOUNT_OPEN_DT" ,FORMAT="NLDATM21."},
					 {name="OCCUPATION_START_DT" , LABEL="OCCUPATION_START_DT" ,FORMAT="NLDATM21."},
					 {name="RESIDENCE_STATUS_DT" , LABEL="RESIDENCE_STATUS_DT" ,FORMAT="NLDATM21."},
					 {name="TEMPORARY_EMPLOYMENT_END_DT" , LABEL="TEMPORARY_EMPLOYMENT_END_DT" ,FORMAT="NLDATM21."},
					 {name="YOUNGEST_CHILD_BIRTH_DT" , LABEL="YOUNGEST_CHILD_BIRTH_DT" ,FORMAT="NLDATM21."}}
			computedVars={{name="MONTHLY_INCOME_AMT"}{name="NET_MONTHLY_INCOME_AMT"}{name="CUSTOMER_RK2"}}
			computedVarsprogram="MONTHLY_INCOME_AMT=( COALESCE(MONTHLY_SALARY_INCOME_AMT,0) + COALESCE(MONTHLY_BUSINESS_INCOME_AMT,0));
								CUSTOMER_RK2=CUSTOMER_RK;
								NET_MONTHLY_INCOME_AMT=( COALESCE(MONTHLY_SALARY_INCOME_AMT,0) + COALESCE(MONTHLY_BUSINESS_INCOME_AMT,0) + 
					COALESCE(MONTHLY_RENTAL_INCOME_AMT,0) + COALESCE(MONTHLY_REPLACEMENT_INCOME_AMT,0) + 
					COALESCE(MONTHLY_OTHER_INCOME_AMT,0) + COALESCE(MONTHLY_CHILD_ALLOW_AMT,0) - COALESCE(MONTHLY_RENTAL_AMT,0) -
					COALESCE(MONTHLY_ALIMONY_AMT,0) - COALESCE(MONTHLY_CHILD_SUPPORT_AMT,0) - COALESCE(MONTHLY_REPAYMENT_AMT,0) - 
					COALESCE(MONTHLY_REPAYMENT_OTHERS_AMT,0) -COALESCE(MONTHLY_OTHER_CHARGE_AMT,0));"
						/* I18NOK:END */
		}
	    }
		;
		QUIT;
	%end;
	
	/* New definition for CORP_ACCOUNT_DIM */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.CORP_ACCOUNT_DIM, DATA)) or %sysfunc(exist(bankcrfm.CORP_ACCOUNT_DIM, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
				   
		proc cas;
				table.view/PROMOTE=TRUE
					/* I18NOK:BEGIN */
				caslib="bankcrfm"
				name="CORP_ACCOUNT_DIM"
				tables={{
				name="ACCOUNT_DIM"
				caslib="bankcrfm"
				vars={{name="ACCOUNT_RK",LABEL="ACCOUNT_RK"},{name="ACCOUNT_SK",LABEL="ACCOUNT_SK"},					 
					 {name="OWNED_BY_INTERNAL_ORG_RK" ,LABEL="OWNED_BY_INTERNAL_ORG_RK" ,FORMAT="12."},
					 {name="PRIMARY_PRODUCT_RK" , LABEL="PRIMARY_PRODUCT_RK" ,FORMAT="12."},
					 {name="CREDIT_FACILITY_RK" , LABEL="CREDIT_FACILITY_RK" ,FORMAT="12."},
					 {name="ACCOUNT_ID" , LABEL="ACCOUNT_ID"},
					 {name="ACCOUNT_TYPE_CD" , LABEL="ACCOUNT_TYPE_CD"},
					 {name="ACCOUNT_TYPE_DESC" , LABEL="ACCOUNT_TYPE_DESC"},
					 {name="ACCOUNT_SUB_TYPE_CD" , LABEL="ACCOUNT_SUB_TYPE_CD"},
					 {name="ACCOUNT_SUB_TYPE_DESC" , LABEL="ACCOUNT_SUB_TYPE_DESC"},
					 {name="PURPOSE_CD" , LABEL="PURPOSE_CD"},
					 {name="ACCT_HOLDERS_CNT" , LABEL="ACCT_HOLDERS_CNT"},
					 {name="SIGNATORIES_CNT" , LABEL="SIGNATORIES_CNT"},
					 {name="ADDITIONAL_CARD_CNT" , LABEL="ADDITIONAL_CARD_CNT"},
					 {name="SECURITY_CD" , LABEL="SECURITY_CD"},
					 {name="COLLATERAL_CD" , LABEL="COLLATERAL_CD"},
					 {name="MORTGAGE_INSURED_FLG" , LABEL="MORTGAGE_INSURED_FLG"},
					 {name="PAYMENT_INSURED_FLG" , LABEL="PAYMENT_INSURED_FLG"},
					 {name="CURRENCY_CD" , LABEL="CURRENCY_CD"},
					 {name="OPENING_CHANNEL_CD" , LABEL="OPENING_CHANNEL_CD"},
					 {name="BROKER_FLG" , LABEL="BROKER_FLG"},
					 {name="OPENING_CAMPAIGN_CD" , LABEL="OPENING_CAMPAIGN_CD"},
					 {name="DOCUMENTATION_TYPE_CD" , LABEL="DOCUMENTATION_TYPE_CD"},
					 {name="CHECK_BOOK_FLG" , LABEL="CHECK_BOOK_FLG"},
					 {name="MIN_ACCOUNT_OPENING_AMT" , LABEL="MIN_ACCOUNT_OPENING_AMT"},
					 {name="REQUIRED_MIN_BALANCE_AMT" , LABEL="REQUIRED_MIN_BALANCE_AMT"},
					 {name="ALLOW_OVERDRAFT_FLG" , LABEL="ALLOW_OVERDRAFT_FLG"},
					 {name="SAFE_DEPOSIT_FLG" , LABEL="SAFE_DEPOSIT_FLG"},
					 {name="MIN_REDRAW_AMT" , LABEL="MIN_REDRAW_AMT"},
					 {name="MIN_PAYMENT_FLG" , LABEL="MIN_PAYMENT_FLG"},
					 {name="DISBURSEMENT_TYPE_CD" , LABEL="DISBURSEMENT_TYPE_CD"},
					 {name="GRACE_PERIOD_DAYS_CNT" , LABEL="GRACE_PERIOD_DAYS_CNT"},
					 {name="CASH_BACK_FLG" , LABEL="CASH_BACK_FLG"},
					 {name="CASH_BACK_PCT" , LABEL="CASH_BACK_PCT"},
					 {name="FINANCE_CHARGE_FLG" , LABEL="FINANCE_CHARGE_FLG"},
					 {name="SPLIT_LOAN_FLG" , LABEL="SPLIT_LOAN_FLG"},
					 {name="ANNUAL_FEES_AMT" , LABEL="ANNUAL_FEES_AMT"},
					 {name="PORTABILITY_FLG" , LABEL="PORTABILITY_FLG"},
					 {name="ACTUAL_ACCOUNT_OPENING_AMT" , LABEL="ACTUAL_ACCOUNT_OPENING_AMT"},
					 {name="CURRENT_LIMIT_AMT" , LABEL="CURRENT_LIMIT_AMT"},
					 {name="CASH_LIMIT_AMT" , LABEL="CASH_LIMIT_AMT"},
					 {name="SECURITY_DEPOSIT_AMT" , LABEL="SECURITY_DEPOSIT_AMT"},
					 {name="APPROVED_AMT" , LABEL="APPROVED_AMT"},
					 {name="ACTUAL_ADVANCE_AMT" , LABEL="ACTUAL_ADVANCE_AMT"},
					 {name="COLLECTIONS_STATUS_CD" , LABEL="COLLECTIONS_STATUS_CD"},
					 {name="DOWNPAYMENT_AMT" , LABEL="DOWNPAYMENT_AMT"},
					 {name="IMPROVEMENTS_ALLOCATION_AMT" , LABEL="IMPROVEMENTS_ALLOCATION_AMT"},
					 {name="INTEREST_PAYOUT_FLG" , LABEL="INTEREST_PAYOUT_FLG"},
					 {name="MULTI_RATE_FLG" , LABEL="MULTI_RATE_FLG"},
					 {name="CLOSE_REASON_CD" , LABEL="CLOSE_REASON_CD"},
					 {name="ACCOUNT_STATUS_CD" , LABEL="ACCOUNT_STATUS_CD"},
					 {name="ACCOUNT_LIFECYCLE_STG_CD" , LABEL="ACCOUNT_LIFECYCLE_STG_CD"},
					 {name="OFFSET_ACCOUNT_FLG" , LABEL="OFFSET_ACCOUNT_FLG"},
					 {name="DO_NOT_CONTACT_FLG" , LABEL="DO_NOT_CONTACT_FLG"},
					 {name="HONEYMOON_PERIOD_FLG" , LABEL="HONEYMOON_PERIOD_FLG"},
					 {name="LINKED_ACCOUNT_FLG" , LABEL="LINKED_ACCOUNT_FLG"},
					 {name="LINKED_DEP_ACCT_FLG" , LABEL="LINKED_DEP_ACCT_FLG"},
					 {name="STATEMENT_FREQUENCY_CD" , LABEL="STATEMENT_FREQUENCY_CD"},
					 {name="REPAYMENT_HOLIDAY_FLG" , LABEL="REPAYMENT_HOLIDAY_FLG"},
					 {name="PAYMENT_FREQUENCY_CD" , LABEL="PAYMENT_FREQUENCY_CD"},
					 {name="REGULAR_PERIODIC_PAYMENT_AMT" , LABEL="REGULAR_PERIODIC_PAYMENT_AMT"},
					 {name="PAYMENT_MODE_CD" , LABEL="PAYMENT_MODE_CD"},
					 {name="SPECIAL_RATE_TYPE_CD" , LABEL="SPECIAL_RATE_TYPE_CD"},
					 {name="SPECIAL_INTEREST_RT" , LABEL="SPECIAL_INTEREST_RT"},
					 {name="VALID_START_DTTM" , LABEL="VALID_START_DTTM" ,FORMAT="NLDATM21."},
					 {name="VALID_END_DTTM" , LABEL="VALID_END_DTTM" ,FORMAT="NLDATM21."},
					 {name="HOME_STATUS_CD" , LABEL="HOME_STATUS_CD"},
					 {name="STEP_UP_FACILITY_USED_FLG" LABEL="STEP_UP_FACILITY_USED_FLG"},
					 {name="CALLABLE_FACILITY_USED_FLG" , LABEL="CALLABLE_FACILITY_USED_FLG"},
					 {name="ACCOUNT_RENEWAL_TYPE_CD" , LABEL="ACCOUNT_RENEWAL_TYPE_CD"},
					 {name="COLLATERAL_AMT" , LABEL="COLLATERAL_AMT"},
					 {name="GUARANTORS_CNT" , LABEL="GUARANTORS_CNT"},
					 {name="NOMINEES_CNT" , LABEL="NOMINEES_CNT"},
					 {name="REDRAW_FLG" , LABEL="REDRAW_FLG"},
					 {name="CLOSING_COST_AMT" , LABEL="CLOSING_COST_AMT"},
					 {name="SENIORITY_CD" , LABEL="SENIORITY_CD"},
					 {name="LIEN_INDICATOR_FLG" , LABEL="LIEN_INDICATOR_FLG"},
					 {name="OVERDRAFT_LIMIT_AMT" , LABEL="OVERDRAFT_LIMIT_AMT"},
					 {name="SECURITY_DEPOSIT_REFUND_AMT" , LABEL="SECURITY_DEPOSIT_REFUND_AMT"},
					 {name="STANDING_ORDERS_CNT" , LABEL="STANDING_ORDERS_CNT"},
					 {name="CHECKING_MAIN_FLG" , LABEL="CHECKING_MAIN_FLG"},
					 {name="INITIAL_LIMIT_AMT" , LABEL="INITIAL_LIMIT_AMT"},
					 {name="DIRECT_DEBITS_CNT" , LABEL="DIRECT_DEBITS_CNT"},
					 {name="GUARANTEE_AMT" , LABEL="GUARANTEE_AMT"},
					 {name="PROVISIONAL_CREDIT_LIMIT_AMT" , LABEL="PROVISIONAL_CREDIT_LIMIT_AMT"},
					 {name="MORTGAGE_OPEN_TO_BUY_AMT" , LABEL="MORTGAGE_OPEN_TO_BUY_AMT"},
					 {name="CHARGE_OFF_AMT" , LABEL="CHARGE_OFF_AMT"},
					 {name="CHARGE_OFF_FLG" , LABEL="CHARGE_OFF_FLG"},
					 {name="ACCOUNT_RENEWAL_CNT" , LABEL="ACCOUNT_RENEWAL_CNT"},
					 {name="PRIMARY_CUSTOMER_RK" , LABEL="PRIMARY_CUSTOMER_RK" ,FORMAT="12."},
					 {name="INDIVIDUAL_ORGANIZATION_CD" , LABEL="INDIVIDUAL_ORGANIZATION_CD"},
					 {name="OPEN_DT" , LABEL="OPEN_DT" ,FORMAT="NLDATM21."},
					 {name="REGISTER_ONLINE_DT" , LABEL="REGISTER_ONLINE_DT" ,FORMAT="NLDATM21."},
					 {name="CURRENT_LIMIT_DT" , LABEL="CURRENT_LIMIT_DT" ,FORMAT="NLDATM21."},
					 {name="CARD_ISSUE_DT" , LABEL="CARD_ISSUE_DT" ,FORMAT="NLDATM21."},
					 {name="CARD_REISSUE_DT" , LABEL="CARD_REISSUE_DT" ,FORMAT="NLDATM21."},
					 {name="CARD_EXPIRATION_DT" , LABEL="CARD_EXPIRATION_DT" ,FORMAT="NLDATM21."},
					 {name="CHARGE_OFF_DT" , LABEL="CHARGE_OFF_DT" ,FORMAT="NLDATM21."},
					 {name="HONEYMOON_START_DT" , LABEL="HONEYMOON_START_DT" ,FORMAT="NLDATM21."},
					 {name="HONEYMOON_END_DT" , LABEL="HONEYMOON_END_DT" ,FORMAT="NLDATM21."},
					 {name="SPECIAL_RATE_END_DT" , LABEL="SPECIAL_RATE_END_DT" ,FORMAT="NLDATM21."},
					 {name="SPECIAL_RATE_START_DT" , LABEL="SPECIAL_RATE_START_DT" ,FORMAT="NLDATM21."},
					 {name="OVERDRAFT_LIMIT_DT" , LABEL="OVERDRAFT_LIMIT_DT" ,FORMAT="NLDATM21."},
					 {name="PROV_CREDIT_LIMIT_OPEN_DT" , LABEL="PROV_CREDIT_LIMIT_OPEN_DT" ,FORMAT="NLDATM21."},
					 {name="PROV_CREDIT_LIMIT_CLOSE_DT" , LABEL="PROV_CREDIT_LIMIT_CLOSE_DT" ,FORMAT="NLDATM21."},
					 {name="CLOSE_DT" , LABEL="CLOSE_DT" ,FORMAT="NLDATM21."},
					 {name="REPAYMENT_HOLIDAY_END_DT" , LABEL="REPAYMENT_HOLIDAY_END_DT" ,FORMAT="NLDATM21."},
					 {name="REPAYMENT_HOLIDAY_START_DT" , LABEL="REPAYMENT_HOLIDAY_START_DT" ,FORMAT="NLDATM21."}}
			computedVars={{name="ACCOUNT_HIERARCHY_CD"}{name="CUSTOMER_RK"}{name="ACCOUNT_RK_2"}}
			computedVarsprogram="ACCOUNT_HIERARCHY_CD=IF (ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND ACCOUNT_SUB_TYPE_CD IN (&CHK_ACCOUNT_SUB_TYPE)) THEN &ACC_HIER_CHK 
					 ELSE IF (ACCOUNT_TYPE_CD IN (&CCD_ACCOUNT_TYPE)) THEN &ACC_HIER_CCD 
					 ELSE IF (ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND ACCOUNT_SUB_TYPE_CD IN (&SAV_ACCOUNT_SUB_TYPE,&CHK_ACCOUNT_SUB_TYPE) AND ALLOW_OVERDRAFT_FLG IN (&CHECK_FLAG_TRUE)) THEN &ACC_HIER_OD
					 ELSE IF (ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  ACCOUNT_SUB_TYPE_CD IN (&RDP_ACCOUNT_SUB_TYPE)) THEN &ACC_HIER_RD
					 ELSE IF (ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  ACCOUNT_SUB_TYPE_CD IN  (&SAV_ACCOUNT_SUB_TYPE)) THEN &ACC_HIER_SAV
					 ELSE IF (ACCOUNT_TYPE_CD IN (&MTG_ACCOUNT_TYPE, &LON_ACCOUNT_TYPE) AND COLLATERAL_CD ne '') THEN &ACC_HIER_SLN  
					 ELSE IF (ACCOUNT_TYPE_CD IN (&COR_ACCOUNT_TYPE) AND  ACCOUNT_SUB_TYPE_CD  IN (&TDP_ACCOUNT_SUB_TYPE)) THEN &ACC_HIER_TD 
					 ELSE IF (ACCOUNT_TYPE_CD IN (&LON_ACCOUNT_TYPE) AND (COLLATERAL_CD eq '' )) THEN &ACC_HIER_ULN
					 ELSE ' ';CUSTOMER_RK=PRIMARY_CUSTOMER_RK;
					 ACCOUNT_RK_2=ACCOUNT_RK;"
					 	/* I18NOK:END */
		}
	    }
		;
		QUIT;
	%end;

    /* New definition for BANK_CARD_DTL_BASE */
	%let etls_viewExist =%eval(%sysfunc(exist(bankcrfm.BANK_CARD_DTL_BASE, DATA)) or %sysfunc(exist(bankcrfm.BANK_CARD_DTL_BASE, VIEW))); 
	%if (&etls_viewExist eq 0) %then %do; 
				   
		proc cas;
				table.view/PROMOTE=TRUE
					/* I18NOK:BEGIN */
				caslib="bankcrfm"
				name="BANK_CARD_DTL_BASE"
				tables={{
				name="BANK_CARD_DETAIL"
				caslib="bankcrfm"
				vars={{name="ACCOUNT_RK",Label="ACCOUNT_RK"},
					 {name="CUSTOMER_RK",Label="CUSTOMER_RK"},
					 {name="BANK_CARD_TYPE_CD",Label="BANK_CARD_TYPE_CD"},
					 {name="CARD_ISSUE_DT",Label="CARD_ISSUE_DT"},     
					 {name="CARD_EXPIRATION_DT",Label="CARD_EXPIRATION_DT"},
					 {name="CARD_CANCEL_REASON_CD",Label="CARD_CANCEL_REASON_CD"},
					 {name="LOSS_AMT",Label="LOSS_AMT"},
					 {name="CARD_CANCEL_DT",Label="CARD_CANCEL_DT"},
					 {name="LOSS_DT",Label="LOSS_DT"},
					 {name="ACCOUNT_HIERARCHY_CD",Label="ACCOUNT_HIERARCHY_CD"},
					 {name="PRODUCT_SUB_TYPE_CD",Label="PRODUCT_SUB_TYPE_CD"},  
					 {name="FINANCIAL_PRODUCT_TYPE_CD",Label="FINANCIAL_PRODUCT_TYPE_CD"}}
			computedVars={{name="CARD_CNT"}}
			computedVarsprogram="CARD_CNT=1"
				/* I18NOK:END */
		}
	    }
		;
		QUIT;
	%end;
	
	/* Terminate cas session */
	
	%dabt_terminate_cas_session(cas_session_ref=create_view);
	
%mend rmcr_create_single_table_view;
		
	