%macro rmcr_csb_source_dim_attrib;

proc sql;
insert into &lib_apdm..SOURCE_DIM_ATTRIB_VALUE_MASTER (
DIM_ATTRIBUTE_VALUE_SK ,SOURCE_COLUMN_SK ,DIM_ATTRIBUTE_VALUE ,DIM_ATTRIBUTE_VALUE_CD ,CREATED_DTTM ,CREATED_BY_USER ,LAST_PROCESSED_DTTM ,LAST_PROCESSED_BY_USER ,DIM_ATTRIBUTE_VALUE_SHORT_NM ,DIM_ATTRIBUTE_VALUE_DESC 
)
VALUES(253,224,'&GUR1_APP_TYPE_CD','GR1',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM1.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS1.1, noquote))") /* i18nOK:Line */
VALUES(254,224,'&APPLC_TC_JH1','JH1',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM2.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS2.1, noquote))") /* i18nOK:Line */
VALUES(255,224,'&APPLC_TC_JH2','JH2',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM3.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS3.1, noquote))") /* i18nOK:Line */
VALUES(256,224,'&APPLC_TC_NOM','NOM',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM4.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS4.1, noquote))") /* i18nOK:Line */
VALUES(257,224,'&PRI_APP_TYPE_CD','PRI',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM5.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS5.1, noquote))") /* i18nOK:Line */
VALUES(258,224,'&APPLC_TC_SEC','SEC',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM6.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS6.1, noquote))") /* i18nOK:Line */
VALUES(374,371,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM25.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS25.1, noquote))") /* i18nOK:Line */
VALUES(380,371,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM27.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS27.1, noquote))") /* i18nOK:Line */
VALUES(383,371,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM30.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS30.1, noquote))") /* i18nOK:Line */
VALUES(386,372,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM31.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS31.1, noquote))") /* i18nOK:Line */
VALUES(387,372,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM32.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS32.1, noquote))") /* i18nOK:Line */
VALUES(388,372,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM33.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS33.1, noquote))") /* i18nOK:Line */
VALUES(389,372,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM34.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS34.1, noquote))") /* i18nOK:Line */
VALUES(406,383,'&CCD_PRD_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM35.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS35.1, noquote))") /* i18nOK:Line */
VALUES(407,383,'&COR_PRD_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM36.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS36.1, noquote))") /* i18nOK:Line */
VALUES(408,383,'&LON_PRD_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM37.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS37.1, noquote))") /* i18nOK:Line */
VALUES(409,383,'&MTG_PRD_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM38.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS38.1, noquote))") /* i18nOK:Line */
VALUES(414,388,'&REC_FTYC_GUR','GUR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM43.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS43.1, noquote))") /* i18nOK:Line */
VALUES(416,388,'&REC_FTYC_PCL','PCL',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM44.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS44.1, noquote))") /* i18nOK:Line */
VALUES(417,388,'&REC_FTYC_PCU','PCU',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM45.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS45.1, noquote))") /* i18nOK:Line */
VALUES(418,388,'&REC_FTYC_SRD','SRD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM46.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS46.1, noquote))") /* i18nOK:Line */
VALUES(602,1317,'&OUTCOME_ACCEPT','ACC',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM49.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS49.1, noquote))") /* i18nOK:Line */
VALUES(604,1317,'&OUTCOME_REJECT','REJ',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM50.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS50.1, noquote))") /* i18nOK:Line */
VALUES(606,1319,'&DEC_CD_REJ','REJ',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM51.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS51.1, noquote))") /* i18nOK:Line */
VALUES(607,1320,'&DEC_OFLG_N','N',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM52.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS52.1, noquote))") /* i18nOK:Line */
VALUES(608,1320,'&DEC_OFLG_Y','Y',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM53.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS53.1, noquote))") /* i18nOK:Line */
VALUES(617,1327,'&CHANNEL_CD_INN','INN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM55.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS55.1, noquote))") /* i18nOK:Line */
VALUES(620,1327,'&CHANNEL_CD_TLR','TLR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM57.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS57.1, noquote))") /* i18nOK:Line */
VALUES(637,1357,'&BNK_STS_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM62.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS62.1, noquote))") /* i18nOK:Line */
VALUES(657,1376,'&DELINQUENCY_FLG_N','N',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM63.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS63.1, noquote))") /* i18nOK:Line */
VALUES(658,1376,'&DELINQUENCY_FLG_Y','Y',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM64.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS64.1, noquote))") /* i18nOK:Line */
VALUES(770,1549,'&MTG_PRD_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM65.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS65.1, noquote))") /* i18nOK:Line */
VALUES(771,1549,'&CCD_PRD_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM66.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS66.1, noquote))") /* i18nOK:Line */
VALUES(772,1549,'&COR_PRD_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM67.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS67.1, noquote))") /* i18nOK:Line */
VALUES(773,1549,'&LON_PRD_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM68.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS68.1, noquote))") /* i18nOK:Line */
VALUES(776,1563,'&ACCT_STATUS_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM69.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS69.1, noquote))") /* i18nOK:Line */
VALUES(777,1563,'&ACCT_STATUS_CLO','CLO',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM70.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS70.1, noquote))") /* i18nOK:Line */
VALUES(778,1563,'&ACCT_STATUS_INA','INA',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM71.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS71.1, noquote))") /* i18nOK:Line */
VALUES(779,1567,'&DEFAULT_STATUS_CD','DFT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM72.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS72.1, noquote))") /* i18nOK:Line */
VALUES(786,1603,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM73.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS73.1, noquote))") /* i18nOK:Line */
VALUES(787,1603,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM74.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS74.1, noquote))") /* i18nOK:Line */
VALUES(788,1603,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM75.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS75.1, noquote))") /* i18nOK:Line */
VALUES(789,1603,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM76.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS76.1, noquote))") /* i18nOK:Line */
VALUES(794,1605,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM78.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS78.1, noquote))") /* i18nOK:Line */
VALUES(803,1605,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM81.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS81.1, noquote))") /* i18nOK:Line */
VALUES(806,1605,'&SSL_ACCOUNT_SUB_TYPE','SSL',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM83.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS83.1, noquote))") /* i18nOK:Line */
VALUES(807,1605,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM84.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS84.1, noquote))") /* i18nOK:Line */
VALUES(817,1612,'&COL_TYPE_PRP','PRP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM85.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS85.1, noquote))") /* i18nOK:Line */
VALUES(838,1653,'&CLOSE_REASON_CD_PPY','PPY',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM86.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS86.1, noquote))") /* i18nOK:Line */
VALUES(839,1654,'&ACCT_STATUS_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM87.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS87.1, noquote))") /* i18nOK:Line */
VALUES(840,1654,'&ACCT_STATUS_CLO','CLO',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM88.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS88.1, noquote))") /* i18nOK:Line */
VALUES(841,1654,'&ACCT_STATUS_INA','INA',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM89.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS89.1, noquote))") /* i18nOK:Line */
VALUES(872,1717,'&CUST_TYPES_CORP','SME',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM90.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS90.1, noquote))") /* i18nOK:Line */
VALUES(880,1745,'&OUTCOME_ACCEPT','ACC',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM91.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS91.1, noquote))") /* i18nOK:Line */
VALUES(882,1745,'&OUTCOME_REJECT','REJ',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM92.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS92.1, noquote))") /* i18nOK:Line */
VALUES(884,1747,'&OUTCOME_REJECT','REJ',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM93.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS93.1, noquote))") /* i18nOK:Line */
VALUES(893,1755,'&CHANNEL_CD_INN','INN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM95.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS95.1, noquote))") /* i18nOK:Line */
VALUES(896,1755,'&CHANNEL_CD_TLR','TLR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM97.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS97.1, noquote))") /* i18nOK:Line */
VALUES(897,1806,'&BNK_STS_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM98.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS98.1, noquote))") /* i18nOK:Line */
VALUES(908,1873,'&OUTCOME_REJECT','REJ',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM99.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS99.1, noquote))") /* i18nOK:Line */
;
quit;
proc sql;
insert into &lib_apdm..SOURCE_DIM_ATTRIB_VALUE_MASTER (
DIM_ATTRIBUTE_VALUE_SK ,SOURCE_COLUMN_SK ,DIM_ATTRIBUTE_VALUE ,DIM_ATTRIBUTE_VALUE_CD ,CREATED_DTTM ,CREATED_BY_USER ,LAST_PROCESSED_DTTM ,LAST_PROCESSED_BY_USER ,DIM_ATTRIBUTE_VALUE_SHORT_NM ,DIM_ATTRIBUTE_VALUE_DESC 
)
VALUES(912,1964,'&CCD_PRD_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM100.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS100.1, noquote))") /* i18nOK:Line */
VALUES(913,1964,'&COR_PRD_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM101.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS101.1, noquote))") /* i18nOK:Line */
VALUES(914,1964,'&LON_PRD_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM102.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS102.1, noquote))") /* i18nOK:Line */
VALUES(915,1964,'&MTG_PRD_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM103.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS103.1, noquote))") /* i18nOK:Line */
VALUES(987,2034,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM120.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS120.1, noquote))") /* i18nOK:Line */
VALUES(988,2034,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM121.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS121.1, noquote))") /* i18nOK:Line */
VALUES(989,2034,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM122.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS122.1, noquote))") /* i18nOK:Line */
VALUES(990,2034,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM123.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS123.1, noquote))") /* i18nOK:Line */
VALUES(991,2034,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM124.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS124.1, noquote))") /* i18nOK:Line */
VALUES(992,2034,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM125.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS125.1, noquote))") /* i18nOK:Line */
VALUES(993,2034,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM126.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS126.1, noquote))") /* i18nOK:Line */
VALUES(994,2034,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM127.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS127.1, noquote))") /* i18nOK:Line */
VALUES(1054,2073,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM132.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS132.1, noquote))") /* i18nOK:Line */
VALUES(1055,2073,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM133.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS133.1, noquote))") /* i18nOK:Line */
VALUES(1056,2073,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM134.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS134.1, noquote))") /* i18nOK:Line */
VALUES(1057,2073,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM135.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS135.1, noquote))") /* i18nOK:Line */
VALUES(1058,2073,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM136.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS136.1, noquote))") /* i18nOK:Line */
VALUES(1059,2073,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM137.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS137.1, noquote))") /* i18nOK:Line */
VALUES(1060,2073,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM138.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS138.1, noquote))") /* i18nOK:Line */
VALUES(1061,2073,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM139.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS139.1, noquote))") /* i18nOK:Line */
VALUES(1095,1907,'&PD_APP_MODEL','PDA',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM144.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS144.1, noquote))") /* i18nOK:Line */
VALUES(1096,1907,'&PD_ONG_MODEL','PDO',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM145.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS145.1, noquote))") /* i18nOK:Line */
VALUES(1097,1907,'&CCF_MODEL','CCF',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM146.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS146.1, noquote))") /* i18nOK:Line */
VALUES(1098,1907,'&LGD_MODEL','LGD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM147.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS147.1, noquote))") /* i18nOK:Line */
VALUES(1099,1907,'&CROSS_SELL_MODEL','CSM',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM148.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS148.1, noquote))") /* i18nOK:Line */
VALUES(1100,1907,'&UP_SELL_MODEL','UPS',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM149.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS149.1, noquote))") /* i18nOK:Line */
VALUES(1101,1907,'&CUS_RET_MODEL','CRM',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM150.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS150.1, noquote))") /* i18nOK:Line */
VALUES(1102,1943,'&PD_APP_MODEL','PDA',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM151.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS151.1, noquote))") /* i18nOK:Line */
VALUES(1103,1943,'&PD_ONG_MODEL','PDO',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM152.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS152.1, noquote))") /* i18nOK:Line */
VALUES(1104,1943,'&CCF_MODEL','CCF',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM153.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS153.1, noquote))") /* i18nOK:Line */
VALUES(1105,1943,'&LGD_MODEL','LGD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM154.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS154.1, noquote))") /* i18nOK:Line */
VALUES(1106,1943,'&CROSS_SELL_MODEL','CSM',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM155.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS155.1, noquote))") /* i18nOK:Line */
VALUES(1107,1943,'&UP_SELL_MODEL','UPS',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM156.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS156.1, noquote))") /* i18nOK:Line */
VALUES(1108,1943,'&CUS_RET_MODEL','CRM',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM157.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS157.1, noquote))") /* i18nOK:Line */
VALUES(1109,1983,'&PD_APP_MODEL','PDA',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM158.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS158.1, noquote))") /* i18nOK:Line */
VALUES(1110,1983,'&PD_ONG_MODEL','PDO',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM159.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS159.1, noquote))") /* i18nOK:Line */
VALUES(1111,1983,'&CCF_MODEL','CCF',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM160.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS160.1, noquote))") /* i18nOK:Line */
VALUES(1112,1983,'&LGD_MODEL','LGD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM161.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS161.1, noquote))") /* i18nOK:Line */
VALUES(1113,1983,'&CROSS_SELL_MODEL','CSM',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM162.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS162.1, noquote))") /* i18nOK:Line */
VALUES(1114,1983,'&UP_SELL_MODEL','UPS',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM163.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS163.1, noquote))") /* i18nOK:Line */
VALUES(1115,1983,'&CUS_RET_MODEL','CRM',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM164.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS164.1, noquote))") /* i18nOK:Line */
VALUES(1116,1987,'&PD_APP_MODEL','PDA',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM165.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS165.1, noquote))") /* i18nOK:Line */
VALUES(1117,1987,'&PD_ONG_MODEL','PDO',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM166.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS166.1, noquote))") /* i18nOK:Line */
VALUES(1118,1987,'&CCF_MODEL','CCF',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM167.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS167.1, noquote))") /* i18nOK:Line */
VALUES(1119,1987,'&LGD_MODEL','LGD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM168.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS168.1, noquote))") /* i18nOK:Line */
VALUES(1120,1987,'&CROSS_SELL_MODEL','CSM',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM169.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS169.1, noquote))") /* i18nOK:Line */
VALUES(1121,1987,'&UP_SELL_MODEL','UPS',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM170.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS170.1, noquote))") /* i18nOK:Line */
VALUES(1122,1987,'&CUS_RET_MODEL','CRM',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM171.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS171.1, noquote))") /* i18nOK:Line */
VALUES(1135,1849,'&GUR1_APP_TYPE_CD','GR1',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM176.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS176.1, noquote))") /* i18nOK:Line */
VALUES(1136,1849,'&APPLC_TC_JH1','JH1',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM177.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS177.1, noquote))") /* i18nOK:Line */
VALUES(1137,1849,'&APPLC_TC_JH2','JH2',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM178.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS178.1, noquote))") /* i18nOK:Line */
VALUES(1138,1849,'&APPLC_TC_NOM','NOM',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM179.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS179.1, noquote))") /* i18nOK:Line */
VALUES(1139,1849,'&PRI_APP_TYPE_CD','PRI',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM180.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS180.1, noquote))") /* i18nOK:Line */
VALUES(1140,1849,'&APPLC_TC_SEC','SEC',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM181.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS181.1, noquote))") /* i18nOK:Line */
VALUES(1141,1873,'&OUTCOME_ACCEPT','ACC',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM182.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS182.1, noquote))") /* i18nOK:Line */
VALUES(1165,2129,'&BNK_STS_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM187.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS187.1, noquote))") /* i18nOK:Line */
VALUES(1185,2148,'&DELINQUENCY_FLG_N','N',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM188.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS188.1, noquote))") /* i18nOK:Line */
VALUES(1186,2148,'&DELINQUENCY_FLG_Y','Y',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM189.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS189.1, noquote))") /* i18nOK:Line */
VALUES(1205,2181,'&BNK_STS_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM194.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS194.1, noquote))") /* i18nOK:Line */
VALUES(1225,2200,'&DELINQUENCY_FLG_N','N',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM195.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS195.1, noquote))") /* i18nOK:Line */
VALUES(1226,2200,'&DELINQUENCY_FLG_Y','Y',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM196.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS196.1, noquote))") /* i18nOK:Line */
VALUES(1230,2204,'&CUST_TYPES_CORP','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM197.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS197.1, noquote))") /* i18nOK:Line */
VALUES(1244,2217,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM198.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS198.1, noquote))") /* i18nOK:Line */
VALUES(1245,2217,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM199.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS199.1, noquote))") /* i18nOK:Line */
;
quit;
proc sql;
insert into &lib_apdm..SOURCE_DIM_ATTRIB_VALUE_MASTER (
DIM_ATTRIBUTE_VALUE_SK ,SOURCE_COLUMN_SK ,DIM_ATTRIBUTE_VALUE ,DIM_ATTRIBUTE_VALUE_CD ,CREATED_DTTM ,CREATED_BY_USER ,LAST_PROCESSED_DTTM ,LAST_PROCESSED_BY_USER ,DIM_ATTRIBUTE_VALUE_SHORT_NM ,DIM_ATTRIBUTE_VALUE_DESC 
)
VALUES(1246,2217,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM200.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS200.1, noquote))") /* i18nOK:Line */
VALUES(1247,2217,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM201.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS201.1, noquote))") /* i18nOK:Line */
VALUES(1248,2217,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM202.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS202.1, noquote))") /* i18nOK:Line */
VALUES(1249,2217,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM203.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS203.1, noquote))") /* i18nOK:Line */
VALUES(1250,2217,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM204.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS204.1, noquote))") /* i18nOK:Line */
VALUES(1251,2217,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM205.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS205.1, noquote))") /* i18nOK:Line */
VALUES(1252,2218,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM206.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS206.1, noquote))") /* i18nOK:Line */
VALUES(1253,2218,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM207.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS207.1, noquote))") /* i18nOK:Line */
VALUES(1254,2218,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM208.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS208.1, noquote))") /* i18nOK:Line */
VALUES(1255,2218,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM209.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS209.1, noquote))") /* i18nOK:Line */
VALUES(1256,2218,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM210.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS210.1, noquote))") /* i18nOK:Line */
VALUES(1257,2218,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM211.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS211.1, noquote))") /* i18nOK:Line */
VALUES(1258,2218,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM212.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS212.1, noquote))") /* i18nOK:Line */
VALUES(1259,2218,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM213.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS213.1, noquote))") /* i18nOK:Line */
VALUES(1260,2219,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM214.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS214.1, noquote))") /* i18nOK:Line */
VALUES(1261,2219,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM215.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS215.1, noquote))") /* i18nOK:Line */
VALUES(1262,2219,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM216.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS216.1, noquote))") /* i18nOK:Line */
VALUES(1263,2219,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM217.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS217.1, noquote))") /* i18nOK:Line */
VALUES(1264,2219,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM218.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS218.1, noquote))") /* i18nOK:Line */
VALUES(1265,2219,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM219.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS219.1, noquote))") /* i18nOK:Line */
VALUES(1266,2219,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM220.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS220.1, noquote))") /* i18nOK:Line */
VALUES(1267,2219,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM221.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS221.1, noquote))") /* i18nOK:Line */
VALUES(1269,540,'&CUS_ACT_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM222.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS222.1, noquote))") /* i18nOK:Line */
VALUES(1306,1717,'&CUST_TYPES_CORP','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM223.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS223.1, noquote))") /* i18nOK:Line */
VALUES(1307,538,'&CUST_TYPES_CORP','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM224.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS224.1, noquote))") /* i18nOK:Line */
VALUES(1314,2257,'&CUST_TYPES_CORP','SME',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM225.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS225.1, noquote))") /* i18nOK:Line */
VALUES(1319,2248,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM226.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS226.1, noquote))") /* i18nOK:Line */
VALUES(1320,2248,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM227.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS227.1, noquote))") /* i18nOK:Line */
VALUES(1321,2248,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM228.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS228.1, noquote))") /* i18nOK:Line */
VALUES(1322,2248,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM229.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS229.1, noquote))") /* i18nOK:Line */
VALUES(1327,2249,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM231.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS231.1, noquote))") /* i18nOK:Line */
VALUES(1336,2249,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM234.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS234.1, noquote))") /* i18nOK:Line */
VALUES(1339,2249,'&SSL_ACCOUNT_SUB_TYPE','SSL',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM236.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS236.1, noquote))") /* i18nOK:Line */
VALUES(1340,2249,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM237.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS237.1, noquote))") /* i18nOK:Line */
VALUES(1353,2258,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM238.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS238.1, noquote))") /* i18nOK:Line */
VALUES(1354,2258,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM239.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS239.1, noquote))") /* i18nOK:Line */
VALUES(1355,2258,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM240.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS240.1, noquote))") /* i18nOK:Line */
VALUES(1356,2258,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM241.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS241.1, noquote))") /* i18nOK:Line */
VALUES(1357,2259,'&CREDIT_FACILITY_LOC','LOC',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM242.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS242.1, noquote))") /* i18nOK:Line */
VALUES(1358,2259,'&CREDIT_FACILITY_CC','CC',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM243.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS243.1, noquote))") /* i18nOK:Line */
VALUES(1359,2259,'&CREDIT_FACILITY_WC','WC',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM244.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS244.1, noquote))") /* i18nOK:Line */
VALUES(583,1289,'&IND_CUST_TYPE','IND',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM245.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS245.1, noquote))") /* i18nOK:Line */
VALUES(1229,2204,'&IND_CUST_TYPE','IND',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM246.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS246.1, noquote))") /* i18nOK:Line */
VALUES(1308,538,'&CUST_TYPES_CORP','SME',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM247.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS247.1, noquote))") /* i18nOK:Line */
VALUES(1360,1589,'&DEFAULT_STATUS_CD','DFT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM248.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS248.1, noquote))") /* i18nOK:Line */
VALUES(1375,2819,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM254.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS254.1, noquote))") /* i18nOK:Line */
VALUES(1376,2819,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM255.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS255.1, noquote))") /* i18nOK:Line */
VALUES(1377,2819,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM256.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS256.1, noquote))") /* i18nOK:Line */
VALUES(1378,2820,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM257.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS257.1, noquote))") /* i18nOK:Line */
VALUES(1379,2820,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM258.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS258.1, noquote))") /* i18nOK:Line */
VALUES(1380,2820,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM259.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS259.1, noquote))") /* i18nOK:Line */
VALUES(1381,2820,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM260.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS260.1, noquote))") /* i18nOK:Line */
VALUES(1382,2814,'&CCD_PRD_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM261.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS261.1, noquote))") /* i18nOK:Line */
VALUES(1383,2814,'&COR_PRD_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM262.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS262.1, noquote))") /* i18nOK:Line */
VALUES(1384,2814,'&LON_PRD_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM263.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS263.1, noquote))") /* i18nOK:Line */
VALUES(1385,2814,'&MTG_PRD_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM264.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS264.1, noquote))") /* i18nOK:Line */
VALUES(1386,2818,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM265.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS265.1, noquote))") /* i18nOK:Line */
VALUES(1387,2818,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM266.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS266.1, noquote))") /* i18nOK:Line */
VALUES(1388,2818,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM267.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS267.1, noquote))") /* i18nOK:Line */
VALUES(1389,2818,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM268.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS268.1, noquote))") /* i18nOK:Line */
VALUES(1390,2818,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM269.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS269.1, noquote))") /* i18nOK:Line */
VALUES(1391,2818,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM270.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS270.1, noquote))") /* i18nOK:Line */
VALUES(1392,2818,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM271.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS271.1, noquote))") /* i18nOK:Line */
VALUES(1393,2818,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM272.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS272.1, noquote))") /* i18nOK:Line */
;
quit;

proc sql;
insert into &lib_apdm..SOURCE_DIM_ATTRIB_VALUE_MASTER (
DIM_ATTRIBUTE_VALUE_SK ,SOURCE_COLUMN_SK ,DIM_ATTRIBUTE_VALUE ,DIM_ATTRIBUTE_VALUE_CD ,DIM_ATTRIBUTE_VALUE_SHORT_NM ,DIM_ATTRIBUTE_VALUE_DESC ,CREATED_DTTM ,CREATED_BY_USER ,LAST_PROCESSED_DTTM ,LAST_PROCESSED_BY_USER 
)
VALUES(1398,3141,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM73.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS73.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1399,3141,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM74.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS74.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1400,3141,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM75.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS75.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1401,3141,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM76.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS76.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1403,3143,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM78.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS78.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1406,3143,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM81.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS81.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1408,3143,'&SSL_ACCOUNT_SUB_TYPE','SSL',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM83.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS83.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1409,3143,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM84.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS84.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1410,3150,'&COL_TYPE_PRP','PRP',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM85.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS85.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1411,3190,'&CLOSE_REASON_CD_PPY','PPY',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM86.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS86.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1412,3191,'&ACCT_STATUS_ACT','ACT',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM87.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS87.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1413,3191,'&ACCT_STATUS_CLO','CLO',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM88.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS88.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1414,3191,'&ACCT_STATUS_INA','INA',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM89.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS89.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1415,3242,'&ACC_HIER_CHK','CHK',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM198.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS198.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1416,3242,'&ACC_HIER_CCD','CCD',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM199.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS199.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1417,3242,'&ACC_HIER_OD','OD',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM200.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS200.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1418,3242,'&ACC_HIER_RD','RD',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM201.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS201.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1419,3242,'&ACC_HIER_SAV','SAV',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM202.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS202.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1420,3242,'&ACC_HIER_SLN','SLN',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM203.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS203.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1421,3242,'&ACC_HIER_TD','TD',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM204.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS204.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1422,3242,'&ACC_HIER_ULN','ULN',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM205.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS205.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1423,3102,'&CUS_ACT_ACT','ACT',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM222.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS222.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1424,3101,'&CUST_TYPES_CORP','COR',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM224.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS224.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1425,3245,'&CUST_TYPES_CORP','SME',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM225.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS225.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
VALUES(1426,3101,'&CUST_TYPES_CORP','SME',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM247.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS247.1, noquote))","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid") /* i18nOK:Line */
;
quit;

proc sql;
insert into &lib_apdm..SOURCE_DIM_ATTRIB_VALUE_MASTER (
DIM_ATTRIBUTE_VALUE_SK ,SOURCE_COLUMN_SK ,DIM_ATTRIBUTE_VALUE ,DIM_ATTRIBUTE_VALUE_CD ,DIM_ATTRIBUTE_VALUE_SHORT_NM ,DIM_ATTRIBUTE_VALUE_DESC ,CREATED_DTTM ,CREATED_BY_USER ,LAST_PROCESSED_DTTM ,LAST_PROCESSED_BY_USER 
)
VALUES(1427,3255,'&CUS_ACT_ACT','ACT',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM222.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS222.1, noquote))",,"%sysfunc(datetime(),datetime.)"dt,,"&sysuserid",,"%sysfunc(datetime(),datetime.)"dt,,"&sysuserid") /* i18nOK:Line */
VALUES(1428,3254,'&CUST_TYPES_CORP','COR',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM224.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS224.1, noquote))",,"%sysfunc(datetime(),datetime.)"dt,,"&sysuserid",,"%sysfunc(datetime(),datetime.)"dt,,"&sysuserid") /* i18nOK:Line */
VALUES(1429,3254,'&CUST_TYPES_CORP','SME',"%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_SM247.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_dtl_banking,SRC_DIM_ATTRIB_VAL_MASTER.DIM_ATTRIBUTE_VALUE_DS247.1, noquote))",,"%sysfunc(datetime(),datetime.)"dt,,"&sysuserid",,"%sysfunc(datetime(),datetime.)"dt,,"&sysuserid") /* i18nOK:Line */
;
quit;

%mend rmcr_csb_source_dim_attrib;