%macro rmcr_insrt_src_dim_attrib;

proc sql;
insert into &lib_apdm..SOURCE_DIM_ATTRIB_VALUE_MASTER (
DIM_ATTRIBUTE_VALUE_SK ,SOURCE_COLUMN_SK ,DIM_ATTRIBUTE_VALUE ,DIM_ATTRIBUTE_VALUE_CD ,CREATED_DTTM ,CREATED_BY_USER ,LAST_PROCESSED_DTTM ,LAST_PROCESSED_BY_USER ,DIM_ATTRIBUTE_VALUE_SHORT_NM ,DIM_ATTRIBUTE_VALUE_DESC 
)
VALUES(9,4,'&ACCT_STATUS_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM1.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS1.1, noquote))") /* i18NOK:LINE */
VALUES(10,4,'&ACCT_STATUS_CLO','CLO',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM2.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS2.1, noquote))") /* i18NOK:LINE */
VALUES(11,4,'&ACCT_STATUS_INA','INA',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM3.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS3.1, noquote))") /* i18NOK:LINE */
VALUES(16,5,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM5.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS5.1, noquote))") /* i18NOK:LINE */
VALUES(23,5,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM8.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS8.1, noquote))") /* i18NOK:LINE */
VALUES(26,5,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM11.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS11.1, noquote))") /* i18NOK:LINE */
VALUES(29,6,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM12.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS12.1, noquote))") /* i18NOK:LINE */
VALUES(30,6,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM13.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS13.1, noquote))") /* i18NOK:LINE */
VALUES(31,6,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM14.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS14.1, noquote))") /* i18NOK:LINE */
VALUES(32,6,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM15.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS15.1, noquote))") /* i18NOK:LINE */
VALUES(51,17,'&CCD_PRD_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM16.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS16.1, noquote))") /* i18NOK:LINE */
VALUES(52,17,'&COR_PRD_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM17.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS17.1, noquote))") /* i18NOK:LINE */
VALUES(53,17,'&LON_PRD_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM18.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS18.1, noquote))") /* i18NOK:LINE */
VALUES(54,17,'&MTG_PRD_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM19.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS19.1, noquote))") /* i18NOK:LINE */
VALUES(62,122,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM21.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS21.1, noquote))") /* i18NOK:LINE */
VALUES(69,122,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM24.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS24.1, noquote))") /* i18NOK:LINE */
VALUES(72,122,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM27.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS27.1, noquote))") /* i18NOK:LINE */
VALUES(75,123,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM28.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS28.1, noquote))") /* i18NOK:LINE */
VALUES(76,123,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM29.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS29.1, noquote))") /* i18NOK:LINE */
VALUES(77,123,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM30.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS30.1, noquote))") /* i18NOK:LINE */
VALUES(78,123,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM31.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS31.1, noquote))") /* i18NOK:LINE */
VALUES(95,132,'&CCD_PRD_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM32.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS32.1, noquote))") /* i18NOK:LINE */
VALUES(96,132,'&COR_PRD_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM33.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS33.1, noquote))") /* i18NOK:LINE */
VALUES(97,132,'&LON_PRD_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM34.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS34.1, noquote))") /* i18NOK:LINE */
VALUES(98,132,'&MTG_PRD_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM35.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS35.1, noquote))") /* i18NOK:LINE */
VALUES(144,148,'&MED_CD_CHQ','CHQ',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM46.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS46.1, noquote))") /* i18NOK:LINE */
VALUES(145,148,'&MED_CD_CSH','CSH',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM47.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS47.1, noquote))") /* i18NOK:LINE */
VALUES(175,154,'&TRAN_TYP_DEP','DEP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM58.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS58.1, noquote))") /* i18NOK:LINE */
VALUES(176,154,'&DIS_TRANS_TYPE','DIS',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM59.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS59.1, noquote))") /* i18NOK:LINE */
/*VALUES(186,154,'&TRAN_TYP_PRD','PRD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM61.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS61.1, noquote))")*/
VALUES(187,154,'&TRAN_TYP_PUR','PUR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM62.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS62.1, noquote))") /* i18NOK:LINE */
VALUES(191,154,'&TRAN_TYP_WDR','WDR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM63.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS63.1, noquote))") /* i18NOK:LINE */
VALUES(192,155,'&DEBIT_FLAG','D',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM64.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS64.1, noquote))") /* i18NOK:LINE */
VALUES(193,155,'&CREDIT_FLAG','C',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM65.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS65.1, noquote))") /* i18NOK:LINE */
VALUES(198,172,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM67.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS67.1, noquote))") /* i18NOK:LINE */
VALUES(205,172,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM70.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS70.1, noquote))") /* i18NOK:LINE */
VALUES(208,172,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM73.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS73.1, noquote))") /* i18NOK:LINE */
VALUES(211,173,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM74.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS74.1, noquote))") /* i18NOK:LINE */
VALUES(212,173,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM75.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS75.1, noquote))") /* i18NOK:LINE */
VALUES(213,173,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM76.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS76.1, noquote))") /* i18NOK:LINE */
VALUES(214,173,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM77.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS77.1, noquote))") /* i18NOK:LINE */
VALUES(220,180,'&CCD_PRD_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM78.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS78.1, noquote))") /* i18NOK:LINE */
VALUES(221,180,'&COR_PRD_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM79.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS79.1, noquote))") /* i18NOK:LINE */
VALUES(222,180,'&LON_PRD_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM80.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS80.1, noquote))") /* i18NOK:LINE */
VALUES(223,180,'&MTG_PRD_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM81.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS81.1, noquote))") /* i18NOK:LINE */
VALUES(228,190,'&DIS_TRANS_TYPE','DIS',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM86.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS86.1, noquote))") /* i18NOK:LINE */
VALUES(287,300,'&CCD_PRD_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM89.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS89.1, noquote))") /* i18NOK:LINE */
VALUES(288,300,'&COR_PRD_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM90.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS90.1, noquote))") /* i18NOK:LINE */
VALUES(289,300,'&LON_PRD_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM91.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS91.1, noquote))") /* i18NOK:LINE */
VALUES(290,300,'&MTG_PRD_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM92.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS92.1, noquote))") /* i18NOK:LINE */
;
quit;
proc sql;
insert into &lib_apdm..SOURCE_DIM_ATTRIB_VALUE_MASTER (
DIM_ATTRIBUTE_VALUE_SK ,SOURCE_COLUMN_SK ,DIM_ATTRIBUTE_VALUE ,DIM_ATTRIBUTE_VALUE_CD ,CREATED_DTTM ,CREATED_BY_USER ,LAST_PROCESSED_DTTM ,LAST_PROCESSED_BY_USER ,DIM_ATTRIBUTE_VALUE_SHORT_NM ,DIM_ATTRIBUTE_VALUE_DESC 
)
VALUES(328,331,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM100.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS100.1, noquote))") /* i18NOK:LINE */
VALUES(333,331,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM102.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS102.1, noquote))") /* i18NOK:LINE */
VALUES(336,331,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM105.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS105.1, noquote))") /* i18NOK:LINE */
VALUES(339,332,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM106.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS106.1, noquote))") /* i18NOK:LINE */
VALUES(340,332,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM107.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS107.1, noquote))") /* i18NOK:LINE */
VALUES(341,332,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM108.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS108.1, noquote))") /* i18NOK:LINE */
VALUES(342,332,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM109.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS109.1, noquote))") /* i18NOK:LINE */
VALUES(348,340,'&CCD_PRD_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM110.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS110.1, noquote))") /* i18NOK:LINE */
VALUES(349,340,'&COR_PRD_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM111.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS111.1, noquote))") /* i18NOK:LINE */
VALUES(350,340,'&LON_PRD_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM112.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS112.1, noquote))") /* i18NOK:LINE */
VALUES(351,340,'&MTG_PRD_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM113.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS113.1, noquote))") /* i18NOK:LINE */
VALUES(431,1164,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM120.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS120.1, noquote))") /* i18NOK:LINE */
VALUES(432,1164,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM121.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS121.1, noquote))") /* i18NOK:LINE */
VALUES(433,1164,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM122.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS122.1, noquote))") /* i18NOK:LINE */
VALUES(434,1164,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM123.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS123.1, noquote))") /* i18NOK:LINE */
VALUES(439,1166,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM125.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS125.1, noquote))") /* i18NOK:LINE */
VALUES(446,1166,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM128.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS128.1, noquote))") /* i18NOK:LINE */
VALUES(449,1166,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM131.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS131.1, noquote))") /* i18NOK:LINE */
VALUES(502,1214,'&CLOSE_REASON_CD_PPY','PPY',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM134.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS134.1, noquote))") /* i18NOK:LINE */
VALUES(503,1215,'&ACCT_STATUS_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM135.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS135.1, noquote))") /* i18NOK:LINE */
VALUES(504,1215,'&ACCT_STATUS_CLO','CLO',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM136.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS136.1, noquote))") /* i18NOK:LINE */
VALUES(505,1215,'&ACCT_STATUS_INA','INA',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM137.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS137.1, noquote))") /* i18NOK:LINE */
VALUES(559,1270,'&TRAN_TYP_DEP','DEP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM140.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS140.1, noquote))") /* i18NOK:LINE */
VALUES(560,1270,'&DIS_TRANS_TYPE','DIS',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM141.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS141.1, noquote))") /* i18NOK:LINE */
/*VALUES(570,1270,'&TRAN_TYP_PRD','PRD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM143.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS143.1, noquote))")*/
VALUES(571,1270,'&TRAN_TYP_PUR','PUR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM144.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS144.1, noquote))") /* i18NOK:LINE */
VALUES(575,1270,'&TRAN_TYP_WDR','WDR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM145.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS145.1, noquote))") /* i18NOK:LINE */
VALUES(577,1271,'&CHANNEL_CD_INN','INN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM147.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS147.1, noquote))") /* i18NOK:LINE */
VALUES(580,1274,'&MED_CD_CHQ','CHQ',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM149.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS149.1, noquote))") /* i18NOK:LINE */
VALUES(581,1274,'&MED_CD_CSH','CSH',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM150.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS150.1, noquote))") /* i18NOK:LINE */
VALUES(924,1910,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM151.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS151.1, noquote))") /* i18NOK:LINE */
VALUES(925,1910,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM152.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS152.1, noquote))") /* i18NOK:LINE */
VALUES(926,1910,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM153.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS153.1, noquote))") /* i18NOK:LINE */
VALUES(927,1910,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM154.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS154.1, noquote))") /* i18NOK:LINE */
VALUES(928,1910,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM155.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS155.1, noquote))") /* i18NOK:LINE */
VALUES(929,1910,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM156.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS156.1, noquote))") /* i18NOK:LINE */
VALUES(930,1910,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM157.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS157.1, noquote))") /* i18NOK:LINE */
VALUES(931,1910,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM158.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS158.1, noquote))") /* i18NOK:LINE */
VALUES(972,2010,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM159.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS159.1, noquote))") /* i18NOK:LINE */
VALUES(973,2010,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM160.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS160.1, noquote))") /* i18NOK:LINE */
VALUES(974,2010,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM161.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS161.1, noquote))") /* i18NOK:LINE */
VALUES(975,2010,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM162.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS162.1, noquote))") /* i18NOK:LINE */
VALUES(976,2010,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM163.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS163.1, noquote))") /* i18NOK:LINE */
VALUES(977,2010,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM164.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS164.1, noquote))") /* i18NOK:LINE */
VALUES(978,2010,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM165.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS165.1, noquote))") /* i18NOK:LINE */
VALUES(979,2010,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM166.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS166.1, noquote))") /* i18NOK:LINE */
VALUES(980,2022,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM167.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS167.1, noquote))") /* i18NOK:LINE */
VALUES(981,2022,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM168.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS168.1, noquote))") /* i18NOK:LINE */
VALUES(982,2022,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM169.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS169.1, noquote))") /* i18NOK:LINE */
VALUES(983,2022,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM170.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS170.1, noquote))") /* i18NOK:LINE */
VALUES(984,2022,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM171.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS171.1, noquote))") /* i18NOK:LINE */
VALUES(985,2022,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM172.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS172.1, noquote))") /* i18NOK:LINE */
VALUES(986,2022,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM173.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS173.1, noquote))") /* i18NOK:LINE */
VALUES(1038,2065,'&CCD_PRD_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM182.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS182.1, noquote))") /* i18NOK:LINE */
VALUES(1039,2065,'&COR_PRD_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM183.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS183.1, noquote))") /* i18NOK:LINE */
VALUES(1040,2065,'&LON_PRD_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM184.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS184.1, noquote))") /* i18NOK:LINE */
VALUES(1041,2065,'&MTG_PRD_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM185.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS185.1, noquote))") /* i18NOK:LINE */
VALUES(1086,1938,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM194.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS194.1, noquote))") /* i18NOK:LINE */
VALUES(1087,1938,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM195.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS195.1, noquote))") /* i18NOK:LINE */
VALUES(1088,1938,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM196.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS196.1, noquote))") /* i18NOK:LINE */
VALUES(1089,1938,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM197.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS197.1, noquote))") /* i18NOK:LINE */
VALUES(1090,1938,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM198.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS198.1, noquote))") /* i18NOK:LINE */
VALUES(1091,1938,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM199.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS199.1, noquote))") /* i18NOK:LINE */
;
quit;
proc sql;
insert into &lib_apdm..SOURCE_DIM_ATTRIB_VALUE_MASTER (
DIM_ATTRIBUTE_VALUE_SK ,SOURCE_COLUMN_SK ,DIM_ATTRIBUTE_VALUE ,DIM_ATTRIBUTE_VALUE_CD ,CREATED_DTTM ,CREATED_BY_USER ,LAST_PROCESSED_DTTM ,LAST_PROCESSED_BY_USER ,DIM_ATTRIBUTE_VALUE_SHORT_NM ,DIM_ATTRIBUTE_VALUE_DESC 
)
VALUES(1092,1938,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM200.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS200.1, noquote))") /* i18NOK:LINE */
VALUES(1093,1938,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM201.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS201.1, noquote))") /* i18NOK:LINE */
VALUES(1094,2022,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM202.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS202.1, noquote))") /* i18NOK:LINE */
/*
VALUES(1232,2205,'&TERM_TYPE_LNG','LNG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM203.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS203.1, noquote))")
VALUES(1233,2205,'&TERM_TYPE_MID','MID',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM204.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS204.1, noquote))")
VALUES(1234,2205,'&TERM_TYPE_SHT','SHT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM205.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS205.1, noquote))")
*/
VALUES(1236,2216,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM206.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS206.1, noquote))") /* i18NOK:LINE */
VALUES(1237,2216,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM207.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS207.1, noquote))") /* i18NOK:LINE */
VALUES(1238,2216,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM208.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS208.1, noquote))") /* i18NOK:LINE */
VALUES(1239,2216,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM209.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS209.1, noquote))") /* i18NOK:LINE */
VALUES(1240,2216,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM210.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS210.1, noquote))") /* i18NOK:LINE */
VALUES(1241,2216,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM211.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS211.1, noquote))") /* i18NOK:LINE */
VALUES(1242,2216,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM212.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS212.1, noquote))") /* i18NOK:LINE */
VALUES(1243,2216,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM213.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS213.1, noquote))") /* i18NOK:LINE */
VALUES(1268,747,'&CUS_ACT_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM214.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS214.1, noquote))") /* i18NOK:LINE */
VALUES(1270,745,'&IND_CUST_TYPE','IND',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM215.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS215.1, noquote))") /* i18NOK:LINE */
VALUES(1271,2237,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM216.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS216.1, noquote))") /* i18NOK:LINE */
VALUES(1272,2237,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM217.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS217.1, noquote))") /* i18NOK:LINE */
VALUES(1273,2237,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM218.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS218.1, noquote))") /* i18NOK:LINE */
VALUES(1274,2237,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM219.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS219.1, noquote))") /* i18NOK:LINE */
VALUES(1279,2238,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM221.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS221.1, noquote))") /* i18NOK:LINE */
VALUES(1288,2238,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM224.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS224.1, noquote))") /* i18NOK:LINE */
VALUES(1291,2238,'&SSL_ACCOUNT_SUB_TYPE','SSL',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM226.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS226.1, noquote))") /* i18NOK:LINE */
VALUES(1292,2238,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM227.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS227.1, noquote))") /* i18NOK:LINE */
VALUES(1315,2256,'&IND_CUST_TYPE','IND',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM228.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS228.1, noquote))") /* i18NOK:LINE */

VALUES(1430,2982,'&CCD_ACCOUNT_TYPE','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM120.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS120.1, noquote))") /* i18NOK:LINE */
VALUES(1431,2982,'&COR_ACCOUNT_TYPE','COR',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM121.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS121.1, noquote))") /* i18NOK:LINE */
VALUES(1432,2982,'&LON_ACCOUNT_TYPE','LON',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM122.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS122.1, noquote))") /* i18NOK:LINE */
VALUES(1433,2982,'&MTG_ACCOUNT_TYPE','MTG',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM123.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS123.1, noquote))") /* i18NOK:LINE */
VALUES(1435,2983,'&CHK_ACCOUNT_SUB_TYPE','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM125.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS125.1, noquote))") /* i18NOK:LINE */
VALUES(1438,2983,'&RDP_ACCOUNT_SUB_TYPE','RDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM128.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS128.1, noquote))") /* i18NOK:LINE */
VALUES(1441,2983,'&TDP_ACCOUNT_SUB_TYPE','TDP',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM131.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS131.1, noquote))") /* i18NOK:LINE */
VALUES(1444,3026,'&CLOSE_REASON_CD_PPY','PPY',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM134.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS134.1, noquote))") /* i18NOK:LINE */
VALUES(1445,3027,'&ACCT_STATUS_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM135.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS135.1, noquote))") /* i18NOK:LINE */
VALUES(1446,3027,'&ACCT_STATUS_CLO','CLO',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM136.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS136.1, noquote))") /* i18NOK:LINE */
VALUES(1447,3027,'&ACCT_STATUS_INA','INA',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM137.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS137.1, noquote))") /* i18NOK:LINE */

VALUES(1450,3086,'&ACC_HIER_CHK','CHK',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM206.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS206.1, noquote))") /* i18NOK:LINE */
VALUES(1451,3086,'&ACC_HIER_CCD','CCD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM207.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS207.1, noquote))") /* i18NOK:LINE */
VALUES(1452,3086,'&ACC_HIER_OD','OD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM208.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS208.1, noquote))") /* i18NOK:LINE */
VALUES(1453,3086,'&ACC_HIER_RD','RD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM209.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS209.1, noquote))") /* i18NOK:LINE */
VALUES(1454,3086,'&ACC_HIER_SAV','SAV',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM210.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS210.1, noquote))") /* i18NOK:LINE */
VALUES(1455,3086,'&ACC_HIER_SLN','SLN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM211.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS211.1, noquote))") /* i18NOK:LINE */
VALUES(1456,3086,'&ACC_HIER_TD','TD',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM212.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS212.1, noquote))") /* i18NOK:LINE */
VALUES(1457,3086,'&ACC_HIER_ULN','ULN',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM213.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS213.1, noquote))") /* i18NOK:LINE */
VALUES(1458,2895,'&CUS_ACT_ACT','ACT',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM214.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS214.1, noquote))") /* i18NOK:LINE */
VALUES(1459,2894,'&IND_CUST_TYPE','IND',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM215.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS215.1, noquote))") /* i18NOK:LINE */
VALUES(1460,3089,'&IND_CUST_TYPE','IND',"%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(datetime(),datetime.)"dt,"&sysuserid","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_SM228.1, noquote))","%sysfunc(sasmsg(work.rmcr_message_bnkfdn_banking,SOURCE_DIM_ATTRIB_VALUE.DIM_ATTRIBUTE_VALUE_DS228.1, noquote))") /* i18NOK:LINE */


;
quit;

%mend rmcr_insrt_src_dim_attrib;
