--- 
- hosts: localhost
    
  tasks:

  - name: create new inventory
    shell: cat /tmp/inventory.head inventory.body > inventory.ini


  - name: Set OpenLdapServer
    blockinfile:
      dest: inventory.ini
      marker: "# {mark} ADD SERVER"
      insertafter: '\[openldapserver\]'
      content: |
        stateful
    tags:
      - updateinventory

  - name: prepare client list
    shell: cat /tmp/inventory.head | awk '{print $1}' > /tmp/inventory.head.short

  - name: Set clients
    blockinfile:
      dest: inventory.ini
      insertafter: '\[openldapclients\]'
      block: "{{ lookup('file', '/tmp/inventory.head.short') }}"
      marker: "# {mark} ADD CLIENTS"
    tags:
      - updateinventory
